import Link from "next/link";

export function Block2Section() {
  return (
    <>
      <section className={"py-stack-lg bg-white relative"}><div className={"px-margin-desktop max-w-container-max mx-auto"}><div className={"bg-surface-container-low flex flex-col md:flex-row overflow-hidden border border-outline-variant/30"}><div className={"md:w-1/2 relative h-96 md:h-auto overflow-hidden group"}><div className={"w-full h-full bg-cover bg-center group-hover:scale-110 transition-transform duration-[3s]"} data-alt={"A visual representation of 'Zero-Defect Quality Control' in action. A precision laser scanner is checking a metallic component on a high-speed conveyor belt. Data overlays of blue glowing lines and measurement points are digitally layered onto the scene. The overall style is a fusion of technical glassmorphism and industrial minimalist design, evoking professional engineering authority."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuCCU8pxP0WPrWfYs503uToUm7xlphQsPmrCo7NDOZS0OxrXh8NtLpq9BniVI4E7BRv2NeOh3YDpt_v0Onto_v1goiCK3X5oLIOpKuWF8UA7fbBvZ57stO11BlonDqmuHozS6PI9UnCwP3wQeEwIdlKqJIdMIRNJd1e1aUn-oI7135QBsD_exFW8fu3NdzSu_DaMHiKXO9Sp0vVgSpeNwd_LCBsWDWA_H1hALjbNZYhwCNVJQdT-l7ZkKnIw0_-MQ4XcbeD-2PXbOC4')"}}></div><div className={"absolute inset-0 bg-primary/20 mix-blend-overlay"}></div></div><div className={"md:w-1/2 p-12 lg:p-20 flex flex-col justify-center"}><span className={"font-label-sm text-label-sm text-primary uppercase tracking-widest mb-4"}>{"Case Study"}</span><h3 className={"font-display-lg text-headline-lg mb-6 leading-tight"}>{"Zero-Defect Quality Control"}</h3><p className={"font-body-lg text-body-lg text-on-surface-variant mb-8"}>{"Implementing a vision-guided closed-loop system for a Tier-1 automotive manufacturer, reducing line rejects by 94.2% while increasing throughput by 12%."}</p><Link href={"/case-studies"} className={"inline-flex items-center gap-2 font-label-sm text-label-sm font-bold uppercase border-b border-primary pb-1 self-start hover:gap-4 transition-all"}>{"Read Impact Report"}</Link></div></div></div></section>
    </>
  );
}
