import Link from "next/link";

export function Block3Section() {
  return (
    <>
      <section className={"py-stack-lg"}><div className={"max-w-container-max mx-auto px-margin-desktop"}><h3 className={"font-label-sm text-label-sm text-on-surface-variant uppercase tracking-widest mb-stack-md text-center"}>{"Related Disciplines"}</h3><div className={"grid grid-cols-1 md:grid-cols-2 gap-gutter"}><Link href={"/hardware-development"} className={"group relative block h-64 rounded-xl overflow-hidden"}><div className={"absolute inset-0 bg-cover bg-center transition-transform duration-500 group-hover:scale-110"} data-alt={"A clean industrial laboratory setting showing high-precision hardware development tools. Oscillosopes with sharp digital waveforms and micro-soldering stations under bright, neutral white lighting. The environment is organized and clinical, echoing a sense of technical perfection and advanced electronic engineering."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuDhI2Xh8f_dEfjPtZKKEAAGXjMvXd_jcMqwQ1gzQotJ3aHn11GkloR_dnviBG9cdSe4NWaialzWCUK88ufVMdGs0RTQVBSJzjffdZu7_AeprH1NXIxgknabs_SPoyVMSSFAYyiGeHkL8uMOrVAIpD2__NBsWJCFSDgW4xxiaE0UQUYubfv4y8aL4gXrjcNleUglNDQRGFGohNqST92mKjQWpdblMQG60oqKSaI2XEMFlM-YzBDP8IGMTQHluygpqrgzo6sH1mOjpcU')"}}></div><div className={"absolute inset-0 bg-black/40 group-hover:bg-black/20 transition-colors"}></div><div className={"absolute inset-0 p-8 flex flex-col justify-end"}><h4 className={"text-white font-headline-md text-headline-md"}>{"Hardware Development"}</h4><p className={"text-white/80 font-body-md text-body-md"}>{"Custom PCB design and prototyping for integrated systems."}</p></div></Link><Link href={"/hardware-development"} className={"group relative block h-64 rounded-xl overflow-hidden"}><div className={"absolute inset-0 bg-cover bg-center transition-transform duration-500 group-hover:scale-110"} data-alt={"An industrial IoT concept image showing interconnected factory machinery. Data points are visualized as digital nodes hovering over large industrial arms and assembly lines. The color palette consists of cool grays and sharp innovation cyan accents, representing a high-tech smart factory infrastructure."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuA_rDU8rNwIcNwxYJJ6znb9efCGALOqmOiO4g6zSao3X5sYigtbXiaKuwnDeIOh3-uXu-bHIL11_-36PWOhZ656RJBPW8l-ace1I7tC4Yj3Ty3m3BVf-Tg2T5zeWql5BNNr7FEFjGu4oJcgIPdbpYb24ySQXftX7CbX1TCB8Wi2MZ3Xe02TjdBP--Sr8NdF5ilCkw5h9j4tgUZWErT2lFIFx81iiMO0N3Va2b825f5Mi3w5ndOmkQJGtmr1Nxolsa7g7EUXvFdtAA8')"}}></div><div className={"absolute inset-0 bg-black/40 group-hover:bg-black/20 transition-colors"}></div><div className={"absolute inset-0 p-8 flex flex-col justify-end"}><h4 className={"text-white font-headline-md text-headline-md"}>{"Industrial IoT"}</h4><p className={"text-white/80 font-body-md text-body-md"}>{"Edge-to-cloud connectivity and large-scale device management."}</p></div></Link></div></div></section>
    </>
  );
}
