import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <section className={"relative overflow-hidden pt-stack-lg pb-24 md:pt-32 md:pb-40"}><div className={"absolute inset-0 z-0"}><div className={"absolute inset-0 bg-gradient-to-b from-transparent to-background/90 z-10"}></div><div className={"w-full h-full bg-center bg-cover scale-105"} data-alt={"A hyper-realistic, macro close-up of a high-performance printed circuit board (PCB). Glowing cyan and electric blue light traces represent data pulses moving through complex gold-plated micro-circuitry. The lighting is dramatic and moody, set in a dark industrial environment with high-contrast shadows. The aesthetic is clean-room precise, reflecting technical authority and high-stakes engineering reliability."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuCyOe3i5ZFvxdB7WlJb3GT0AdZIAbeYpyijLRo15n_mBwFSJgZxOROGvuCmzCLZ7xAHMILFM9pzG3je5CgjlAQ_mrHazu9aGxTm1Ses3HUnMDc36uYb5uWu9bGw8PiD8fe748gzmK5lGX9tSwE7KB9lWEgr82RiOLAgovekpmNTAn9WZQ09UEUUe3F6D4UdHnmzNT_eJCR9bGFszSpn_QmsOSUwFLMDr758ixxt2SulEmL8FBO6DrJaKvwgFfj-c5vnlx6JrFWbdOE')"}}></div></div><div className={"relative z-20 max-w-container-max mx-auto px-margin-desktop"}><div className={"max-w-3xl"}><div className={"inline-flex items-center gap-2 px-3 py-1 bg-primary/5 border border-primary/10 rounded-full mb-stack-md"}><span className={"w-2 h-2 rounded-full bg-primary animate-pulse"}></span><span className={"font-label-sm text-label-sm text-primary tracking-widest uppercase"}>{"Specialized Engineering"}</span></div><h1 className={"font-display-lg text-display-lg text-primary mb-stack-md leading-none"}>{"\n                        Industrial-Grade Firmware for Mission-Critical Systems\n                    "}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant mb-stack-lg max-w-2xl"}>{"\n                        Engineering deterministic, low-latency firmware solutions that power the next generation of industrial automation, medical devices, and aerospace infrastructure.\n                    "}</p><div className={"flex flex-wrap gap-stack-sm"}><Link href={"/technical-downloads-and-sdks"} className={"bg-primary text-on-primary px-8 py-4 font-label-sm text-label-sm rounded-lg technical-glow transition-all"}>{"Download Capability Statement"}</Link><Link href={"/case-studies"} className={"border border-outline px-8 py-4 font-label-sm text-label-sm rounded-lg hover:bg-surface-container transition-all"}>{"View Case Studies"}</Link></div></div></div></section>
    </>
  );
}
