import Link from "next/link";

export function TechnicalBadgeSection() {
  return (
    <>
      <header className={"relative min-h-[921px] flex items-center overflow-hidden grid-pattern"}><div className={"max-w-container-max mx-auto px-margin-desktop w-full relative z-10 py-stack-lg"}><div className={"max-w-3xl"}><div className={"flex items-center gap-2 mb-stack-sm"}><span className={"w-2 h-2 rounded-full bg-primary animate-pulse"}></span><span className={"font-label-sm text-label-sm uppercase tracking-widest text-on-surface-variant"}>{"Precision Engineering Solutions"}</span></div><h1 className={"font-display-lg text-display-lg mb-stack-md leading-none text-primary"}>{"\n                    The Pulse of "}<br /><span className={"text-on-primary-container"}>{"Industrial Energy."}</span></h1><p className={"font-body-lg text-body-lg text-on-surface-variant mb-stack-lg max-w-2xl"}>{"\n                    High-fidelity real-time monitoring and predictive load balancing for mission-critical infrastructure. Harness the power of ESP32 edge processing and Azure IoT cloud scalability to eliminate downtime.\n                "}</p><div className={"flex flex-wrap gap-4"}><Link href={"/smart-grid"} className={"bg-primary text-on-primary px-8 py-4 rounded font-label-sm text-label-sm flex items-center gap-2 hover:bg-[#2563EB] transition-colors technical-glow group"}>{"\n                        Deploy System\n                        "}<span className={"material-symbols-outlined transition-transform group-hover:translate-x-1"}>{"arrow_forward"}</span></Link><Link href={"/smart-grid"} className={"border border-outline-variant text-on-surface px-8 py-4 rounded font-label-sm text-label-sm hover:bg-surface-container transition-colors"}>{"\n                        View Technical Docs\n                    "}</Link></div></div></div><div className={"absolute right-margin-desktop bottom-margin-desktop hidden xl:block"}><div className={"bg-white/80 backdrop-blur-md p-6 border border-outline-variant/30 rounded shadow-sm"}><div className={"flex gap-stack-md items-center"}><div><div className={"font-label-sm text-[10px] text-on-surface-variant uppercase tracking-tighter"}>{"System Latency"}</div><div className={"font-headline-md text-headline-md text-primary"}>{"< 15ms"}</div></div><div className={"w-[1px] h-10 bg-outline-variant"}></div><div><div className={"font-label-sm text-[10px] text-on-surface-variant uppercase tracking-tighter"}>{"Sensor Accuracy"}</div><div className={"font-headline-md text-headline-md text-primary"}>{"99.98%"}</div></div></div></div></div></header>
    </>
  );
}
