import Link from "next/link";

export function Block2Section() {
  return (
    <>
      <section className={"py-stack-lg bg-surface relative overflow-hidden"}><div className={"px-margin-desktop max-w-container-max mx-auto relative z-10"}><div className={"max-w-4xl mx-auto text-center"}><h2 className={"font-headline-lg text-headline-lg mb-8"}>{"Engineering Excellence for "}<br />{"Sustainable Frontiers"}</h2><p className={"font-body-lg text-body-lg text-on-surface-variant mb-12"}>{"From power electronics design to secure OTA updates, our expertise ensures your infrastructure remains ahead of the curve."}</p><div className={"grid grid-cols-1 md:grid-cols-2 gap-gutter text-left mb-16"}><div className={"flex gap-4 items-start"}><div className={"p-3 bg-primary-container rounded-lg text-white"}><span className={"material-symbols-outlined"}>{"bolt"}</span></div><div><h5 className={"font-headline-md text-headline-md mb-2"}>{"Power Electronics"}</h5><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Custom PCB design for high-current applications and advanced thermal modeling."}</p></div></div><div className={"flex gap-4 items-start"}><div className={"p-3 bg-primary-container rounded-lg text-white"}><span className={"material-symbols-outlined"}>{"system_update"}</span></div><div><h5 className={"font-headline-md text-headline-md mb-2"}>{"Secure OTA Updates"}</h5><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Failsafe remote firmware deployment with multi-layer verification protocols."}</p></div></div></div><div className={"inline-flex flex-col items-center"}><Link href={"/metropolis-ev-transit"} className={"bg-primary text-on-primary text-xl px-12 py-6 rounded-xl font-label-sm text-label-sm hover:scale-105 transition-transform duration-300 shadow-xl"}>{"\n                            Scale Your EV Network\n                        "}</Link><p className={"mt-6 text-label-sm font-label-sm text-on-surface-variant"}>{"Contact our infrastructure experts for a technical consultation."}</p></div></div></div></section>
    </>
  );
}
