import Link from "next/link";

export function GlassmorphismStatsOverlaySection() {
  return (
    <>
      <section className={"relative min-h-[870px] flex items-center overflow-hidden"}><div className={"absolute inset-0 z-0"}><div className={"w-full h-full bg-cover bg-center opacity-60"} data-alt={"A futuristic, high-tech EV charging station in a clean-room environment with technical glass surfaces and ultra-modern white and black accents. The lighting is cold and clinical, emphasizing the precision-engineered components and illuminated blue status pips. The scene feels like a high-end industrial tech laboratory for renewable energy infrastructure."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuDGaKTUnXoOsHCpuoj4nJtragPODlXVB3-I9m0EAYbuhFGBkziiIq88wKDcEpuk-0PFwleULbWyBEcC90zSTvCW6eRNsA8drHzG-wuhjEJz9lGVWgizfGTfbLR8NKjRSANIgylPXdsp1geI45oEA1xw52aPh5oFebQE2baVrTSlnGSYfYJIU4JSKuvA4Mvh6Iz1zDeua-GZNxO0HaYnTce3QTc3jZNzjQQUoMc9yCe60IbZMaqpMgTJkFlwRCW9g5m758MzePZ5CUA')"}}></div></div><div className={"relative z-10 px-margin-desktop max-w-container-max mx-auto w-full"}><div className={"max-w-3xl"}><span className={"inline-block py-1 px-3 mb-6 bg-primary-container text-on-primary-fixed rounded-full font-label-sm text-label-sm"}>{"TRANSFORMING MOBILITY"}</span><h1 className={"font-display-lg text-display-lg mb-8 leading-tight"}>{"Next-Gen Electronics for "}<span className={"text-primary underline decoration-2 underline-offset-8"}>{"EV Charging Ecosystems"}</span></h1><p className={"font-body-lg text-body-lg text-on-surface-variant mb-10 max-w-2xl"}>{"Engineering ultra-reliable power electronics and secure cloud integration for the global electric vehicle infrastructure frontier."}</p><div className={"flex gap-4"}><Link href={"/metropolis-ev-transit"} className={"bg-primary text-on-primary px-8 py-4 rounded-lg font-label-sm text-label-sm flex items-center gap-2 group transition-all"}>{"\n                            Scale Your EV Network\n                            "}<span className={"material-symbols-outlined group-hover:translate-x-1 transition-transform"}>{"arrow_forward"}</span></Link><Link href={"/metropolis-ev-transit"} className={"glass-card text-primary border border-outline/20 px-8 py-4 rounded-lg font-label-sm text-label-sm"}>{"Technical Whitepapers"}</Link></div></div></div><div className={"absolute bottom-12 right-margin-desktop hidden xl:flex gap-6"}><div className={"glass-card p-6 rounded-xl w-64"}><div className={"text-headline-md font-headline-md mb-1"}>{"99.99%"}</div><div className={"text-label-sm font-label-sm text-on-surface-variant"}>{"UPTIME RELIABILITY"}</div></div><div className={"glass-card p-6 rounded-xl w-64"}><div className={"text-headline-md font-headline-md mb-1"}>{"SiC-POWERED"}</div><div className={"text-label-sm font-label-sm text-on-surface-variant"}>{"HIGH POWER EFFICIENCY"}</div></div></div></section>
    </>
  );
}
