import type { Config } from "tailwindcss";

/** Client brand: Navy #021a3e, Teal #0095a4, Gold #fdb912, Montserrat */
const BRAND = {
  navy: "#021a3e",
  teal: "#0095a4",
  gold: "#fdb912",
} as const;

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/content/**/*.{html,js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          navy: BRAND.navy,
          teal: BRAND.teal,
          gold: BRAND.gold,
        },
        "surface-container-low": "#f4f7f9",
        "on-primary": "#ffffff",
        "surface-container-high": "#e8eef2",
        "on-tertiary": BRAND.navy,
        "on-tertiary-fixed": BRAND.navy,
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#006670",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#c9a227",
        outline: "#6b7280",
        "tertiary-fixed": "#fef3d6",
        "outline-variant": "#c5d0d8",
        "secondary-fixed-dim": "#b8e4ea",
        "secondary-fixed": "#e6f6f8",
        "surface-container-highest": "#dfe8ed",
        "surface-dim": "#e2e8ed",
        "tertiary-container": "#fff8e8",
        "primary-container": BRAND.navy,
        "on-secondary-container": "#006670",
        "on-error-container": "#93000a",
        "surface-bright": "#fcfdfd",
        "tertiary-fixed-dim": "#fde8a8",
        error: "#ba1a1a",
        "surface-container": "#eef3f6",
        "on-surface-variant": "#4a5568",
        "primary-fixed": "#e6f6f8",
        background: "#fafcfd",
        "on-background": BRAND.navy,
        "on-primary-container": "#8ec5cc",
        "inverse-surface": BRAND.navy,
        "on-error": "#ffffff",
        secondary: BRAND.teal,
        "surface-tint": BRAND.teal,
        "on-surface": BRAND.navy,
        "secondary-container": "#e6f6f8",
        "surface-variant": "#e8eef2",
        "on-tertiary-fixed-variant": "#8a6d12",
        primary: BRAND.navy,
        "on-primary-fixed-variant": "#006670",
        "inverse-on-surface": "#f0f7f8",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": BRAND.navy,
        surface: "#fafcfd",
        "inverse-primary": "#8ec5cc",
        "on-primary-fixed": BRAND.navy,
        "primary-fixed-dim": "#b8e4ea",
        tertiary: BRAND.gold,
        "accent-blue": BRAND.teal,
        "innovation-cyan": BRAND.teal,
        "deep-navy": BRAND.navy,
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        "container-max": "1440px",
        gutter: "24px",
        "margin-mobile": "16px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        base: "8px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        montserrat: ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "display-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-lg-mobile": [
          "var(--font-montserrat)",
          "Montserrat",
          "sans-serif",
        ],
        "label-sm": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
      },
      boxShadow: {
        "tech-glow": "0 0 20px rgba(0, 149, 164, 0.12)",
        "tech-glow-lg": "0 20px 40px rgba(0, 149, 164, 0.08)",
      },
      animation: {
        "scroll-x": "scroll-x 30s linear infinite",
      },
      keyframes: {
        "scroll-x": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
