import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/content/**/*.{html,js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f4",
        "on-primary": "#ffffff",
        "surface-container-high": "#eae7e9",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#281809",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#404758",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#997f6a",
        outline: "#76777d",
        "tertiary-fixed": "#fddcc4",
        "outline-variant": "#c6c6cc",
        "secondary-fixed-dim": "#c0c6db",
        "secondary-fixed": "#dce2f7",
        "surface-container-highest": "#e5e2e3",
        "surface-dim": "#dcd9da",
        "tertiary-container": "#281809",
        "primary-container": "#151b2a",
        "on-secondary-container": "#5c6274",
        "on-error-container": "#93000a",
        "surface-bright": "#fcf8fa",
        "tertiary-fixed-dim": "#e0c1a9",
        error: "#ba1a1a",
        "surface-container": "#f0edee",
        "on-surface-variant": "#45474c",
        "primary-fixed": "#dce2f6",
        background: "#fcf8fa",
        "on-background": "#1b1b1d",
        "on-primary-container": "#7d8496",
        "inverse-surface": "#303031",
        "on-error": "#ffffff",
        secondary: "#575e70",
        "surface-tint": "#585e6f",
        "on-surface": "#1b1b1d",
        "secondary-container": "#d9dff5",
        "surface-variant": "#e5e2e3",
        "on-tertiary-fixed-variant": "#584231",
        primary: "#000000",
        "on-primary-fixed-variant": "#404757",
        "inverse-on-surface": "#f3f0f1",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#141b2b",
        surface: "#fcf8fa",
        "inverse-primary": "#c0c6da",
        "on-primary-fixed": "#151b2a",
        "primary-fixed-dim": "#c0c6da",
        tertiary: "#000000",
        "accent-blue": "#2563EB",
        "deep-navy": "#0B1220",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        "container-max": "1440px",
        gutter: "24px",
        "margin-mobile": "16px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        base: "8px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-md": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "label-sm": ["var(--font-geist)", "Geist", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
      boxShadow: {
        "tech-glow": "0 0 20px rgba(37, 99, 235, 0.08)",
        "tech-glow-lg": "0 20px 40px rgba(37, 99, 235, 0.05)",
      },
      animation: {
        "scroll-x": "scroll-x 30s linear infinite",
      },
      keyframes: {
        "scroll-x": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
