import { StitchImage } from "@/components/ui/StitchImage";

export function Block2Section() {
  return (
    <>
      <section className={"py-stack-lg bg-surface-container-low"}><div className={"max-w-container-max mx-auto px-margin-desktop"}><div className={"text-center mb-stack-lg"}><h2 className={"font-headline-lg text-headline-lg"}>{"Industrial Applications"}</h2><p className={"font-body-lg text-body-lg text-on-surface-variant"}>{"Engineered for the most demanding technical environments."}</p></div><div className={"grid grid-cols-1 md:grid-cols-2 gap-gutter"}><div className={"group relative overflow-hidden rounded-xl aspect-[16/9]"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDdS9VlZWBhK7LSYo-plIKqgLDlJ4qDjdYJCwzce_uGWBjMhwShKKd8SBaHq9cs5-eE2OrAeMGpWP2ryy8m_RrouKDQuHX0DiDRLmzt6a1cBrny_CmRmtviQxh5odWhWbreO97nfZ25Bcdj8UNvcsRyqe5TOdMetttbi56Y--8ZyWtNFYGtqvCrfm0R6tbnoXuy0Y-EW1oJAZ4rhKdVPnVrtQyM1RAwWhx-sB_WrH0VNd3b1LGgaGvynHWNu5QP7iqM0v6bC4BEXRg"} alt={"A sprawling solar renewable energy farm at dusk with thousands of solar panels. The lighting is dramatic, with orange and purple hues reflecting off the glass. Superimposed are technical diagrams showing the grounding grid and Mind Matrix sensors. Industrial minimalist style with a focus on clean energy and technical authority."} className={"w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"} /><div className={"absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent p-8 flex flex-col justify-end"}><h4 className={"font-headline-md text-headline-md text-white"}>{"Renewable Energy"}</h4><p className={"font-body-md text-body-md text-white/70"}>{"Monitoring PV field grounding networks across thousands of acres."}</p></div></div><div className={"group relative overflow-hidden rounded-xl aspect-[16/9]"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDfg6XVFm6gF8nb5YHy8Bo0MMfF65kQGYGdQI9TfA8Gptw-pxKe-TGW-ubu85E1j4Vp7xJqX2qqLVI-FR_OoCPD17nn155g1q2Ok6d9rvwHv64ZkiG1rRKIb7-U2wkErxGpfztC6GisQR-Vd9ErOe832by--Q_MiwV-W3E119-uNF1s2tjLD2n4ozhLRz84u-MrP9PiNCahqYehvq1ZcAwLtyAanRtffyBMGKvlVi4T8YzyNQuhMt9G2hH6gV8qN0XhqjkoyrSzfq0"} alt={"A massive high-voltage power substation filled with complex transformers and steel infrastructure. The lighting is crisp and cold, highlighting the metallic textures. Strategic overlays show potential lightning strike points and the Mind Matrix monitoring system in action. Precision industrial photography aesthetic."} className={"w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"} /><div className={"absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent p-8 flex flex-col justify-end"}><h4 className={"font-headline-md text-headline-md text-white"}>{"Power Substations"}</h4><p className={"font-body-md text-body-md text-white/70"}>{"Ensuring safety and continuity in critical utility infrastructure."}</p></div></div></div></div></section>
    </>
  );
}
