import { StitchImage } from "@/components/ui/StitchImage";

export function SubtleTechBackgroundEffectSection() {
  return (
    <>
      <section className={"py-stack-lg"}><div className={"max-w-container-max mx-auto px-margin-desktop"}><div className={"bg-primary-container text-on-primary-container rounded-3xl p-stack-lg relative overflow-hidden"}><div className={"absolute inset-0 opacity-10 pointer-events-none technical-grid"}></div><div className={"relative z-10 grid md:grid-cols-2 gap-stack-lg items-center"}><div><h2 className={"font-headline-lg text-headline-lg text-on-surface-variant/20 mb-stack-sm"}>{"Ready to Upgrade?"}</h2><p className={"font-display-lg text-headline-lg text-white mb-stack-md"}>{"Engineering the future of autonomous systems."}</p><div className={"flex gap-stack-sm"}><button className={"bg-surface-container-lowest text-primary px-stack-lg py-stack-sm rounded-lg font-label-sm text-label-sm hover:scale-105 transition-transform"}>{"Request a Demo"}</button><button className={"border border-on-primary-container/30 text-white px-stack-lg py-stack-sm rounded-lg font-label-sm text-label-sm hover:bg-white/10 transition-colors"}>{"Talk to an Engineer"}</button></div></div><div className={"hidden md:block"}><div className={"aspect-video glass-card border-white/10 rounded-xl overflow-hidden p-stack-sm"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuAPp_dNdKTy91_TMF05JIxwmsrJ8jeZjWGjx63HjoYiXUazl-ycSxRpM4Vqynmk9k8nHNgHpYOPU9LsvdVI-oYFJx6EfUTvvJFOOuTVh45Qi5hGD-SoHHDOm8bnalQyQpv2592d3VK_zLNrTSgRN9Yf76DfRgtrMG4RGE3n9o0Eya2imhXUJoF1f3OZ_ohpiDHoN9jArgx--Tfb9JLXm_zErsWUGZQV-OjoAVZ3yf1bx60hCc-sESqkyg6s1TeQf0GH2mZUriZOVVI"} alt={"A wide-angle professional shot of a modern automated assembly line in a clean, industrial factory environment. Articulated robot arms move in a choreographed motion. The lighting is sophisticated, using cool tones and sharp, clean reflections off metallic surfaces. The image emphasizes precision, speed, and technical superiority."} className={"w-full h-full object-cover rounded-lg"} /></div></div></div></div></div></section>
    </>
  );
}
