import Link from "next/link";
import { StitchImage } from "@/components/ui/StitchImage";

export function TechnicalOverlayTagSection() {
  return (
    <>
      <section className={"relative overflow-hidden pt-20 pb-32"}><div className={"max-w-container-max mx-auto px-margin-desktop grid grid-cols-1 md:grid-cols-12 gap-gutter items-center"}><div className={"md:col-span-6 space-y-stack-md"}><div className={"inline-flex items-center gap-base px-stack-sm py-1 bg-primary-fixed text-on-primary-fixed-variant rounded-full"}><span className={"material-symbols-outlined text-[16px]"}>{"verified"}</span><span className={"font-label-sm text-label-sm"}>{"SIL3 CERTIFIED SYSTEM"}</span></div><h1 className={"font-display-lg text-display-lg leading-[1.05]"}>{"Industrial Controller Matrix-X1"}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-lg"}>{"\n                        The ultimate edge-processing unit for ultra-low latency industrial automation. Engineered for high-stakes precision in robotics and assembly lines.\n                    "}</p><div className={"flex flex-wrap gap-stack-sm pt-base"}><Link href={"/industrial-controller"} className={"px-stack-lg py-stack-sm bg-primary text-on-primary rounded-lg font-label-sm text-label-sm hover:shadow-[0_0_20px_rgba(37,99,235,0.2)] transition-all"}>{"Download Datasheet"}</Link><Link href={"/industrial-controller"} className={"px-stack-lg py-stack-sm border border-outline-variant text-on-surface rounded-lg font-label-sm text-label-sm hover:bg-surface-container-low transition-all"}>{"Explore Architecture"}</Link></div></div><div className={"md:col-span-6 relative"}><div className={"glass-card aspect-[4/3] rounded-xl overflow-hidden p-stack-sm"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDOif_bnp00aAPWQh3G-kpAWFzMXah_ryCXoBDC1x6nx1M5rN8oC4Csasx5L5_7s2NVRRemWzOKVPRIpdHZ6q5zmLx_qjdLtLFn0OzliJn-GAUMJ-d-veR9cr2sDhR8tun30gY3sac9vueSuyg1H6r-ArvYpLWAsl7xss_OReQQnc6mj-m3SMsnRPV_VSqfjBDpqfX4GVBMn9Ez5ouVSrbAmFtJoxN-cKJ6B6n_65t_-Paa07-Vxk-TyteIK2Y-Xz1ctKIQsHIP5iM"} alt={"A high-tech industrial programmable logic controller (PLC) shown in a clean-room studio setting. The device features a metallic brushed steel chassis with glowing status LEDs and fiber optic ports. Lighting is crisp and technical with cold blue and clinical white highlights. The atmosphere is professional, suggesting advanced engineering and reliability."} className={"w-full h-full object-cover rounded-lg"} /></div><div className={"absolute -bottom-6 -left-6 glass-card p-stack-md rounded-lg shadow-xl hidden lg:block"}><p className={"font-label-sm text-label-sm text-on-surface-variant mb-1"}>{"DETERMINISTIC LATENCY"}</p><p className={"font-headline-md text-headline-md"}>{"<100μs Jitter"}</p></div></div></div></section>
    </>
  );
}
