import Link from "next/link";

export function Block5Section() {
  return (
    <>
      <section className={"py-stack-lg bg-white"}><div className={"px-margin-desktop max-w-container-max mx-auto"}><h3 className={"font-label-sm text-label-sm text-on-surface-variant mb-stack-md uppercase tracking-widest"}>{"Related Projects"}</h3><div className={"grid grid-cols-1 md:grid-cols-2 gap-gutter"}><Link href={"/industrial-iot-solutions"} className={"group relative aspect-[16/7] overflow-hidden rounded-xl"}><div className={"absolute inset-0 bg-cover bg-center transition-transform duration-700 group-hover:scale-110"} data-alt={"An artistic view of complex industrial IoT machinery in a high-tech factory environment, with glowing blue and teal accents. The scene is crisp and highly technical, showcasing sensors and robotic arms in a clean-room aesthetic."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuBxuxorXQLrFSEaaGQbMTys-6XWRAvjPicvAOYFFXugWzNk-eDCL62itHfp6cWf0kV1VZNRfTUvAm-oYOBflzp5UMXztKsV2NTHRWAjeHC1zRPfR2XL95FJCy_lTH_Mi7yUMhrXjQ1sVGXfd3vzI9xPORLScSO1K5J_t8aIzBKPggxtnXobDtYNZOBfBKryZjg8pRcm9wUeHDLjRhrWcCKiFa7SOlMIV-4NVaxtYmFjazcGyRPPtZ3QotvpOIzh5AknX9WNV4M8824')"}}></div><div className={"absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex flex-col justify-end p-stack-lg"}><span className={"text-white/60 font-label-sm text-label-sm"}>{"CASE STUDY"}</span><h4 className={"text-white font-headline-md text-headline-md"}>{"Industrial IoT Solutions"}</h4></div></Link><Link href={"/industrial-iot-solutions"} className={"group relative aspect-[16/7] overflow-hidden rounded-xl"}><div className={"absolute inset-0 bg-cover bg-center transition-transform duration-700 group-hover:scale-110"} data-alt={"A specialized engineering view of an oil and gas refinery complex at night, with thousands of precise lights illuminating the steel structures. The mood is powerful and industrial, using a dark palette with silver and electric blue highlights."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuDLLdpBlLXWRWp4ROQEB-Hzg8Cipf7GjCb_PAuIUagyrWPK8I7UPyk5AOF1OwPSN2586Av0tRWHlV3Rot6NNjGyYJzb2fg9AHmxWZA5uomQ9ndcIOJDAbtgKVbDy0hwMrWe4UzaRRwraDH1L9BSnkKVokMt_ha5Wqgp2PoxiEsMt_lgGAf5uVVhkz6zwEE8PZ9FJEslqUtHBe5D7B7R5zUFV6s91AFSdH_Bh89M8Kiy8lac3JlB1mR0iDxmtbrfvEM3d6VfBp2YduY')"}}></div><div className={"absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex flex-col justify-end p-stack-lg"}><span className={"text-white/60 font-label-sm text-label-sm"}>{"SECTOR OVERVIEW"}</span><h4 className={"text-white font-headline-md text-headline-md"}>{"Oil & Gas Engineering"}</h4></div></Link></div></div></section>
    </>
  );
}
