import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <section className={"relative h-[870px] overflow-hidden flex items-center"}><div className={"absolute inset-0 z-0"}><div className={"absolute inset-0 bg-gradient-to-r from-primary-container/90 via-primary-container/40 to-transparent z-10"}></div><div className={"w-full h-full bg-cover bg-center"} data-alt={"A cinematic wide shot of an industrial offshore oil rig at sunset, featuring deep oranges and dark silhouettes. Overlaid across the image are glowing cyan and white digital network lines and nodes that pulse with light, suggesting a high-tech communication layer. The atmosphere is sophisticated and secure, with a technical glass-like clarity and high-end industrial minimalism."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuCMnWGL3qzCNcS_T_zS8JH8xVc_Y80D8crAbNLt8SuXyLynDgd8Q9Nm0s5VqLWYuIntklqms0j8hltV381fxFLIiL773GLptImTFQmYmY3uUZTOshMo4Y16Oc6Ct5cFbNoI3s-qlOjwPfaW9Q7H9dWe0MgAW4zqkUtntAjP9XfLekoC6DcRRwFHgnSPpBh-fyuEnIS-cC9V8MKWaUNxyfr-PH6Nv1OlHa1ooFR8YTku853G5C9AQPTRzQFzPaOAnpp3COU0JBVgo1E')"}}></div></div><div className={"relative z-20 px-margin-desktop max-w-container-max mx-auto w-full"}><div className={"max-w-3xl"}><div className={"flex items-center gap-base mb-stack-md"}><span className={"w-12 h-[1px] bg-outline"}></span><span className={"font-label-sm text-label-sm tracking-widest text-on-primary-container uppercase"}>{"Industrial Cyber-Security"}</span></div><h1 className={"font-display-lg text-display-lg text-on-primary-fixed mb-stack-md leading-none"}>{"Quantum-Ready Data: Securing the Digital Frontier"}</h1><p className={"font-body-lg text-body-lg text-on-primary-container/80 mb-stack-lg max-w-2xl"}>{"Deploying post-quantum cryptographic standards to safeguard critical energy infrastructure from next-generation threats."}</p><div className={"flex gap-stack-md"}><Link href={"/industrial-iot-solutions"} className={"px-8 py-4 bg-primary text-on-primary font-label-sm text-label-sm flex items-center gap-2 group hover:bg-secondary transition-all"}>{"\n                            EXPLORE SOLUTION "}<span className={"material-symbols-outlined group-hover:translate-x-1 transition-transform"}>{"arrow_forward"}</span></Link><div className={"flex flex-col"}><span className={"font-label-sm text-label-sm text-on-primary-container/60"}>{"SECTOR"}</span><span className={"font-body-md text-on-primary-fixed font-bold"}>{"Energy & Infrastructure"}</span></div></div></div></div></section>
    </>
  );
}
