import { StitchImage } from "@/components/ui/StitchImage";

export function Section() {
  return (
    <>
      <section className={"bg-primary-container py-24 mt-stack-lg relative overflow-hidden"}><div className={"absolute inset-0 opacity-10"}></div><div className={"px-margin-desktop max-w-container-max mx-auto relative z-10 grid md:grid-cols-2 gap-20 items-center"}><div className={"text-white"}><h2 className={"font-display-lg text-headline-lg md:text-[56px] leading-none mb-stack-md"}>{"Specialized Engineering Services"}</h2><p className={"font-body-lg text-body-lg text-white/70 mb-stack-lg"}>{"We provide cross-disciplinary expertise across mechanical, electrical, and systems engineering, specifically tailored for industrial environments."}</p><div className={"space-y-6"}><div className={"flex gap-stack-md border-b border-white/10 pb-6"}><span className={"font-display-lg text-4xl text-white/20"}>{"01"}</span><div><h4 className={"font-headline-md text-headline-md mb-1"}>{"Systems Architecture"}</h4><p className={"text-white/60 font-body-md text-body-md"}>{"High-level design of interconnected industrial ecosystems."}</p></div></div><div className={"flex gap-stack-md border-b border-white/10 pb-6"}><span className={"font-display-lg text-4xl text-white/20"}>{"02"}</span><div><h4 className={"font-headline-md text-headline-md mb-1"}>{"Structural Integrity"}</h4><p className={"text-white/60 font-body-md text-body-md"}>{"FEA analysis and vibration studies for extreme environments."}</p></div></div><div className={"flex gap-stack-md"}><span className={"font-display-lg text-4xl text-white/20"}>{"03"}</span><div><h4 className={"font-headline-md text-headline-md mb-1"}>{"Thermal Management"}</h4><p className={"text-white/60 font-body-md text-body-md"}>{"Specialized cooling solutions for high-density power electronics."}</p></div></div></div></div><div className={"relative group"}><div className={"absolute -inset-4 bg-white/5 rounded-2xl blur-xl group-hover:bg-white/10 transition-all"}></div><div className={"relative rounded-xl overflow-hidden border border-white/10 aspect-[4/5] bg-black"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDUPD_flSltvLgXgEmK_TMqI_CoDxDq4OO3F0cKlm9FnaB6jlHkNabDsegr7LkUt3iRv5RQkHvVEz9sldT4-AYWllJGxcjUqE0gBpydDVtFYa2Kpdivs1QqC9Wb9CJEBEKRgJF4JQR0OdO22FBEIiTkddtLYs4PmB-IhiH4A3rN13ZvtjRV2iay8p0DrG4ED4KdO73O4bHQ4ZUvnbuUZl04MEeh616nQ4bHYZBZx7qjrkoFqc7ODdeVq49GFU2c6sCFqL1QWVt1bFI"} alt={"A blueprint-style 3D wireframe render of a complex industrial engine, glowing in thin neon blue lines against a dark navy background. Professional CAD visualization, technical, sharp detail."} className={"w-full h-full object-cover opacity-60"} /><div className={"absolute bottom-8 left-8 right-8 bg-white/10 backdrop-blur-md p-6 rounded-lg border border-white/10"}><p className={"text-label-sm font-label-sm text-white/50 mb-1"}>{"PROJECT 842-X"}</p><p className={"text-white font-body-md font-semibold"}>{"\"Efficiency increased by 14% via custom thermal modeling.\""}</p></div></div></div></div></section>
    </>
  );
}
