import Link from "next/link";

export function Section() {
  return (
    <>
      <section className={"py-stack-lg max-w-container-max mx-auto px-margin-desktop grid grid-cols-12 gap-gutter border-t border-outline-variant/20"}><div className={"col-span-12 lg:col-span-4"}><h3 className={"font-headline-md text-headline-md mb-stack-sm"}>{"Technical Stack"}</h3><div className={"flex flex-wrap gap-3"}><span className={"px-4 py-2 bg-surface-container rounded-full font-label-sm text-label-sm border border-outline-variant/30 flex items-center gap-2"}><span className={"w-2 h-2 bg-primary rounded-full"}></span>{" NXP i.MX RT\n                    "}</span><span className={"px-4 py-2 bg-surface-container rounded-full font-label-sm text-label-sm border border-outline-variant/30 flex items-center gap-2"}><span className={"w-2 h-2 bg-primary rounded-full"}></span>{" Yocto Linux\n                    "}</span><span className={"px-4 py-2 bg-surface-container rounded-full font-label-sm text-label-sm border border-outline-variant/30 flex items-center gap-2"}><span className={"w-2 h-2 bg-primary rounded-full"}></span>{" SiC Technology\n                    "}</span><span className={"px-4 py-2 bg-surface-container rounded-full font-label-sm text-label-sm border border-outline-variant/30 flex items-center gap-2"}><span className={"w-2 h-2 bg-primary rounded-full"}></span>{" MQTT / TLS 1.3\n                    "}</span></div></div><div className={"col-span-12 lg:col-span-8 bg-surface-container-low p-8 rounded-xl border border-outline-variant/20"}><div className={"grid grid-cols-1 md:grid-cols-2 gap-8"}><div><h4 className={"font-label-sm text-label-sm font-bold uppercase text-on-surface-variant mb-4"}>{"Customer Benefits"}</h4><ul className={"space-y-4"}><li className={"flex gap-3"}><span className={"material-symbols-outlined text-blue-600"}>{"check_circle"}</span><span className={"font-body-md text-body-md"}>{"Seamless transition to zero-emission transit."}</span></li><li className={"flex gap-3"}><span className={"material-symbols-outlined text-blue-600"}>{"check_circle"}</span><span className={"font-body-md text-body-md"}>{"Optimized schedules via smart telemetry."}</span></li></ul></div><div><h4 className={"font-label-sm text-label-sm font-bold uppercase text-on-surface-variant mb-4"}>{"Related Projects"}</h4><div className={"space-y-3"}><Link href={"/ev-infrastructure"} className={"block p-3 bg-white rounded border border-outline-variant/20 hover:border-blue-500 transition-colors"}><p className={"font-label-sm text-label-sm font-semibold"}>{"EV Infrastructure Phase II"}</p><p className={"text-[10px] text-on-surface-variant"}>{"Residential V2G Solutions"}</p></Link><Link href={"/smart-infrastructure"} className={"block p-3 bg-white rounded border border-outline-variant/20 hover:border-blue-500 transition-colors"}><p className={"font-label-sm text-label-sm font-semibold"}>{"Smart Cities Core"}</p><p className={"text-[10px] text-on-surface-variant"}>{"Grid Management Systems"}</p></Link></div></div></div></div></section>
    </>
  );
}
