import { StitchImage } from "@/components/ui/StitchImage";

export function GlassOverlayInfoSection() {
  return (
    <>
      <section className={"bg-primary-container text-white py-24 overflow-hidden"}><div className={"px-margin-desktop max-w-container-max mx-auto grid grid-cols-12 gap-gutter items-center"}><div className={"col-span-12 md:col-span-6"}><span className={"font-label-sm text-label-sm text-on-primary-container mb-4 block tracking-[0.2em]"}>{"ENGINEERING PRECISION"}</span><h2 className={"font-display-lg text-headline-lg mb-8 leading-tight"}>{"Mastering the Mixed-Signal Frontier"}</h2><p className={"font-body-lg text-body-lg text-on-primary-container mb-8"}>{"\n                        Our engineering workflow prioritizes safety-critical code and seamless mixed-signal integration. We ensure that digital logic and analog precision coexist in the most demanding electromagnetic environments.\n                    "}</p><div className={"grid grid-cols-2 gap-8"}><div><div className={"text-3xl font-display-lg text-white mb-2"}>{"99.9%"}</div><p className={"font-label-sm text-label-sm text-on-primary-container"}>{"UPTIME IN INDUSTRIAL DEPLOYMENT"}</p></div><div><div className={"text-3xl font-display-lg text-white mb-2"}>{"ISO 26262"}</div><p className={"font-label-sm text-label-sm text-on-primary-container"}>{"SAFETY COMPLIANCE READY"}</p></div></div></div><div className={"col-span-12 md:col-span-6 relative h-[400px]"}><div className={"absolute inset-0 rounded-2xl overflow-hidden border border-outline/20"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuBKxl8KsAP7RrjytFvqEEK_6qwZPD1Zb_SR4bz2tq0E3VqvelP-HlQvh-wiaAnghoFtSyBG1Y3Nza9JDx722x9sMjTdtrJpOP-xsVwyclwvR_5qPfOz8eOFa9O1vP9vS0K1JFK8Dh4J0WMILFMew8EDzSdBVvM6_mHiSL2kGUjy07n78QITjHbqfAA755jbWBBogwsdaPtRL4hS8YaFeH4-fddR4HsfMx-YzD_kkAbkZeTUnFsMYDeyx4IPnLQswx1_zzu--E3SP_g"} alt={"A macro photograph of a high-tech printed circuit board featuring a Microchip SAM processor. The lighting is cold and clinical, focusing on the intricate gold-plated pathways and the matte black finish of the silicon package. The style is technical and architectural, emphasizing industrial reliability and advanced electronics engineering."} className={"w-full h-full object-cover"} /></div><div className={"absolute -bottom-6 -left-6 glass-panel p-6 rounded-xl max-w-xs"}><p className={"font-label-sm text-label-sm text-white mb-2"}>{"Real-time Oscilloscope Feed"}</p><div className={"h-12 w-full bg-primary flex items-end gap-1 px-2 py-1"}><div className={"w-1 bg-on-primary-container h-4 animate-pulse"}></div><div className={"w-1 bg-on-primary-container h-8 animate-pulse delay-75"}></div><div className={"w-1 bg-on-primary-container h-6 animate-pulse delay-150"}></div><div className={"w-1 bg-on-primary-container h-10 animate-pulse"}></div><div className={"w-1 bg-on-primary-container h-5 animate-pulse delay-75"}></div></div></div></div></div></section>
    </>
  );
}
