import Link from "next/link";

export function TechnicalFloatingStatsSection() {
  return (
    <>
      <section className={"relative min-h-[819px] flex items-center overflow-hidden py-24 px-margin-desktop max-w-container-max mx-auto"}><div className={"grid grid-cols-12 gap-gutter w-full relative z-10"}><div className={"col-span-12 lg:col-span-7 flex flex-col justify-center"}><span className={"font-label-sm text-label-sm uppercase tracking-widest text-secondary mb-4 flex items-center gap-2"}><span className={"w-8 h-[1px] bg-secondary"}></span>{" \n                        Precision Engineering\n                    "}</span><h1 className={"font-display-lg text-display-lg text-primary mb-6 leading-none"}>{"\n                        i.MX Application "}<br />{" Processors\n                    "}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-xl mb-10"}>{"\n                        Powering the next generation of edge intelligence with industrial-grade reliability. Mind Matrix delivers advanced MCU solutions for automotive safety and smart-city infrastructure.\n                    "}</p><div className={"flex gap-4"}><button className={"bg-primary text-on-primary px-8 py-4 rounded-lg font-label-sm text-label-sm font-bold flex items-center gap-2 group transition-all"}>{"\n                            EXPLORE THE ARCHITECTURE\n                            "}<span className={"material-symbols-outlined text-sm group-hover:translate-x-1 transition-transform"}>{"arrow_forward"}</span></button><Link href={"/technical-downloads-and-sdks"} className={"border border-outline px-8 py-4 rounded-lg font-label-sm text-label-sm font-bold hover:bg-surface-container-low transition-colors"}>{"\n                            DOWNLOAD WHITE PAPER\n                        "}</Link></div></div><div className={"col-span-12 lg:col-span-5 relative mt-12 lg:mt-0"}><div className={"relative w-full aspect-square bg-surface-container rounded-3xl overflow-hidden glass-card"}><div className={"absolute inset-0 flex items-center justify-center"}><div className={"p-8 bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 text-center"}><span className={"material-symbols-outlined text-6xl text-primary mb-4"} style={{"fontVariationSettings":"'FILL' 1"}}>{"memory"}</span><div className={"font-headline-md text-headline-md text-primary"}>{"i.MX 9 Series"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant mt-2"}>{"NPU-ENABLED EDGE AI"}</div></div></div></div><div className={"absolute -bottom-6 -left-6 p-6 glass-card rounded-xl border border-outline-variant shadow-lg z-20"}><div className={"text-3xl font-bold text-primary"}>{"5.2 TOPS"}</div><div className={"text-xs font-label-sm text-secondary"}>{"Neural Processing Unit"}</div></div><div className={"absolute -top-6 -right-6 p-6 glass-card rounded-xl border border-outline-variant shadow-lg z-20"}><div className={"text-3xl font-bold text-primary"}>{"ISO 26262"}</div><div className={"text-xs font-label-sm text-secondary"}>{"Functional Safety Certified"}</div></div></div></div></section>
    </>
  );
}
