import Link from "next/link";
import { StitchImage } from "@/components/ui/StitchImage";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[819px] flex items-center overflow-hidden grid-pattern"}><div className={"px-margin-desktop max-w-container-max mx-auto w-full grid grid-cols-12 gap-gutter items-center"}><div className={"col-span-12 lg:col-span-6 z-10"}><div className={"inline-flex items-center gap-2 px-3 py-1 bg-primary/5 border border-primary/10 rounded-full mb-6"}><span className={"w-2 h-2 rounded-full bg-primary animate-pulse"}></span><span className={"font-label-sm text-label-sm uppercase tracking-widest text-primary"}>{"High-Power Electronics"}</span></div><h1 className={"font-display-lg text-display-lg mb-6 leading-none"}>{"EV Charger "}<br /><span className={"text-primary/40 italic"}>{"Engineering"}</span></h1><p className={"font-body-lg text-body-lg text-on-surface-variant mb-10 max-w-lg"}>{"\n                        Next-generation SiC-powered charger modules delivering ultra-fast DC charging with 98% peak efficiency. Engineering the future of high-stakes mobility infrastructure.\n                    "}</p><div className={"flex gap-4"}><Link href={"/ev-charger-electronics"} className={"bg-primary text-on-primary px-8 py-4 rounded font-label-sm text-label-sm uppercase tracking-widest hover:bg-on-primary-fixed-variant transition-colors"}>{"Download Specs"}</Link><Link href={"/ev-charger-electronics"} className={"border border-outline px-8 py-4 rounded font-label-sm text-label-sm uppercase tracking-widest hover:bg-surface-variant transition-colors"}>{"Technical Demo"}</Link></div></div><div className={"col-span-12 lg:col-span-6 relative h-[500px]"}><div className={"absolute inset-0 z-0"}></div><div className={"relative z-10 glass-card p-4 rounded-xl shadow-2xl mt-12 transform hover:-rotate-1 transition-transform duration-500"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDVEpQqAeTqCOnP1s4_UsbBK4ca8FufhMiwEX9ShUQCYJYhBPGUqTwObpJqFxU48XNvLpvuL5wSoTnziB0cZW1FpNc9q3Mw5CTqPJa-ssYlPIYsZ9OlUoUyG8CBe2Do1l7fm9vuOTVz-o6xDXZtQm1OmAeWLWHTMklmEidk792jBb_nU_MVvVoQUhJaJ-t8hyKPYOlqxSPpSu6Xyy66EklGbaXtgovr5yLbP99ayvelfHrWk94fCVrxZMjC_DEGdMVbOJ1xBy41qc4"} alt={"A highly detailed industrial product shot of a high-power Silicon Carbide SiC EV charger power module. The device features visible cooling fins, gold-plated busbars, and precision-engineered circuit boards in a light-mode industrial aesthetic. The lighting is crisp and surgical, highlighting the technical craftsmanship and absolute reliability of the hardware against a clean white background."} className={"w-full h-[400px] object-cover rounded shadow-inner"} /><div className={"absolute -bottom-6 -right-6 glass-card p-6 rounded-lg border border-primary/20 shadow-xl"}><div className={"text-display-lg font-display-lg text-primary leading-none"}>{"98.4%"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant uppercase tracking-tighter"}>{"Conversion Efficiency"}</div></div></div></div></div></section>
    </>
  );
}
