import Link from "next/link";

export function Block4Section() {
  return (
    <>
      <section className={"py-stack-lg bg-primary text-on-primary overflow-hidden relative"}><div className={"absolute inset-0 opacity-10"}><div className={"absolute top-0 left-0 w-full h-full grid-bg"}></div></div><div className={"max-w-container-max mx-auto px-margin-desktop relative z-10 flex flex-col md:flex-row justify-between items-center gap-12"}><div className={"max-w-2xl"}><h2 className={"font-headline-lg text-headline-lg mb-6"}>{"Future-Proof Your Legacy Infrastructure"}</h2><div className={"grid grid-cols-1 sm:grid-cols-2 gap-6 mb-8"}><div className={"flex gap-3"}><span className={"material-symbols-outlined text-secondary-fixed"}>{"shield_lock"}</span><span className={"font-body-md text-body-md"}>{"Enterprise-grade security standards"}</span></div><div className={"flex gap-3"}><span className={"material-symbols-outlined text-secondary-fixed"}>{"dynamic_feed"}</span><span className={"font-body-md text-body-md"}>{"Unlimited scalability per site"}</span></div><div className={"flex gap-3"}><span className={"material-symbols-outlined text-secondary-fixed"}>{"published_with_changes"}</span><span className={"font-body-md text-body-md"}>{"Zero-touch provisioning"}</span></div><div className={"flex gap-3"}><span className={"material-symbols-outlined text-secondary-fixed"}>{"headset_mic"}</span><span className={"font-body-md text-body-md"}>{"24/7 technical support access"}</span></div></div></div><div className={"bg-surface p-1 rounded-sm w-full md:w-auto shadow-2xl"}><div className={"bg-surface-container-lowest p-10 border border-outline-variant/30 flex flex-col gap-6 text-on-surface"}><h4 className={"font-headline-md text-headline-md text-center"}>{"Inquire for Pilot Program"}</h4><div className={"space-y-4"}><input className={"w-full px-4 py-3 bg-surface-container border-none focus:ring-2 ring-primary/20 text-body-md"} placeholder={"Work Email"} type={"email"} /><Link href={"/request-consultation"} className={"w-full py-4 bg-primary text-on-primary font-label-sm text-label-sm uppercase tracking-widest hover:opacity-90 transition-all"}>{"\n                                GET STARTED\n                            "}</Link></div><p className={"text-[11px] text-center text-on-surface-variant font-label-sm"}>{"Standard response time within 4 business hours."}</p></div></div></div></section>
    </>
  );
}
