import Link from "next/link";

export function Feature1Section() {
  return (
    <>
      <section className={"py-stack-lg bg-surface-container-lowest"}><div className={"max-w-container-max mx-auto px-margin-desktop"}><div className={"flex flex-col md:flex-row justify-between items-end mb-16 gap-4"}><div><h2 className={"font-headline-lg text-headline-lg mb-4"}>{"Core Capabilities"}</h2><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-xl"}>{"Advanced features designed for the rigorous demands of 24/7 technical infrastructure."}</p></div><Link href={"/technical-downloads-and-sdks"} className={"text-primary font-label-sm text-label-sm flex items-center gap-1 border-b border-primary py-1"}>{"VIEW ALL SPECIFICATIONS"}</Link></div><div className={"grid grid-cols-1 md:grid-cols-4 gap-gutter"}><div className={"space-y-4"}><div className={"w-12 h-12 flex items-center justify-center bg-surface-container-high rounded"}><span className={"material-symbols-outlined text-primary"}>{"bolt"}</span></div><h5 className={"font-headline-md text-headline-md text-[18px]"}>{"Real-time Alerting"}</h5><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Instant transformation of traps into push notifications, SMS, or webhook triggers."}</p></div><div className={"space-y-4"}><div className={"w-12 h-12 flex items-center justify-center bg-surface-container-high rounded"}><span className={"material-symbols-outlined text-primary"}>{"history"}</span></div><h5 className={"font-headline-md text-headline-md text-[18px]"}>{"Legacy Integration"}</h5><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Retrofit 20-year-old hardware with modern, standardized cloud connectivity."}</p></div><div className={"space-y-4"}><div className={"w-12 h-12 flex items-center justify-center bg-surface-container-high rounded"}><span className={"material-symbols-outlined text-primary"}>{"settings_ethernet"}</span></div><h5 className={"font-headline-md text-headline-md text-[18px]"}>{"Dual-Gigabit LAN"}</h5><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Redundant network interfaces for failover and high-availability setups."}</p></div><div className={"space-y-4"}><div className={"w-12 h-12 flex items-center justify-center bg-surface-container-high rounded"}><span className={"material-symbols-outlined text-primary"}>{"analytics"}</span></div><h5 className={"font-headline-md text-headline-md text-[18px]"}>{"Data Normalization"}</h5><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Automatic mapping of vendor-specific MIBs into uniform JSON structures."}</p></div></div></div></section>
    </>
  );
}
