import Link from "next/link";
import { StitchImage } from "@/components/ui/StitchImage";

export function Block3Section() {
  return (
    <>
      <section className={"py-stack-lg px-margin-desktop max-w-container-max mx-auto"}><div className={"bg-surface-container rounded-2xl p-stack-lg border border-outline-variant/20 flex flex-col md:flex-row gap-stack-lg overflow-hidden"}><div className={"md:w-1/2"}><span className={"font-label-sm text-label-sm text-primary font-bold tracking-widest uppercase mb-stack-sm block"}>{"Case Study"}</span><h3 className={"font-headline-lg text-headline-lg mb-stack-md"}>{"Zero-Latency Infrastructure Refactor"}</h3><p className={"text-on-surface-variant font-body-lg mb-stack-md"}>{"How Mind Matrix upgraded a regional utility provider's transmission network, reducing fault isolation time by 85% while implementing end-to-end encryption for 1.2M endpoints."}</p><ul className={"space-y-3 mb-stack-lg"}><li className={"flex items-center space-x-3"}><span className={"material-symbols-outlined text-primary"} data-icon={"check_circle"}>{"check_circle"}</span><span className={"font-body-md"}>{"Seamless legacy integration"}</span></li><li className={"flex items-center space-x-3"}><span className={"material-symbols-outlined text-primary"} data-icon={"check_circle"}>{"check_circle"}</span><span className={"font-body-md"}>{"Zero downtime deployment"}</span></li></ul><Link href={"/solutions"} className={"bg-primary text-on-primary px-6 py-3 rounded-lg font-label-sm text-label-sm"}>{"Read Detailed Report"}</Link></div><div className={"md:w-1/2 relative h-64 md:h-auto rounded-xl overflow-hidden shadow-xl border border-outline-variant/30"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDJ1JbkeU1DMrGh7aM0PW02r2Q2Ji4kN_60hq7vSRyWHVRyHVZdRCLb0rdBlSqVOZURkm7giIAZk8HHjlAZLGa5_x8XtcoDfvJPhFvoGnjkviOZOwTToiusAhCujL33KEqJk54oa0DHJEz86IeKkuNBux-4-dObRHBepEPNKRDyJqBUP4oo1cVqCcIqsU7eslpMpA97f1_GEq_96aUlTDLTfUSFmXcsKMwT3T68crysLIND_bfiyGD8kDHdZXTqvvQL017yyMDIEnk"} alt={"A series of large, floor-to-ceiling server cabinets in a professional utility operations center. The server racks are filled with neat, labeled cabling and glowing status indicators. In the background, a large digital wall map shows a city's electrical grid with real-time status pulses. The scene is immaculate, organized, and represents technical mastery over complex infrastructure."} className={"object-cover w-full h-full"} /></div></div></section>
    </>
  );
}
