import Link from "next/link";

export function DynamicDataGridOverlaySection() {
  return (
    <>
      <section className={"relative h-[870px] flex items-center overflow-hidden bg-primary-container"}><div className={"absolute inset-0 z-0 opacity-40"}><div className={"w-full h-full bg-cover bg-center"} data-alt={"A highly detailed technical visualization of a 3D power distribution network with glowing blue energy conduits crisscrossing a dark, futuristic landscape. The camera angle is low, looking up at complex transformer stations and high-voltage transmission towers illuminated by pulsing cyan data streams. The aesthetic is sharp, industrial, and clean-room minimal, utilizing a palette of deep navy and electric blue light. Cinematic atmosphere with shallow depth of field."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuC-uQrNShtP8tweq3KNzr3SIXIH0KUNijbJqcnd3C1t5BZcaPovEak8ESBAORzqIgLaRV742fBHyDk-t2mTKfDLs1X1SPeys-Nvh0EnfVW6O01wU3xXfpmX_X3bWSfzl_WKNOWbF7L5-nq5Dx3AyeFxYuFBy9ue5XMz7xLh8TGLZ4Jp6btRSh9d4uP2UtSTuw9_weho89hjUIesZ-JElcxl1KWnfWEe5k_bUhzDqH--roD4LNMt6KgpgXKKx7v4XoBIGpHTuovKSgQ')"}}></div></div><div className={"absolute inset-0 z-10 pointer-events-none opacity-20"} style={{"backgroundImage":"radial-gradient(circle, #ffffff 1px, transparent 1px)","backgroundSize":"48px 48px"}}></div><div className={"relative z-20 px-margin-desktop max-w-container-max mx-auto w-full"}><div className={"max-w-3xl"}><div className={"inline-flex items-center space-x-2 bg-secondary/20 backdrop-blur-md px-3 py-1 rounded-full mb-stack-md border border-outline-variant/30"}><span className={"w-2 h-2 rounded-full bg-primary-fixed shadow-[0_0_8px_#dce2f6]"}></span><span className={"font-label-sm text-label-sm text-on-primary tracking-widest"}>{"INDUSTRY: SMART GRID"}</span></div><h1 className={"font-display-lg text-display-lg text-on-primary mb-stack-md leading-tight"}>{"\n                        Intelligent Power Distribution "}<br />{"for the "}<span className={"text-primary-fixed"}>{"Modern Grid"}</span></h1><p className={"font-body-lg text-body-lg text-on-primary-container max-w-xl mb-stack-lg"}>{"\n                        Engineering resilient, adaptive, and high-performance energy networks through advanced industrial protocols and hardware-level cybersecurity.\n                    "}</p><div className={"flex space-x-stack-md"}><Link href={"/solutions"} className={"bg-surface-container-lowest text-primary px-8 py-4 rounded-lg font-label-sm text-label-sm font-bold flex items-center group transition-all"}>{"\n                            Optimize Your Grid\n                            "}<span className={"material-symbols-outlined ml-2 group-hover:translate-x-1 transition-transform"}>{"arrow_forward"}</span></Link><Link href={"/solutions"} className={"border border-outline-variant/40 text-on-primary px-8 py-4 rounded-lg font-label-sm text-label-sm hover:bg-white/5 transition-all"}>{"\n                            Technical Specs\n                        "}</Link></div></div></div></section>
    </>
  );
}
