import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <header className={"relative min-h-[921px] flex items-center overflow-hidden"}><div className={"absolute inset-0 z-0"}><div className={"absolute inset-0 bg-gradient-to-r from-background via-background/40 to-transparent z-10"}></div><div className={"w-full h-full bg-cover bg-center"} data-alt={"A cinematic, high-exposure wide shot of a futuristic smart factory interior. High-precision robotic arms are perfectly aligned in a sterile, clean-room environment with cool blue and white industrial lighting. Digital data streams and glowing holographic wireframes of industrial sensors overlay the machinery, projecting a sense of technical authority and engineering precision."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuDEN0rKQVyVnnzz16nXGYXE179uMMFwZ9WRrU2LFjmMgn9DFosJ8AqOgD9fkTB6ykBZI5WDPiB-7OAE2YW3ZpNocsZ5mQWSV7_n_nxZYAau5EOdtPeTftQH697zhraTflIJeXiabBgj-mCp7sPPaAnhGFKKo1lu2eRp2BcEi4FSt4i4m1Of_KZ5xmHQ42UUhgQ-roxrkJghbN_ixLYCnnN2XP_oVTzC0n9PyjvN0PLl0h4QNBDKtEDmoHsQSUc8Jj6exDZN3xwVtYc')"}}></div></div><div className={"relative z-20 px-margin-desktop max-w-container-max mx-auto w-full"}><div className={"max-w-3xl"}><div className={"flex items-center gap-3 mb-6"}><span className={"w-12 h-[1px] bg-primary"}></span><span className={"font-label-sm text-label-sm uppercase tracking-widest text-on-surface-variant"}>{"Industrial Intelligence 4.0"}</span></div><h1 className={"font-display-lg text-display-lg mb-8 leading-tight"}>{"Engineering Precision for the "}<span className={"text-primary italic"}>{"Digital Frontier."}</span></h1><p className={"font-body-lg text-body-lg text-on-surface-variant mb-10 max-w-xl"}>{"\n                    Seamlessly bridge the gap between physical assets and digital intelligence with our enterprise-grade Industrial IoT ecosystem. Architecture designed for absolute reliability.\n                "}</p><div className={"flex flex-wrap gap-4"}><Link href={"/manufacturing"} className={"bg-primary text-on-primary px-8 py-4 font-label-sm text-label-sm font-bold uppercase tracking-widest flex items-center gap-3 hover:bg-primary/90 transition-all"}>{"\n                        Deploy Solutions\n                        "}<span className={"material-symbols-outlined"}>{"arrow_forward"}</span></Link><Link href={"/manufacturing"} className={"border border-outline-variant px-8 py-4 font-label-sm text-label-sm font-bold uppercase tracking-widest hover:bg-surface-container transition-all"}>{"\n                        View Architecture\n                    "}</Link></div></div></div></header>
    </>
  );
}
