import Link from "next/link";
import { StitchImage } from "@/components/ui/StitchImage";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[921px] flex items-center px-margin-desktop overflow-hidden border-b border-outline-variant/20 bg-surface-container-lowest"}><div className={"absolute inset-0 z-0"}></div><div className={"max-w-container-max mx-auto w-full grid grid-cols-12 gap-gutter relative z-10"}><div className={"col-span-12 md:col-span-7 flex flex-col justify-center"}><div className={"flex items-center gap-2 mb-6"}><span className={"w-12 h-[1px] bg-primary"}></span><span className={"font-label-sm text-label-sm uppercase tracking-[0.2em] text-on-primary-container"}>{"Strategic Integration"}</span></div><h1 className={"font-display-lg text-display-lg text-primary mb-8 leading-[1.05]"}>{"Texas Instruments: The Backbone of Global Electronics."}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-xl mb-10"}>{"\n                        Pioneering the future of analog and embedded processing. From power management to precision sensing, we provide the technical authority required for high-stakes industrial systems.\n                    "}</p><div className={"flex gap-stack-md"}><Link href={"/texas-instruments"} className={"bg-primary text-on-primary px-8 py-4 rounded-none font-label-sm text-label-sm uppercase tracking-widest hover:bg-secondary transition-all flex items-center gap-2"}>{"\n                            Explore Portfolio "}<span className={"material-symbols-outlined text-sm"} data-icon={"arrow_forward"}>{"arrow_forward"}</span></Link><Link href={"/texas-instruments"} className={"border border-outline px-8 py-4 rounded-none font-label-sm text-label-sm uppercase tracking-widest hover:bg-surface-container transition-all"}>{"\n                            Technical Specs\n                        "}</Link></div></div><div className={"col-span-12 md:col-span-5 flex justify-center items-center relative py-12"}><div className={"relative w-full aspect-square float-anim"}><div className={"absolute inset-0 glass-panel rounded-full opacity-20 border-primary/20"}></div><div className={"absolute inset-8 glass-panel rounded-full flex items-center justify-center border-primary/10"}><div className={"w-full h-full p-12"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuAUSSZsF9FOnKiIjZS4kw9Bthi-EF96GUBnewRRuBmL7tPuCvhoahg_Awd9GLWISwlkP9QwLVSDon-webf7kSEFP9Hm2aNifeqUnoavaBblNWjtr3BerORIIpD8nkbhRDmBaokFbwW4WIlYC8NV3n1qIlkcSaKl2qIo9VzN3wfoyL-JULmitMS2P5hQTOQ7c5Tm--kJ_4VvBpBuaJYkBPUzQeDU8bxkmeWGd6wIWuS2yoBuuMDlKrexopUc7EhL4zt3Zjz0XDkOb8w"} alt={"A highly detailed, macro-photographic view of a sophisticated Texas Instruments semiconductor wafer with intricate circuit patterns reflecting metallic blues and silvers. The lighting is crisp and industrial, emphasizing technical precision and cleanliness in a high-tech manufacturing environment. Soft blue ambient light glows from the background."} className={"w-full h-full object-contain filter grayscale brightness-110"} /></div></div></div></div></div></section>
    </>
  );
}
