import { StitchImage } from "@/components/ui/StitchImage";

export function Section() {
  return (
    <>
      <section className={"bg-primary-container py-24 overflow-hidden relative"}><div className={"absolute inset-0 opacity-10"}></div><div className={"max-w-container-max mx-auto px-margin-desktop grid grid-cols-12 gap-gutter relative z-10"}><div className={"col-span-12 md:col-span-5 text-on-primary"}><span className={"font-label-sm text-label-sm text-on-primary-container uppercase tracking-widest mb-4 block"}>{"System Architecture"}</span><h2 className={"font-display-lg text-headline-lg mb-8"}>{"Integrated Ecosystem for Signal Integrity."}</h2><ul className={"space-y-6"}><li className={"flex items-start gap-4"}><span className={"material-symbols-outlined text-on-primary-container mt-1"} data-icon={"check_circle"}>{"check_circle"}</span><p className={"font-body-md text-body-md text-on-primary-container"}>{"Optimized thermal dissipation for high-current applications."}</p></li><li className={"flex items-start gap-4"}><span className={"material-symbols-outlined text-on-primary-container mt-1"} data-icon={"check_circle"}>{"check_circle"}</span><p className={"font-body-md text-body-md text-on-primary-container"}>{"Low-latency data pathways for real-time response loops."}</p></li><li className={"flex items-start gap-4"}><span className={"material-symbols-outlined text-on-primary-container mt-1"} data-icon={"check_circle"}>{"check_circle"}</span><p className={"font-body-md text-body-md text-on-primary-container"}>{"Universal footprints for simplified PCB migration."}</p></li></ul></div><div className={"col-span-12 md:col-span-7 mt-12 md:mt-0"}><div className={"glass-panel border-white/10 p-4 aspect-video flex items-center justify-center overflow-hidden"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDXkuEaw6sEi_pxYkiqu5rJi5y79k7VZMex-cD8OYAqdzwB5hqFC1V46OfrJ5gLlfqCdwoUWGBZG4unZdVpmwswkoBNs4l3o-tNcRlTHguU2X-ETuCo2lZHqNua_01mzMW041JdtEyi-J1BSiC8tKrjQE2m6DhLmx0RWlvHSmdp6o40ZlNqLXmrC99Xkl5aL5hRelv2ccblJz-waLSEs_dBjoI-CiBr9tK3mRST5NaxL9fkTDeV8CNqP4OtFcoOQb92-T4FfqhlpV8"} alt={"A complex technical schematic diagram of a system-on-chip architecture, presented in a glowing neon-blue and silver aesthetic. The diagram shows clean interconnected blocks labeled with technical terms like ADC, MCU, and POWER. The background is a deep navy industrial grid, conveying a sense of advanced engineering and digital complexity."} className={"w-full h-full object-cover"} /></div></div></div></section>
    </>
  );
}
