import Link from "next/link";

export function AnimatedShaderOverlayForFlowSection() {
  return (
    <>
      <section className={"relative h-[819px] flex items-center overflow-hidden"}><div className={"absolute inset-0 z-0"}><div className={"w-full h-full bg-cover bg-center"} data-alt={"A cinematic aerial wide shot of a massive industrial pipeline cutting through a vast, rugged mountain landscape at dawn. The lighting is cold and atmospheric with blue and silver tones, highlighting the metallic texture of the pipeline. The scene conveys industrial scale and precision engineering, with soft morning mist clinging to the valley floors and a high-key technical aesthetic."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuDK5z1RiSrfIAbuoBsnpZoX1R2DcgTa6FN32oQEFU1oIK7aA-NuB9pldeABsnSLNZB3jy1mo21pSVMavrv4MmgLNFGQNfjaTxIOkEHQtLVY0oG_pBeq9oTht9dF-TuFKAj2K3T8cee2Th8X_H24jAB6v03Q1qHHl4Pc2IrUbL8Tj_NvtVYRcV1UVAHk0bClkUWmwbJpXnnDm8gENl17kk43BDFVf610c85agnIWi-c9l5MQklpkbWvSLVUh1FkxHpNhAjC9yxuNW00')"}}></div><div className={"absolute inset-0 bg-primary/20 backdrop-brightness-75"}></div><div className={"absolute inset-0 pipeline-gradient"}></div></div><div className={"relative z-10 w-full px-margin-desktop max-w-container-max mx-auto"}><div className={"max-w-3xl"}><div className={"inline-flex items-center gap-2 px-3 py-1 bg-primary text-on-primary rounded mb-stack-md"}><span className={"material-symbols-outlined text-[16px]"}>{"sensors"}</span><span className={"font-label-sm text-label-sm uppercase tracking-widest"}>{"Industrial Precision"}</span></div><h1 className={"font-display-lg text-display-lg text-primary mb-stack-md"}>{"\n                        Intelligent Leak Detection and Flow Analysis\n                    "}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-2xl mb-stack-lg"}>{"\n                        Securing critical energy infrastructure through high-fidelity acoustic monitoring and real-time pressure-wave telemetry.\n                    "}</p><div className={"flex flex-wrap gap-stack-md"}><Link href={"/wireless-sensor-network"} className={"bg-primary text-on-primary px-8 py-4 rounded-lg font-label-sm text-label-sm font-bold flex items-center gap-2 hover:bg-[#2563EB] transition-all"}>{"\n                            Monitor Your Infrastructure\n                            "}<span className={"material-symbols-outlined"}>{"arrow_forward"}</span></Link></div></div></div></section>
    </>
  );
}
