import Link from "next/link";

export function Block3Section() {
  return (
    <>
      <section className={"bg-primary text-on-primary py-stack-lg"}><div className={"px-margin-desktop max-w-container-max mx-auto"}><div className={"grid grid-cols-1 md:grid-cols-2 gap-stack-lg"}><div><span className={"font-label-sm text-label-sm text-on-primary-container uppercase tracking-widest block mb-4"}>{"Case Study"}</span><h2 className={"font-display-lg text-headline-lg text-on-primary mb-stack-md"}>{"Global Asset Tracking"}</h2><p className={"font-body-lg text-body-lg text-on-primary-container mb-stack-lg"}>{"\n                            We implemented an end-to-end monitoring solution for a 2,500km natural gas corridor, reducing leak detection latency from hours to seconds and preventing millions in potential environmental damage.\n                        "}</p><Link href={"/wireless-sensor-network"} className={"inline-flex items-center gap-2 font-label-sm text-label-sm text-on-primary font-bold border-b border-on-primary pb-1 hover:gap-4 transition-all"}>{"\n                            View Full Technical Case Study\n                            "}<span className={"material-symbols-outlined text-sm"}>{"open_in_new"}</span></Link></div><div className={"grid grid-cols-2 gap-gutter"}><div className={"p-6 border border-on-primary-container/20 rounded-xl"}><span className={"material-symbols-outlined text-on-primary mb-4"}>{"settings_input_antenna"}</span><h4 className={"font-headline-md text-body-lg font-bold mb-2"}>{"Wireless sensor networks"}</h4><p className={"font-body-md text-on-primary-container text-sm"}>{"Mesh architectures designed for redundancy in zero-signal zones."}</p></div><div className={"p-6 border border-on-primary-container/20 rounded-xl"}><span className={"material-symbols-outlined text-on-primary mb-4"}>{"precision_manufacturing"}</span><h4 className={"font-headline-md text-body-lg font-bold mb-2"}>{"High-precision measurement"}</h4><p className={"font-body-md text-on-primary-container text-sm"}>{"Grade-A industrial sensors with calibrated sub-micron sensitivity."}</p></div></div></div></div></section>
    </>
  );
}
