import Link from "next/link";

export function Block2Section() {
  return (
    <>
      <section className={"py-stack-lg relative"}><div className={"max-w-4xl mx-auto px-margin-mobile text-center relative z-10"}><h2 className={"font-display-lg text-headline-lg lg:text-display-lg text-primary mb-stack-md"}>{"Engineered for Extremes"}</h2><p className={"text-on-surface-variant font-body-lg text-body-lg mb-stack-lg"}>{"\n                Our microcontrollers aren't just components; they are the reliable heart of your most critical missions. \n                With extended temperature ranges and 20-year longevity programs.\n            "}</p><div className={"grid grid-cols-2 md:grid-cols-4 gap-gutter mb-stack-lg"}><div className={"p-6 bg-surface border border-outline-variant rounded-xl"}><div className={"font-display-lg text-[32px] text-primary"}>{"125°C"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant"}>{"Max Temp Range"}</div></div><div className={"p-6 bg-surface border border-outline-variant rounded-xl"}><div className={"font-display-lg text-[32px] text-primary"}>{"20yr+"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant"}>{"Longevity Program"}</div></div><div className={"p-6 bg-surface border border-outline-variant rounded-xl"}><div className={"font-display-lg text-[32px] text-primary"}>{"SIL3"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant"}>{"Safety Ready"}</div></div><div className={"p-6 bg-surface border border-outline-variant rounded-xl"}><div className={"font-display-lg text-[32px] text-primary"}>{"48h"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant"}>{"Support Response"}</div></div></div><Link href={"/industrial-automation"} className={"bg-primary text-on-primary px-12 py-5 rounded-full font-headline-md text-headline-md hover:scale-105 transition-transform"}>{"\n                Consult with an Expert\n            "}</Link></div></section>
    </>
  );
}
