import Link from "next/link";

export function DecorativeTechnicalLinesSection() {
  return (
    <>
      <header className={"relative overflow-hidden pt-24 pb-32"}><div className={"max-w-container-max mx-auto px-margin-desktop grid grid-cols-12 gap-gutter relative z-10"}><div className={"col-span-12 lg:col-span-7 flex flex-col justify-center"}><div className={"inline-flex items-center gap-2 px-3 py-1 bg-primary-fixed text-on-primary-fixed rounded-full w-fit mb-stack-sm"}><span className={"material-symbols-outlined text-[14px]"}>{"precision_manufacturing"}</span><span className={"font-label-sm text-label-sm uppercase tracking-widest"}>{"Industrial Precision"}</span></div><h1 className={"font-display-lg text-display-lg text-primary mb-stack-md leading-tight"}>{"\n                    Reliability Engineered. "}<br />{"Future Secured.\n                "}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-xl mb-stack-lg"}>{"\n                    Harnessing the technical authority of Renesas RX, RA, and RL78 architectures to deliver high-stakes industrial control systems with absolute functional safety.\n                "}</p><div className={"flex gap-4"}><Link href={"/industrial-automation"} className={"bg-primary text-on-primary px-8 py-4 rounded-full font-label-sm text-label-sm flex items-center gap-2 group hover:gap-4 transition-all"}>{"\n                        Technical Specs "}<span className={"material-symbols-outlined"}>{"arrow_forward"}</span></Link><Link href={"/industrial-automation"} className={"border border-outline-variant px-8 py-4 rounded-full font-label-sm text-label-sm hover:bg-surface-container transition-all"}>{"\n                        Ecosystem Overview\n                    "}</Link></div></div><div className={"col-span-12 lg:col-span-5 relative hidden lg:block"}><div className={"aspect-square glass rounded-3xl p-8 flex items-center justify-center relative overflow-hidden group"}><div className={"absolute inset-0 bg-gradient-to-br from-primary-fixed/20 to-transparent"}></div><div className={"relative z-10 w-full h-full border border-outline-variant/30 rounded-2xl bg-surface/50 backdrop-blur-md flex flex-col items-center justify-center text-center p-8"}><span className={"material-symbols-outlined text-[64px] text-primary mb-4"} style={{"fontVariationSettings":"'FILL' 1"}}>{"developer_board"}</span><div className={"font-headline-md text-headline-md text-primary mb-2"}>{"RX72M Complex Control"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant"}>{"The Pinnacle of 32-bit Performance"}</div></div><div className={"absolute top-0 right-0 w-32 h-32 border-t-2 border-r-2 border-primary/20 -translate-y-4 translate-x-4"}></div><div className={"absolute bottom-0 left-0 w-32 h-32 border-b-2 border-l-2 border-primary/20 translate-y-4 -translate-x-4"}></div></div></div></div></header>
    </>
  );
}
