import { StitchImage } from "@/components/ui/StitchImage";

export function Block2Section() {
  return (
    <>
      <section className={"py-stack-lg px-margin-desktop max-w-container-max mx-auto grid grid-cols-12 gap-gutter items-center"}><div className={"col-span-12 lg:col-span-5 mb-12 lg:mb-0"}><h2 className={"font-headline-lg text-headline-lg mb-stack-md"}>{"Technology & Hardware Ecosystem"}</h2><div className={"space-y-stack-md"}><div className={"flex gap-gutter"}><div className={"flex-shrink-0 w-12 h-12 bg-primary flex items-center justify-center"}><span className={"material-symbols-outlined text-white"}>{"terminal"}</span></div><div><h6 className={"font-headline-md text-headline-md mb-2"}>{"Analysis Stacks"}</h6><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Utilization of Wireshark, Protocol Analyzers, and custom-built sniffing tools for deep packet inspection."}</p></div></div><div className={"flex gap-gutter"}><div className={"flex-shrink-0 w-12 h-12 bg-primary flex items-center justify-center"}><span className={"material-symbols-outlined text-white"}>{"memory"}</span></div><div><h6 className={"font-headline-md text-headline-md mb-2"}>{"Edge Gateways"}</h6><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Ruggedized Linux-based gateways and specialized PLC communication modules for protocol translation."}</p></div></div><div className={"flex gap-gutter"}><div className={"flex-shrink-0 w-12 h-12 bg-primary flex items-center justify-center"}><span className={"material-symbols-outlined text-white"}>{"developer_board"}</span></div><div><h6 className={"font-headline-md text-headline-md mb-2"}>{"Field Devices"}</h6><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Native integration for sensors, actuators, and remote I/O nodes across all physical layers."}</p></div></div></div></div><div className={"col-span-12 lg:col-span-7"}><div className={"relative aspect-video glass overflow-hidden flex items-center justify-center"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuBDspOp3xI8lDSiiT7oLrhxth1TFfHH6VGU1MYQRJO7z6e2AUA1QNjT9Qgqp63ywcQ2yYpEGfr3ddBcLhYOI1iNESGYZyBByALgo_x_MzMVZlXW7M0I_X4KL9NCFwV3lyPHlz_Y3DbNMHpWg5gWK6VTWRYoVALPDtkvy17lu4Nlv88r6dS_FHOFjxgcEvhCgKh_wkVC8Zs5XrRFninMWdrV_0OAmIKZobpc5z7g6c0axLfGfFg1wxA8SVD4VfVpR1JtEu85UcMrgWk"} alt={"A high-tech industrial laboratory featuring a clean, minimalist workbench with high-end oscilloscopes, logic analyzers, and glowing ethernet switches. The lighting is cool-toned and professional, showcasing a sophisticated technical environment for protocol validation. Cables are organized with industrial precision, reflecting a modern light-mode aesthetic with primary black and blue accents."} className={"w-full h-full object-cover"} /><div className={"absolute inset-0 bg-primary-container/20"}></div></div></div></section>
    </>
  );
}
