import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[921px] flex items-center overflow-hidden bg-primary-container"}><div className={"relative z-10 w-full px-margin-desktop max-w-container-max mx-auto grid grid-cols-12 gap-gutter py-24"}><div className={"col-span-12 lg:col-span-8 flex flex-col justify-center"}><span className={"font-label-sm text-label-sm text-on-primary-container tracking-[0.2em] uppercase mb-stack-sm"}>{"Engineering Integrity"}</span><h1 className={"font-display-lg text-display-lg text-white mb-stack-md leading-none"}>{"Industrial "}<br /><span className={"text-on-primary-container"}>{"Communication"}</span></h1><p className={"font-body-lg text-body-lg text-on-primary-container max-w-2xl mb-stack-lg"}>{"\n                        Architecting deterministic, high-availability protocol stacks for the digital frontier. We deliver zero-latency interconnectivity for mission-critical industrial ecosystems.\n                    "}</p><div className={"flex flex-wrap gap-stack-sm"}><Link href={"/industrial-communication"} className={"bg-white text-primary-container px-8 py-4 font-label-sm text-label-sm uppercase font-bold tracking-widest hover:bg-primary-fixed transition-all"}>{"Download Technical Spec"}</Link><Link href={"/industrial-communication"} className={"border border-white/20 text-white px-8 py-4 font-label-sm text-label-sm uppercase tracking-widest hover:bg-white/10 transition-all backdrop-blur-sm"}>{"Our Protocol Stack"}</Link></div></div></div><div className={"absolute bottom-12 left-margin-desktop hidden lg:flex items-center gap-stack-md"}><div className={"flex flex-col"}><span className={"font-label-sm text-label-sm text-on-primary-container/50"}>{"LATEST PROTOCOL"}</span><span className={"font-headline-md text-headline-md text-white"}>{"EtherCAT G"}</span></div><div className={"w-px h-12 bg-white/10"}></div><div className={"flex flex-col"}><span className={"font-label-sm text-label-sm text-on-primary-container/50"}>{"DETERMINISM"}</span><span className={"font-headline-md text-headline-md text-white"}>{"< 1μs Jitter"}</span></div></div></section>
    </>
  );
}
