import Link from "next/link";

export function Section() {
  return (
    <>
      <footer className={"w-full mt-stack-lg bg-on-secondary-fixed border-t border-outline-variant/10"}><div className={"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-gutter px-margin-desktop py-stack-lg max-w-container-max mx-auto"}><div><span className={"font-headline-md text-headline-md text-on-primary block mb-6"}>{"KnowledgeCenter"}</span><p className={"text-on-primary-container/80 text-sm leading-relaxed"}>{"Defining industrial standards through technical transparency and rigorous documentation for the global engineering community."}</p></div><div className={"flex flex-col gap-3"}><span className={"font-label-sm text-label-sm text-on-primary-container uppercase tracking-widest mb-2"}>{"Legal & Privacy"}</span><Link href={"/privacy-policy"} className={"text-on-primary-container/80 hover:text-on-primary transition-opacity font-label-sm text-label-sm underline"}>{"Privacy Policy"}</Link><Link href={"/terms-and-conditions"} className={"text-on-primary-container/80 hover:text-on-primary transition-opacity font-label-sm text-label-sm"}>{"Terms of Service"}</Link><Link href={"/terms-and-conditions"} className={"text-on-primary-container/80 hover:text-on-primary transition-opacity font-label-sm text-label-sm"}>{"Compliance"}</Link></div><div className={"flex flex-col gap-3"}><span className={"font-label-sm text-label-sm text-on-primary-container uppercase tracking-widest mb-2"}>{"Engineering"}</span><Link href={"/engineering-whitepapers"} className={"text-on-primary-container/80 hover:text-on-primary transition-opacity font-label-sm text-label-sm"}>{"Security Whitepaper"}</Link><Link href={"/contact-us"} className={"text-on-primary-container/80 hover:text-on-primary transition-opacity font-label-sm text-label-sm"}>{"Contact Engineering"}</Link><Link href={"/technical-knowledge-base"} className={"text-on-primary-container/80 hover:text-on-primary transition-opacity font-label-sm text-label-sm"}>{"API Health"}</Link></div><div className={"flex flex-col justify-end"}><p className={"font-label-sm text-label-sm text-on-primary-container/60"}>{"\n                            © 2024 Industrial Precision Engineering Group. "}<br />{"All technical rights reserved.\n                        "}</p></div></div></footer>
    </>
  );
}
