import Link from "next/link";
import { StitchImage } from "@/components/ui/StitchImage";

export function Block4Section() {
  return (
    <>
      <section className={"py-stack-lg relative"}><div className={"px-margin-desktop max-w-container-max mx-auto"}><div className={"grid grid-cols-1 lg:grid-cols-12 gap-gutter items-center"}><div className={"lg:col-span-7"}><div className={"relative group"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuCFgxkwq2jaqnU5ifDPd74YUOk6sx169BhI3Fwd_mUeaKFevr2p97hX7P9IrEmZFlalj9B3fMnUXApVIBw64HhLA2pHOnChOMsDjsSesLGc7S7U_o0DgOvdprMlsTeIlYCiwij-XtoaKM1G1xKBOnK_xODAY8QJWfzBWKvkSaEwUqcAFQrVY45LCxOfdqzU1Z9qPscnC6XIi9FHGMITjZxfsrTVVjMwQJDMoyBnHwQu7obr9WcPEhqMGszFwbnOi9GR03qRC9WqH8g"} alt={"A wide panoramic shot of a modern energy storage facility located in a Nordic coastal landscape during twilight. Several clean, white industrial containers are neatly arranged on a concrete pad, illuminated by soft blue and white LED security lighting. The background features distant snowy mountains and a calm fjord. The image conveys a sense of clean, sustainable technology integrated into a cold, pristine environment."} className={"w-full aspect-video object-cover"} /><div className={"absolute top-4 left-4 bg-primary text-on-primary px-4 py-2 font-label-sm text-label-sm"}>{"\n                            CASE STUDY: NORDIC EDGE HUB\n                        "}</div></div></div><div className={"lg:col-span-5 flex flex-col gap-stack-md"}><h3 className={"font-headline-lg text-headline-lg"}>{"Balancing the Arctic Grid"}</h3><p className={"font-body-md text-body-md text-on-surface-variant"}>{"\n                        Mind Matrix engineered the 50MWh BMS for the Nordic Edge Hub, implementing sub-zero electrolyte heating logic and ultra-low latency grid-support responses. \n                    "}</p><div className={"grid grid-cols-2 gap-4"}><div className={"bg-surface-container p-4"}><span className={"text-3xl font-bold font-display-lg"}>{"99.9%"}</span><p className={"text-xs font-label-sm uppercase opacity-60"}>{"System Uptime"}</p></div><div className={"bg-surface-container p-4"}><span className={"text-3xl font-bold font-display-lg"}>{"< 5ms"}</span><p className={"text-xs font-label-sm uppercase opacity-60"}>{"Response Latency"}</p></div></div><Link href={"/battery-management-system"} className={"border border-primary text-primary px-8 py-4 font-label-sm text-label-sm hover:bg-primary hover:text-white transition-all w-fit"}>{"\n                        Read Full Technical Paper\n                    "}</Link></div></div></div></section>
    </>
  );
}
