import Link from "next/link";
import { StitchImage } from "@/components/ui/StitchImage";

export function HeroSection() {
  return (
    <>
      <header className={"relative min-h-[870px] flex items-center overflow-hidden py-stack-lg"}><div className={"absolute inset-0 z-0"}></div><div className={"px-margin-desktop max-w-container-max mx-auto w-full relative z-10 grid grid-cols-1 md:grid-cols-12 gap-gutter items-center"}><div className={"md:col-span-6"}><div className={"inline-flex items-center gap-2 px-3 py-1 bg-primary text-on-primary font-label-sm text-label-sm mb-stack-md"}><span className={"w-2 h-2 rounded-full bg-green-400 animate-pulse"}></span>{"\n                    ACTIVE PROJECT SECTOR\n                "}</div><h1 className={"font-display-lg text-display-lg mb-stack-md leading-tight"}>{"\n                    Mission-Critical "}<br /><span className={"text-outline"}>{"Battery Management"}</span>{" Systems\n                "}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant mb-stack-lg max-w-lg"}>{"\n                    Engineering reliable, high-density energy storage architectures that bridge the gap between volatile renewables and grid stability. Precision-tuned for thermal safety and peak efficiency.\n                "}</p><div className={"flex gap-stack-md"}><Link href={"/battery-management-system"} className={"bg-primary text-on-primary px-8 py-4 font-label-sm text-label-sm hover:scale-[1.02] transition-transform flex items-center gap-2"}>{"\n                        Engineer Your Storage Solution\n                        "}<span className={"material-symbols-outlined"}>{"arrow_forward"}</span></Link></div></div><div className={"md:col-span-6 relative"}><div className={"glass-panel p-4 rounded-xl border border-outline-variant/30 overflow-hidden shadow-2xl"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuB6ERt8zhudaKwu--cBaOc8ibpF7AljR6ts8f7AX4IZxAYp0cJFaSGt2LiWPw6GHzxEaMHssSV0I9X7HR7pFsE6KeK_JxQespKyPYPrLdmmewemRqWlL2n_7ROGVWcAzjmrlGbGksdmkstDqcLg04W-juWj4fuZUBA2MIFFhh-RtGj3_qfxs2x5AmbyHQnj8uGHi5skj61X2oS0N0HXMHJ9nPfKkkhDVaouZinwEJW1HrYId2xkr_Ljd2NS6uKxtjP7V-MZtz9RLng"} alt={"A highly technical, detailed cutaway 3D render of a large containerized battery energy storage system (BESS). The image shows internal lithium-iron-phosphate (LiFePO4) battery racks, cooling conduits, and electronic control modules. The lighting is cold, surgical, and professional, reflecting an industrial high-tech manufacturing environment. The color palette is dominated by deep blues, metallic grays, and glowing technical indicators in cyan."} className={"w-full h-[500px] object-cover grayscale-[0.2] hover:grayscale-0 transition-all duration-700"} /></div></div></div></header>
    </>
  );
}
