import Link from "next/link";

export function Block3Section() {
  return (
    <>
      <section className={"py-stack-lg bg-surface"}><div className={"max-w-container-max mx-auto px-margin-desktop"}><div className={"flex flex-col md:flex-row justify-between items-end mb-16 gap-stack-md"}><div className={"max-w-2xl"}><h2 className={"font-headline-lg text-headline-lg text-primary"}>{"Industrial Ruggedness"}</h2><p className={"font-body-lg text-body-lg text-on-surface-variant mt-4"}>{"Hardware and software designed to withstand the harsh electromagnetic and physical conditions of the shop floor."}</p></div><Link href={"/connectivity"} className={"bg-primary text-on-primary px-8 py-4 font-label-sm text-label-sm uppercase tracking-widest hover:bg-secondary"}>{"Download Specs"}</Link></div><div className={"grid grid-cols-1 md:grid-cols-3 gap-gutter"}><div className={"p-8 border border-outline-variant hover:bg-white transition-colors duration-300"}><span className={"material-symbols-outlined text-3xl mb-4"} data-icon={"timer"}>{"timer"}</span><h4 className={"font-headline-md text-headline-md mb-4"}>{"Determinism"}</h4><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Guaranteed message delivery times with zero packet loss, critical for motion control and safety systems."}</p></div><div className={"p-8 border border-outline-variant hover:bg-white transition-colors duration-300"}><span className={"material-symbols-outlined text-3xl mb-4"} data-icon={"handshake"}>{"handshake"}</span><h4 className={"font-headline-md text-headline-md mb-4"}>{"Interoperability"}</h4><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Protocol translation engines that bridge legacy RS-485 Modbus to modern TSN-ready Industrial Ethernet."}</p></div><div className={"p-8 border border-outline-variant hover:bg-white transition-colors duration-300"}><span className={"material-symbols-outlined text-3xl mb-4"} data-icon={"verified_user"}>{"verified_user"}</span><h4 className={"font-headline-md text-headline-md mb-4"}>{"Fail-Safe Logic"}</h4><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Integrated watchdog timers and cyclic redundancy checks (CRC) for mission-critical data integrity."}</p></div></div></div></section>
    </>
  );
}
