import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[921px] flex items-center overflow-hidden pt-20"}><div className={"max-w-container-max mx-auto px-margin-desktop grid grid-cols-12 gap-gutter relative z-10"}><div className={"col-span-12 md:col-span-7 flex flex-col justify-center space-y-stack-md"}><div className={"inline-flex items-center space-x-2 bg-primary-fixed/30 px-3 py-1 rounded-full w-fit"}><span className={"w-2 h-2 rounded-full bg-primary animate-pulse"}></span><span className={"font-label-sm text-label-sm text-on-primary-fixed-variant uppercase tracking-widest"}>{"Enterprise IoT Framework"}</span></div><h1 className={"font-display-lg text-display-lg text-primary leading-tight"}>{"\n                        Architecting the "}<br /><span className={"text-secondary-fixed-dim"}>{"Industrial Metaverse."}</span></h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-xl"}>{"\n                        Seamlessly bridge the physical and digital divide with Mind Matrix IoT Hub and Digital Twins. Engineering precision for global manufacturing, logistics, and cloud-native embedded systems.\n                    "}</p><div className={"flex flex-wrap gap-4 pt-4"}><Link href={"/azure-iot"} className={"bg-primary text-on-primary px-8 py-4 rounded font-label-sm text-label-sm uppercase tracking-widest hover:bg-secondary transition-all"}>{"Explore Architecture"}</Link><Link href={"/azure-iot"} className={"border border-outline-variant text-primary px-8 py-4 rounded font-label-sm text-label-sm uppercase tracking-widest hover:bg-surface-container transition-all"}>{"Download Technical Specs"}</Link></div></div><div className={"col-span-12 md:col-span-5 hidden md:flex items-center justify-center"}><div className={"w-full aspect-square glass-panel rounded-xl flex items-center justify-center relative group"}><div className={"absolute inset-0 bg-gradient-to-tr from-primary-fixed/10 to-transparent opacity-50"}></div><div className={"text-center space-y-4 p-stack-lg"}><span className={"material-symbols-outlined text-6xl text-primary"} style={{"fontVariationSettings":"'FILL' 1"}}>{"hub"}</span><div className={"font-headline-md text-headline-md"}>{"IoT Hub Core"}</div><div className={"h-px w-24 bg-outline-variant mx-auto"}></div><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Bidirectional communication for billions of devices with absolute security."}</p></div></div></div></div></section>
    </>
  );
}
