import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[870px] flex items-center overflow-hidden industrial-grid"}><div className={"absolute inset-0 z-0"}><div className={"absolute inset-0 bg-gradient-to-r from-background via-background/60 to-transparent z-10"}></div><div className={"w-full h-full bg-cover bg-center"} data-alt={"A cinematic, high-altitude wide shot of a futuristic cellular communications tower standing atop a misty mountain ridge at dusk. The tower features intricate mechanical details and glowing blue status arrays. The sky is a gradient of deep twilight blues and faint purples, reflecting an industrial minimalism aesthetic with technical precision. Low-angle perspective emphasizes the scale of the infrastructure against the digital frontier."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuA5Pe2bSmh3jAdNwPH9q-8SE0vmLQd571o8fYK9tl2V6gfDY1CshdNZwxnPpHCtcQtzNM9ZcV63h47wvJfmBBeiYvZZZWAEcXp0D8doWoUK6WQqtXvQNAjpxAcyZT_WyAHY7kd-ZSsTzq0mHcSUeicHpIRis5bfklDSCpk8BW3lc-OC8Jg2JbQct3IvBqnR9G_zZDQCkS7I5Yo_eY9R4FF7Xq3_pf33URfpKp6EGLCdzkdSqKW4JZlEs_o_YnHSgl-KE4fsvjn01jM')"}}></div></div><div className={"relative z-20 w-full px-margin-desktop max-w-container-max mx-auto"}><div className={"max-w-2xl"}><span className={"inline-block py-1 px-3 border border-primary text-primary font-label-sm text-label-sm mb-stack-md"}>{"TELECOM INFRASTRUCTURE"}</span><h1 className={"font-display-lg text-display-lg mb-stack-md leading-none"}>{"High-Availability Infrastructure for the Digital Frontier"}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant mb-stack-lg max-w-lg"}>{"We engineer high-frequency communication systems that bridge the gap between global connectivity and environmental extremes."}</p><div className={"flex gap-gutter"}><Link href={"/telecom"} className={"bg-primary text-on-primary px-8 py-4 font-label-sm text-label-sm flex items-center gap-2 group transition-all"}>{"\n                            STRENGTHEN YOUR NETWORK\n                            "}<span className={"material-symbols-outlined text-[18px] group-hover:translate-x-1 transition-transform"}>{"arrow_forward"}</span></Link><Link href={"/case-studies"} className={"px-8 py-4 border border-outline font-label-sm text-label-sm hover:bg-surface-container transition-all"}>{"VIEW CASE STUDIES"}</Link></div></div></div></section>
    </>
  );
}
