import Link from "next/link";

export function Block2Section() {
  return (
    <>
      <section className={"py-stack-lg bg-primary-container"}><div className={"px-margin-desktop max-w-container-max mx-auto"}><div className={"grid grid-cols-1 md:grid-cols-2 gap-16 items-center"}><div className={"reveal-on-scroll"}><span className={"font-label-sm text-label-sm text-on-primary-container mb-4 block uppercase tracking-widest"}>{"Case Study 01"}</span><h2 className={"font-headline-lg text-headline-lg text-white mb-6"}>{"Quantum-Ready Data Architecture"}</h2><p className={"font-body-lg text-body-lg text-white/70 mb-8 leading-relaxed"}>{"\n                            For a major offshore operator, we developed a decentralized data architecture capable of handling multi-terabyte streams from subsea sensors, encrypted with post-quantum algorithms to safeguard national energy interests.\n                        "}</p><div className={"flex items-center gap-10"}><div><span className={"text-4xl font-headline-lg text-white block"}>{"40%"}</span><span className={"text-white/50 font-label-sm text-label-sm"}>{"Efficiency Gain"}</span></div><div><span className={"text-4xl font-headline-lg text-white block"}>{"Zero"}</span><span className={"text-white/50 font-label-sm text-label-sm"}>{"Downtime Incidents"}</span></div></div><Link href={"/quantum-ready-data-architecture"} className={"inline-flex items-center gap-4 text-white mt-12 font-label-sm text-label-sm group"}>{"\n                            READ FULL REPORT \n                            "}<span className={"material-symbols-outlined transition-transform group-hover:translate-x-2"}>{"arrow_forward"}</span></Link></div><div className={"relative reveal-on-scroll"}><div className={"aspect-[4/5] bg-white/5 border border-white/10 relative overflow-hidden"}><div className={"absolute inset-0 flex items-center justify-center pointer-events-none"}><div className={"w-3/4 h-3/4 border border-white/20 flex flex-col items-center justify-center p-8 bg-black/40 backdrop-blur-md"}><span className={"material-symbols-outlined text-6xl text-white mb-6"} style={{"fontVariationSettings":"'FILL' 0"}}>{"hub"}</span><span className={"text-white font-label-sm text-label-sm text-center"}>{"QUANTUM ENCRYPTION LAYER V2.4"}</span></div></div></div></div></div></div></section>
    </>
  );
}
