import Link from "next/link";

export function TechnicalOverlayElementsSection() {
  return (
    <>
      <section className={"relative h-[921px] overflow-hidden flex items-center"}><div className={"absolute inset-0 z-0"} data-alt={"A cinematic, wide-angle shot of a massive offshore oil drilling platform during a dramatic sunset. The sky is filled with deep oranges, purples, and industrial greys. The platform is intricately detailed with steel lattice structures and glowing safety lights, reflecting on the slightly choppy dark blue ocean surface. The atmosphere is powerful, resilient, and highly technical, captured with a professional high-dynamic-range photography style."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuDsCW_5UuXc5rk5mrNm_RdBLx5IFiZ_ABqGzJQxzBn1ETmOr4mgCWlB73YBpKVV2kHEFJs1HLfrM7zP4L3GMDd4z801ftH9Ze5A2-9GHJNhpEgw7IbsQmFp_WsFBdCg2zXZ_TTC9gn7wYSTJIPr4ldlMAfuP6hGUw6elx-TRlcJKpQSkf63eaHH7cqZYFUPFRmTDQxf5ZOQ1dYaESwl4yDDx9kQbs0Tt51J7DxCNSPDr5Va9v2Zrto6DOtW3XoqIHyqNuCgsA1nzDo')"}}></div><div className={"absolute inset-0 hero-gradient z-10"}></div><div className={"relative z-20 w-full px-margin-desktop max-w-container-max mx-auto"}><div className={"max-w-3xl"}><span className={"inline-block px-3 py-1 bg-primary text-on-primary font-label-sm text-label-sm mb-6 tracking-widest"}>{"OIL & GAS SECTOR"}</span><h1 className={"font-display-lg text-display-lg text-white mb-6 leading-[1.1]"}>{"Resilient Engineering for the Energy Sector"}</h1><p className={"font-body-lg text-body-lg text-white/80 max-w-2xl mb-10 leading-relaxed"}>{"Pioneering ruggedized sensor networks and ultra-low-power telemetry systems designed for the world's most demanding extraction environments."}</p><div className={"flex gap-4"}><Link href={"/quantum-ready-data-architecture"} className={"bg-white text-primary px-8 py-4 font-label-sm text-label-sm font-bold transition-all hover:bg-white/90"}>{"SECURE YOUR OPERATIONS"}</Link><Link href={"/quantum-ready-data-architecture"} className={"border border-white/30 backdrop-blur-md text-white px-8 py-4 font-label-sm text-label-sm font-bold hover:bg-white/10 transition-all"}>{"VIEW TECH STACK"}</Link></div></div></div><div className={"absolute bottom-12 right-margin-desktop z-20 hidden lg:block"}><div className={"glass-card p-6 flex flex-col gap-4"}><div className={"flex items-center gap-3"}><div className={"w-2 h-2 rounded-full bg-green-500 animate-pulse"}></div><span className={"text-white/60 font-label-sm text-label-sm"}>{"SYSTEM UPTIME: 99.99%"}</span></div><div className={"flex items-center gap-3"}><span className={"material-symbols-outlined text-white/60"} style={{"fontVariationSettings":"'FILL' 0"}}>{"verified_user"}</span><span className={"text-white/60 font-label-sm text-label-sm"}>{"ATEX/IECEx COMPLIANT"}</span></div></div></div></section>
    </>
  );
}
