import { StitchImage } from "@/components/ui/StitchImage";

export function Section() {
  return (
    <>
      <section className={"py-stack-lg px-margin-desktop max-w-container-max mx-auto"}><div className={"grid grid-cols-12 gap-gutter items-center"}><div className={"col-span-12 lg:col-span-6"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDzCqBCzqpTHU2s__5snDY43d_FMwortYWz09D1GqCvaI5OX2bclTwbWzvI9W8p29HtaHpShWHeIFvK_BLSKWkK8iKYXaGKiFFal8iTOZLph9LEyzFLXVLIANtJT-IR-LRUvC9Lneg6ItJ5EwKExltCN00xh-r_6vjFDQAVh0jeEtimWg6PMzhOT__HtjIzrHTR-E_twQHFfWD1-cy7Z-S-3nO3OqxbLSQexBTvlPdFaALHMffcbtk6yVoJXA8jSEa5cIynCTJ0cEo"} alt={"A clean, minimalist photograph of an engineering dashboard displaying real-time sensor data in a high-tech facility. The screen shows precise line charts in electric blue and white, indicating stable environmental metrics. In the soft-focus background, a pristine white cleanroom environment is visible, with a technician in a sterile suit working on delicate equipment. The overall aesthetic is clinical, organized, and technologically superior."} className={"w-full aspect-[4/3] object-cover rounded-xl shadow-xl"} /></div><div className={"col-span-12 lg:col-span-6 lg:pl-12"}><h2 className={"font-headline-lg text-headline-lg mb-8"}>{"Engineering Results"}</h2><ul className={"space-y-8"}><li className={"flex items-start gap-6 border-b border-outline-variant/20 pb-6"}><div className={"text-primary font-display-lg text-headline-lg leading-none w-20"}>{"12ms"}</div><div><h5 className={"font-bold mb-1"}>{"Response Time"}</h5><p className={"text-on-surface-variant"}>{"Critical system correction speed to thermal disturbance detection."}</p></div></li><li className={"flex items-start gap-6 border-b border-outline-variant/20 pb-6"}><div className={"text-primary font-display-lg text-headline-lg leading-none w-20"}>{"+15%"}</div><div><h5 className={"font-bold mb-1"}>{"Wafer Yield Increase"}</h5><p className={"text-on-surface-variant"}>{"Direct correlation between environmental stability and product quality."}</p></div></li><li className={"flex items-start gap-6"}><div className={"text-primary font-display-lg text-headline-lg leading-none w-20"}>{"-30%"}</div><div><h5 className={"font-bold mb-1"}>{"Energy Reduction"}</h5><p className={"text-on-surface-variant"}>{"Predictive cooling cycles reducing redundant HVAC waste."}</p></div></li></ul></div></div></section>
    </>
  );
}
