import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[870px] flex items-center overflow-hidden bg-primary-container"}><div className={"absolute inset-0 z-0 opacity-40"}><div className={"w-full h-full bg-cover bg-center"} data-alt={"A cinematic, high-resolution photograph of a rugged industrial sensor node deployed on the mossy edge of a crystal clear forest waterway. The lighting is early morning soft mist, with sunlight breaking through tall coniferous trees. The camera angle is low, highlighting the metallic texture and precise engineering of the sensor against the organic, lush green environment. The overall mood is one of technical authority and environmental harmony, utilizing a cool-toned, professional color palette."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuBnXBqmhV6me6yh4EL45GjjxIhCKoIek5SLp7DzLQ2zegLxG6NBrQyzAZo95gZhJ7gb6qdiKRqgQXCRbZXDXGnk7HQSV2RgR6ePgLg3b3hhHlc9p5ny-OOy-lSqtefhb-Y5iSiic2RF6ksUrnNZCeMjENWurVBqC_r5nJFK9B1corxKwYloPtqjeAdOSTqIn4rrGq7m721xhft2WJ2CGe-E_xTf8fMmHX9painiWG9xqDYmXc6dOPB0qOEMKElWAE1H0NgvUp6cIxQ')"}}></div></div><div className={"absolute inset-0 bg-gradient-to-r from-primary-container via-primary-container/80 to-transparent z-10"}></div><div className={"relative z-20 px-margin-desktop max-w-container-max mx-auto w-full"}><div className={"max-w-2xl space-y-stack-md"}><span className={"inline-block py-1 px-3 border border-outline-variant text-on-primary-container font-label-sm text-label-sm uppercase tracking-widest"}>{"Industry Expertise"}</span><h1 className={"font-display-lg text-display-lg text-on-primary leading-none"}>{"Data-Driven Stewardship for the Planet"}</h1><p className={"font-body-lg text-body-lg text-on-primary-container/80 leading-relaxed max-w-xl"}>{"\n                    Engineering precision for fragile ecosystems. We bridge the gap between heavy industry and ecological preservation through hardened, low-power monitoring architectures.\n                "}</p><div className={"flex flex-wrap gap-stack-sm pt-4"}><Link href={"/nanolithography-cluster-control"} className={"bg-surface text-primary px-8 py-4 rounded-none font-label-sm text-label-sm hover:bg-secondary-fixed transition-colors"}>{"Download Specs"}</Link><Link href={"/case-studies"} className={"border border-outline-variant text-on-primary px-8 py-4 rounded-none font-label-sm text-label-sm hover:bg-white/10 transition-colors"}>{"View Case Studies"}</Link></div></div></div></section>
    </>
  );
}
