import Link from "next/link";

export function Block2Section() {
  return (
    <>
      <section className={"py-stack-lg bg-surface"}><div className={"px-margin-desktop max-w-container-max mx-auto"}><div className={"flex flex-col md:flex-row gap-gutter items-stretch"}><div className={"md:w-1/3 bg-surface-container-low p-12 flex flex-col justify-center"}><span className={"font-label-sm text-label-sm text-primary uppercase tracking-[0.2em] mb-4"}>{"Case Study"}</span><h2 className={"font-headline-lg text-headline-lg mb-6 leading-tight"}>{"Distributed Control Architecture"}</h2><p className={"font-body-md text-body-md text-on-surface-variant mb-8"}>{"Implementing a decentralized logic system for a multi-national aerospace manufacturer, resulting in a 24% increase in production throughput."}</p><Link href={"/manufacturing"} className={"inline-flex items-center gap-2 font-bold text-primary hover:underline group"}>{"\n                        Download PDF Blueprint\n                        "}<span className={"material-symbols-outlined text-[18px]"}>{"download"}</span></Link></div><div className={"md:w-2/3 relative min-h-[400px]"}><div className={"w-full h-full bg-cover bg-center rounded-lg"} data-alt={"A detailed technical blueprint of a distributed control system displayed on a high-resolution 4K monitor. The scene shows a clean, modern workstation in an engineering lab. The lighting is focused and professional, highlighting the contrast between the dark monitor screen and the bright, minimalist office environment. The style is strictly industrial and technical, featuring sharp lines and high-contrast visuals."} style={{"backgroundImage":"url('https://lh3.googleusercontent.com/aida-public/AB6AXuBmZWjNKPtjpFsAY-_rKs-Fqpiq2xD1TWodEao8s91jX9awnos9yG55nV4_q-1rfM5KgvD3C77-SE4DMJ-ArPRnrXAVauQNpQWc6ZT3Sg25MGmtDNKauELaQV0EbGHGI93tN8Vp-U4P7WbKwaISYh72YtMThbJ-ISkY-jG3x2K4o008Nb505ZX-3J8mtOvAfp-cqLdIFVU1dsgC8mWMK3CEfq9N26VlVf59r8vXIJMGP-8WBhbz0eNiLGU24j5sfhFcA1p6xm-GSDs')"}}></div><div className={"absolute top-8 right-8 glass-card p-6 border border-white/20"}><div className={"text-display-lg text-primary font-display-lg"}>{"24%"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant"}>{"THROUGHPUT INCREASE"}</div></div></div></div></div></section>
    </>
  );
}
