import Link from "next/link";

export function Block2Section() {
  return (
    <>
      <section className={"py-stack-lg px-margin-desktop bg-primary text-white"}><div className={"max-w-container-max mx-auto text-center"}><h2 className={"font-display-lg text-headline-lg mb-stack-md"}>{"Ready to optimize your grid assets?"}</h2><p className={"font-body-lg text-white/60 mb-stack-lg max-w-2xl mx-auto"}>{"\n                    Download the full technical architecture for the Atacama Solar Reserve and see how our SiC-based BESS systems can scale your operations.\n                "}</p><div className={"flex flex-col sm:flex-row justify-center gap-stack-md"}><Link href={"/smart-grid"} className={"bg-white text-primary px-10 py-5 rounded-lg font-label-sm text-label-sm hover:bg-innovation-cyan hover:text-white transition-all"}>{"\n                        Download Technical Whitepaper\n                    "}</Link><Link href={"/smart-grid"} className={"border border-white/20 text-white px-10 py-5 rounded-lg font-label-sm text-label-sm hover:bg-white/10 transition-all"}>{"\n                        Speak to an Engineer\n                    "}</Link></div><div className={"mt-20 pt-stack-lg border-t border-white/10 text-left"}><h4 className={"font-label-sm text-label-sm text-white/40 uppercase mb-stack-md tracking-widest"}>{"Related Case Studies"}</h4><div className={"grid grid-cols-1 md:grid-cols-2 gap-gutter"}><Link href={"/smart-grid"} className={"group flex items-center justify-between p-stack-md border border-white/10 rounded-xl hover:bg-white/5 transition-all"}><div><h5 className={"font-headline-md text-headline-md group-hover:text-innovation-cyan transition-colors"}>{"Smart Grid Implementation"}</h5><p className={"text-label-sm text-white/50"}>{"Berlin Urban Infrastructure"}</p></div><span className={"material-symbols-outlined group-hover:translate-x-2 transition-transform"}>{"arrow_forward"}</span></Link><Link href={"/smart-grid"} className={"group flex items-center justify-between p-stack-md border border-white/10 rounded-xl hover:bg-white/5 transition-all"}><div><h5 className={"font-headline-md text-headline-md group-hover:text-innovation-cyan transition-colors"}>{"Energy Management AI"}</h5><p className={"text-label-sm text-white/50"}>{"Global Logistics Hub"}</p></div><span className={"material-symbols-outlined group-hover:translate-x-2 transition-transform"}>{"arrow_forward"}</span></Link></div></div></div></section>
    </>
  );
}
