import Link from "next/link";
import { StitchImage } from "@/components/ui/StitchImage";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[819px] flex items-center overflow-hidden py-stack-lg"}><div className={"absolute inset-0 z-0"}></div><div className={"container max-w-container-max mx-auto px-margin-desktop grid grid-cols-12 gap-gutter relative z-10"}><div className={"col-span-12 lg:col-span-7 flex flex-col justify-center"}><span className={"font-label-sm text-label-sm uppercase tracking-widest text-secondary mb-4"}>{"Technical Specification v3.0"}</span><h1 className={"font-display-lg text-display-lg mb-6 leading-tight"}>{"ESP32: The Apex of IoT Convergence"}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-xl mb-stack-md"}>{"\n                        Engineered for the demands of industrial precision and mobile connectivity, the ESP32 platform integrates Wi-Fi, dual-mode Bluetooth, and dual-core processing into a single, power-efficient SoC.\n                    "}</p><div className={"flex gap-stack-sm"}><Link href={"/connectivity"} className={"bg-primary text-on-primary px-8 py-4 font-label-sm text-label-sm flex items-center gap-2 group transition-all active:scale-95"}>{"\n                            EXPLORE ARCHITECTURE\n                            "}<span className={"material-symbols-outlined text-[18px] group-hover:translate-x-1 transition-transform"}>{"arrow_forward"}</span></Link></div></div><div className={"col-span-12 lg:col-span-5 flex items-center"}><div className={"glass-panel p-2 rounded-xl w-full border-outline-variant/20 shadow-2xl"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuAR98VuzWhYLoZtBd0AIX8OHGBA25T-F-nvNf0_EcoS9XWN2IH-bamXAg5loFJ4m9PnaUJrjUlxZAgHGwqZkgzR6x0-lbb-6m630NJvQJTK_f6tP2mfAL59qVrj0scNfwHTVh8bFiiamsmxMxJyX33Og-Dd9biD-UDxqexcBJs26AYmQN0CSnEC7IFP8WjrgHV7hW1Sw_uQghfhk9L36OkK5I_xx-6BH6BA8CrQ48LayDqWeylCX8VffVg0m4bBnFTPtiZI6KG_gHw"} alt={"A highly detailed close-up shot of an ESP32 microcontroller chip mounted on a black PCB circuit board. The lighting is cold and professional with cyan and white highlights reflecting off the technical metal surfaces. The scene is clean, minimal, and conveys high-tech industrial precision. The background is a blurred dark laboratory environment with technical displays."} className={"w-full h-auto rounded-lg object-cover aspect-[4/3]"} /></div></div></div></section>
    </>
  );
}
