import Link from "next/link";
import { StitchImage } from "@/components/ui/StitchImage";

export function SubtleBackgroundDecorationSection() {
  return (
    <>
      <section className={"py-stack-lg border-t border-outline-variant/20"}><div className={"max-w-container-max mx-auto px-margin-desktop text-center"}><div className={"max-w-3xl mx-auto bg-surface p-12 md:p-20 rounded-2xl border border-outline-variant shadow-sm relative overflow-hidden"}><div className={"absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"}></div><h2 className={"font-display-lg text-headline-lg mb-6"}>{"Ready to Engineer Your "}<br />{"Connectivity Strategy?"}</h2><p className={"font-body-lg text-on-surface-variant mb-10"}>{"Our engineers are ready to assist with your mesh network architecture design, hardware selection, and deployment roadmap."}</p><div className={"flex flex-col md:flex-row gap-4 justify-center"}><Link href={"/request-consultation"} className={"bg-primary text-on-primary px-10 py-5 rounded-lg font-label-sm text-label-sm hover:opacity-90 transition-opacity shadow-lg"}>{"Schedule Technical Review"}</Link><Link href={"/contact-us"} className={"bg-white border border-outline-variant px-10 py-5 rounded-lg font-label-sm text-label-sm hover:bg-surface-container-low transition-colors"}>{"Contact Sales"}</Link></div><div className={"mt-12 flex items-center justify-center gap-8 opacity-60"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuBlQDy9u3c4RZYIxy3ETCxpLjEPZHKvDh-OFDc9lXmpBrw--NlvIgzTk1bDhRIFbxxOR7ih1g1oeXTh0iVg9iJPSoRsuPhTR5akXoKpT0NgT8Eecclz_7goZABRwEmpTUEHznKYSsfe_yCz2aga6Ty4zAOk1kemeR_PMaHW6E2LVuEYqJ41aNUV17CIwGTGTg3XxcDUQWG_aBxCZHWTzAeuCeWhMvgA7dm76yQX8GwHq-cC8JKMWPzseM6cJZAWPtrGH0fFg8eotYU"} alt={"Partner"} className={"h-6 grayscale"} /><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuBvjjzo8d8lTxlyqxJvp5hHYNzKNCxFsOcEdsksdej0V7vGRb03cRoZz4b7ErhDhxu0peXNFem_symKCA_gMQSuGBCne7c4EVod_btTo2ST3XjSJRtkwRjp2pkK-bliii3cMY6_7M7eH9RSk0H88w3l59FOEFpwWODIqGMCrkDnE_9mxKyy7f59os41xGd658IsCPWKKdcsLlapFwDcZPJw3G0RX2N6c0OtFCUMFdipLXYAtrLtC5A7yV3TABdG7-kOZBxEbFQO1ag"} alt={"Partner"} className={"h-6 grayscale"} /><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuB2l4EKmLnm6FmUUnOiT2B9d3KMnOKHXJ12g1ZoCjM-P7fvWL3BBEZrPJDtkQaCl-6uEDXqr3FE7XQvYi0_5kqN-W8BABmF2leqcsL1mi8LCy43NjN_zKOWpba_VC2Uza9CGWnDGGvhYahrabEzV1e1m4g6r2IVvLsYXKWi5fRpMfODLpOJIc4-DvpoTTJwgQ-77XtZ8PXHXKMlpRnB57yO_tbwChU3-GUIeitsJjunZNbodiobwRTRZCa7NlBxigC-vaWayi1IIrA"} alt={"Partner"} className={"h-6 grayscale"} /></div></div></div></section>
    </>
  );
}
