import { StitchImage } from "@/components/ui/StitchImage";

export function Section() {
  return (
    <>
      <section className={"py-stack-lg bg-surface-container-low"}><div className={"max-w-container-max mx-auto px-margin-desktop grid grid-cols-12 gap-gutter items-center"}><div className={"col-span-12 lg:col-span-5"}><div className={"inline-block px-3 py-1 bg-primary text-on-primary rounded font-label-sm text-label-sm mb-4"}>{"ENGINEERING EXPERIENCE"}</div><h2 className={"font-headline-lg text-headline-lg mb-6 leading-tight"}>{"Wireless Stack Optimization for Mission-Critical Data"}</h2><div className={"space-y-6"}><div className={"flex gap-4"}><div className={"flex-shrink-0 w-12 h-12 bg-surface-container-highest rounded-lg flex items-center justify-center"}><span className={"material-symbols-outlined text-primary"}>{"waves"}</span></div><div><h5 className={"font-bold mb-1"}>{"Low Latency Mesh Networks"}</h5><p className={"text-on-surface-variant text-sm"}>{"Advanced mesh algorithms for thousands of nodes in industrial lighting and automation."}</p></div></div><div className={"flex gap-4"}><div className={"flex-shrink-0 w-12 h-12 bg-surface-container-highest rounded-lg flex items-center justify-center"}><span className={"material-symbols-outlined text-primary"}>{"memory"}</span></div><div><h5 className={"font-bold mb-1"}>{"nRF Connect SDK"}</h5><p className={"text-on-surface-variant text-sm"}>{"Unified development environment using Zephyr RTOS for future-proofed application logic."}</p></div></div></div></div><div className={"col-span-12 lg:col-span-7 relative"}><div className={"glass-panel p-6 rounded-2xl shadow-xl overflow-hidden border border-outline-variant"}><div className={"flex justify-between items-center mb-6"}><div className={"flex gap-2"}><div className={"w-3 h-3 rounded-full bg-red-400"}></div><div className={"w-3 h-3 rounded-full bg-amber-400"}></div><div className={"w-3 h-3 rounded-full bg-emerald-400"}></div></div><div className={"text-label-sm font-label-sm opacity-50 uppercase tracking-tighter"}>{"Architecture.sys // stack_viewer"}</div></div><div className={"relative aspect-video rounded-lg overflow-hidden bg-primary-container"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuC3B2LSO6tDYl-O_A93K8fGmUTs74ka1W_bj1CjcREbNUUhIw0Yqp3HS4MMiXTDBBq28kw1WyR9GgLy6HZHacBWoJ4agdERlVnhRw2xkLWulya6ZC2AwS9xEpnLl0WasROZspOrp4x2kVfrUyUexb78QNSPt2gVCb07l9kk9_zklEc-kBSHTWo3XyACSmWNj3Hr2SqrlJLo6wG5sJuMxRGGsQeJOTjmheMzAthhLF9Wg7drl5mRR4AlzG3l7XXaUsUa88iiUrwslsw"} alt={"A highly technical 3D schematic diagram of a semi-conductor internal architecture with glowing cyan pathways and data nodes. The aesthetic is clean-room industrial with high-contrast black backgrounds and sharp technical lines. Soft white light catches the edges of the silicon substrate, suggesting precision manufacturing and advanced technology."} className={"w-full h-full object-cover opacity-80"} /><div className={"absolute inset-0 bg-gradient-to-t from-primary-container via-transparent to-transparent"}></div></div></div></div></div></section>
    </>
  );
}
