import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[819px] flex items-center overflow-hidden grid-bg"}><div className={"absolute inset-0 bg-gradient-to-b from-transparent via-background/50 to-background"}></div><div className={"max-w-container-max mx-auto px-margin-desktop grid grid-cols-12 gap-gutter relative z-10"}><div className={"col-span-12 lg:col-span-7 flex flex-col justify-center gap-stack-md"}><div className={"inline-flex items-center gap-2 px-3 py-1 bg-primary text-on-primary w-fit font-label-sm text-label-sm tracking-widest uppercase"}>{"\n                        Protocol Engineering\n                    "}</div><h1 className={"font-display-lg text-display-lg text-primary leading-none"}>{"MQTT: Precision Data Orchestration"}</h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-2xl"}>{"\n                        A lightweight messaging protocol engineered for the digital frontier. Designed for mission-critical industrial IoT where bandwidth is scarce and reliability is non-negotiable.\n                    "}</p><div className={"flex gap-stack-sm mt-4"}><Link href={"/industrial-automation"} className={"bg-primary text-on-primary px-8 py-4 font-label-sm text-label-sm uppercase tracking-widest flex items-center gap-2 group transition-all"}>{"\n                            Explore Specs\n                            "}<span className={"material-symbols-outlined group-hover:translate-x-1 transition-transform"} data-icon={"arrow_forward"}>{"arrow_forward"}</span></Link><Link href={"/industrial-automation"} className={"border border-outline-variant px-8 py-4 font-label-sm text-label-sm uppercase tracking-widest hover:bg-surface-container transition-all"}>{"\n                            Technical Docs\n                        "}</Link></div></div><div className={"col-span-12 lg:col-span-5 relative hidden lg:block"}><div className={"aspect-square glass-panel p-gutter relative"}><div className={"absolute inset-0 flex items-center justify-center"}><div className={"w-64 h-64 border-2 border-primary/20 rounded-full animate-pulse"}></div><div className={"absolute w-48 h-48 border border-primary/40 rounded-full animate-ping"}></div></div><div className={"h-full w-full border border-outline-variant/30 flex flex-col items-center justify-center gap-stack-md relative z-10"}><span className={"material-symbols-outlined text-[80px] text-primary"} data-icon={"hub"}>{"hub"}</span><div className={"text-center"}><p className={"font-label-sm text-label-sm text-primary tracking-widest uppercase"}>{"Central Broker"}</p><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Low Latency Pulse"}</p></div></div></div></div></div></section>
    </>
  );
}
