import Link from "next/link";

export function MajorQuickStartCardSection() {
  return (
    <>
      <section className={"mb-stack-lg"}><div className={"flex items-center gap-3 mb-stack-md"}><span className={"material-symbols-outlined text-primary"}>{"bolt"}</span><h2 className={"font-headline-lg text-headline-lg"}>{"Quick Start"}</h2></div><div className={"grid grid-cols-12 gap-gutter"}><div className={"col-span-12 lg:col-span-7 p-8 bg-surface-container-low rounded-xl border border-outline-variant/20 relative group overflow-hidden technical-glow transition-all"}><div className={"relative z-10"}><span className={"bg-primary text-on-primary px-3 py-1 rounded text-[10px] font-bold tracking-widest uppercase mb-6 inline-block"}>{"MANDATORY"}</span><h3 className={"font-headline-md text-headline-md mb-3"}>{"Workspace Core Deployment"}</h3><p className={"text-on-surface-variant mb-8 max-w-md"}>{"The fundamental architecture for multi-tenant engineering workspaces. Configure secure nodes and local-first data synchronization."}</p><div className={"flex gap-4"}><Link href={"/application-notes-and-design-guides"} className={"bg-primary text-on-primary px-5 py-2 rounded-lg font-label-sm hover:bg-on-secondary-fixed transition-colors"}>{"VIEW SCHEMATIC"}</Link><Link href={"/application-notes-and-design-guides"} className={"border border-outline px-5 py-2 rounded-lg font-label-sm hover:bg-surface-variant/30 transition-colors"}>{"COPY CLI CMD"}</Link></div></div><div className={"absolute right-0 top-0 w-1/2 h-full opacity-10 group-hover:opacity-20 transition-opacity"}><span className={"material-symbols-outlined text-[240px] absolute -right-20 -top-10"}>{"account_tree"}</span></div></div><div className={"col-span-12 lg:col-span-5 p-8 bg-on-secondary-fixed text-on-primary rounded-xl relative overflow-hidden technical-glow transition-all"}><span className={"text-primary-fixed font-label-sm tracking-widest uppercase mb-4 block"}>{"Optimization"}</span><h3 className={"font-headline-md text-headline-md mb-2"}>{"Memory Matrix v2"}</h3><p className={"opacity-70 text-body-md mb-6"}>{"Optimizing cache invalidation for massive technical datasets."}</p><Link href={"/application-notes-and-design-guides"} className={"inline-flex items-center gap-2 text-primary-fixed hover:underline font-label-sm"}>{"\n                            READ DOCS "}<span className={"material-symbols-outlined text-[18px]"}>{"arrow_forward"}</span></Link></div></div></section>
    </>
  );
}
