import Link from "next/link";

export function DecorativeRadialGlowSection() {
  return (
    <>
      <section className={"py-stack-lg relative overflow-hidden"}><div className={"absolute inset-0 bg-primary-container"}></div><div className={"max-w-container-max mx-auto px-margin-desktop relative z-10"}><div className={"bg-surface-container-lowest p-stack-lg rounded-2xl border border-on-primary/10 shadow-2xl flex flex-col md:flex-row items-center justify-between gap-gutter"}><div className={"max-w-2xl"}><h2 className={"font-display-lg text-headline-lg text-primary mb-4"}>{"Precision Oversight. Reduced Risk."}</h2><ul className={"space-y-4 mb-8"}><li className={"flex items-start gap-3"}><span className={"material-symbols-outlined text-[#2563EB]"}>{"check_circle"}</span><span className={"font-body-md text-body-md text-on-surface-variant"}>{"Reduce emergency maintenance costs by up to 35% through predictive alerts."}</span></li><li className={"flex items-start gap-3"}><span className={"material-symbols-outlined text-[#2563EB]"}>{"check_circle"}</span><span className={"font-body-md text-body-md text-on-surface-variant"}>{"Centralize global fleet visibility into a single technical glass pane."}</span></li><li className={"flex items-start gap-3"}><span className={"material-symbols-outlined text-[#2563EB]"}>{"check_circle"}</span><span className={"font-body-md text-body-md text-on-surface-variant"}>{"Enable automated compliance reporting with immutable data logs."}</span></li></ul><div className={"flex flex-wrap gap-4"}><Link href={"/manufacturing"} className={"bg-primary text-on-primary font-label-sm text-label-sm px-10 py-5 rounded hover:bg-[#2563EB] transition-all technical-glow"}>{"Schedule System Demo"}</Link><Link href={"/manufacturing"} className={"border border-outline px-10 py-5 font-label-sm text-label-sm rounded hover:bg-surface-variant transition-all"}>{"Download Brochure"}</Link></div></div><div className={"w-full md:w-1/3 aspect-square glass rounded-xl flex items-center justify-center p-8 border border-outline-variant/30 relative overflow-hidden"}><div className={"absolute inset-0 grid-mesh opacity-10"}></div><div className={"text-center relative z-10"}><div className={"text-6xl font-display-lg text-primary mb-2"}>{"35%"}</div><div className={"font-label-sm text-label-sm text-on-surface-variant uppercase tracking-widest"}>{"Efficiency Gain"}</div></div><div className={"absolute -bottom-1/2 -right-1/2 w-full h-full bg-[#2563EB]/10 rounded-full blur-[100px]"}></div></div></div></div></section>
    </>
  );
}
