import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <header className={"relative w-full h-[716px] flex items-center overflow-hidden bg-primary-container"}><div className={"absolute inset-0 z-0 opacity-40"}><div className={"w-full h-full bg-[url('https://lh3.googleusercontent.com/aida-public/AB6AXuC8Lc9ek2leanWwsnuRipJWXMkKpeEomytTsKi2PmjiHjwcqZxRZZBc3hpFzZbkxg6nZoxtarHI-Oxh7sxD4jjdbyG65FO4sLfKo5HukLyU_56vyQWcBTVVXbPrz8Lp1mU0ukUC2OhIrZRlcvlQvDR-dIe5jp15vZYR2CgeujidebRP4FboY0JwmNOmJEIaHEiKDDRiTl9KMcJmKAyszHz8G3KSh6mNGGKneBYG1v4E2PAFcb90mDHjEgSoa49RN1-pI81RN7LjaMc')] bg-cover bg-center mix-blend-overlay"} data-alt={"A highly complex 3D CAD model of a precision-engineered industrial component, showcasing intricate wireframes and technical measurements. The aesthetic is monochromatic navy and silver with thin cyan glowing lines tracing the geometry, suggesting extreme technical authority and digital precision. Soft atmospheric lighting illuminates the metallic surfaces within a vast clean-room digital environment."}></div></div><div className={"absolute inset-0 bg-gradient-to-r from-primary-container via-primary-container/80 to-transparent z-10"}></div><div className={"relative z-20 px-margin-desktop max-w-container-max mx-auto w-full"}><div className={"max-w-3xl space-y-stack-md"}><div className={"inline-flex items-center gap-2 px-3 py-1 bg-primary text-white rounded-full"}><span className={"material-symbols-outlined text-[14px]"}>{"precision_manufacturing"}</span><span className={"font-label-sm text-label-sm tracking-widest uppercase"}>{"Systemic Reliability"}</span></div><h1 className={"font-display-lg text-display-lg text-white leading-tight"}>{"\n                    A Disciplined Approach to "}<span className={"text-secondary-fixed"}>{"Engineering Excellence"}</span></h1><p className={"font-body-lg text-body-lg text-on-primary-container max-w-xl"}>{"\n                    We bridge the gap between visionary concepts and industrial-grade reality through a rigid framework of technical validation and systemic oversight.\n                "}</p><div className={"flex gap-stack-md pt-base"}><Link href={"/hardware-development"} className={"bg-white text-primary px-8 py-4 rounded-lg font-label-sm text-label-sm font-bold flex items-center gap-2 hover:bg-secondary-fixed transition-colors"}>{"\n                        Explore Methodology\n                        "}<span className={"material-symbols-outlined"}>{"arrow_downward"}</span></Link></div></div></div></header>
    </>
  );
}
