import Link from "next/link";

export function Block4Section() {
  return (
    <>
      <section className={"py-stack-lg bg-white"}><div className={"px-margin-desktop max-w-3xl mx-auto"}><h2 className={"font-headline-lg text-headline-lg text-primary mb-12 text-center"}>{"Frequently Asked Questions"}</h2><div className={"space-y-4"}><div className={"border-b border-outline-variant/20 py-6"}><Link href={"/manufacturing"} className={"w-full flex justify-between items-center text-left"}><span className={"font-headline-md text-headline-md"}>{"What is your typical project timeline?"}</span><span className={"material-symbols-outlined arrow transition-transform"}>{"expand_more"}</span></Link><div className={"mt-4 text-on-surface-variant font-body-md hidden"}>{"\n                            Typical engagements range from 3 months for specific validation tasks to 18+ months for full-cycle product development from concept to mass production.\n                        "}</div></div><div className={"border-b border-outline-variant/20 py-6"}><Link href={"/manufacturing"} className={"w-full flex justify-between items-center text-left"}><span className={"font-headline-md text-headline-md"}>{"How do you handle IP protection?"}</span><span className={"material-symbols-outlined arrow transition-transform"}>{"expand_more"}</span></Link><div className={"mt-4 text-on-surface-variant font-body-md hidden"}>{"\n                            We operate under strict master service agreements (MSAs) where all resulting intellectual property is owned by the client upon project completion.\n                        "}</div></div><div className={"border-b border-outline-variant/20 py-6"}><Link href={"/manufacturing"} className={"w-full flex justify-between items-center text-left"}><span className={"font-headline-md text-headline-md"}>{"Do you manage the actual manufacturing?"}</span><span className={"material-symbols-outlined arrow transition-transform"}>{"expand_more"}</span></Link><div className={"mt-4 text-on-surface-variant font-body-md hidden"}>{"\n                            Yes, through our verified network of global Tier-1 manufacturing partners, we provide full scale-up management and quality control oversight.\n                        "}</div></div></div></div></section>
    </>
  );
}
