import Link from "next/link";

export function HeroSection() {
  return (
    <>
      <section className={"relative min-h-[921px] flex items-center overflow-hidden bg-white"}><div className={"absolute inset-0 z-0"}><div className={"w-full h-full bg-[url('https://lh3.googleusercontent.com/aida-public/AB6AXuC8Lc9ek2leanWwsnuRipJWXMkKpeEomytTsKi2PmjiHjwcqZxRZZBc3hpFzZbkxg6nZoxtarHI-Oxh7sxD4jjdbyG65FO4sLfKo5HukLyU_56vyQWcBTVVXbPrz8Lp1mU0ukUC2OhIrZRlcvlQvDR-dIe5jp15vZYR2CgeujidebRP4FboY0JwmNOmJEIaHEiKDDRiTl9KMcJmKAyszHz8G3KSh6mNGGKneBYG1v4E2PAFcb90mDHjEgSoa49RN1-pI81RN7LjaMc')] bg-cover bg-center opacity-40 mix-blend-multiply"} data-alt={"A high-fidelity cinematic rendering of an advanced industrial robotic arm performing precision assembly on a sleek, carbon-fiber medical device. The scene is set in a pristine, futuristic clean-room laboratory with bright, cool lighting and subtle blue technical overlays. The atmosphere reflects extreme technical precision and industrial authority with a minimalist light-mode aesthetic."}></div><div className={"absolute inset-0 bg-gradient-to-r from-background via-background/80 to-transparent"}></div></div><div className={"relative z-10 px-margin-desktop max-w-container-max mx-auto w-full grid grid-cols-12 gap-gutter"}><div className={"col-span-12 md:col-span-8 flex flex-col justify-center"}><span className={"inline-block px-3 py-1 rounded bg-primary text-white font-label-sm text-label-sm mb-6 w-fit uppercase tracking-widest"}>{"Enterprise Precision"}</span><h1 className={"font-display-lg text-display-lg text-primary leading-tight mb-8"}>{"Engineering the "}<br /><span className={"text-outline"}>{"Digital Frontier."}</span></h1><p className={"font-body-lg text-body-lg text-on-surface-variant max-w-2xl mb-12"}>{"\n                        Accelerate innovation with Mind Matrix's end-to-end product development suite. From intricate mechanical engineering to mass-market production, we provide technical authority at every micron.\n                    "}</p><div className={"flex gap-4"}><Link href={"/manufacturing"} className={"bg-primary text-white px-8 py-4 font-label-sm text-label-sm uppercase tracking-widest rounded transition-all hover:bg-primary/90 technical-glow"}>{"Start Your Project"}</Link><Link href={"/case-studies"} className={"border border-outline-variant px-8 py-4 font-label-sm text-label-sm uppercase tracking-widest rounded hover:bg-surface-container transition-all"}>{"View Case Studies"}</Link></div></div></div></section>
    </>
  );
}
