import { StitchImage } from "@/components/ui/StitchImage";

export function Section() {
  return (
    <>
      <section className={"py-stack-lg px-margin-desktop max-w-container-max mx-auto"}><div className={"grid grid-cols-12 gap-gutter items-center"}><div className={"col-span-12 md:col-span-5"}><h2 className={"font-headline-lg text-headline-lg text-primary mb-8 leading-tight"}>{"Specialized Platforms for "}<br />{"Every Domain"}</h2><div className={"space-y-6"}><div className={"flex gap-4 items-start"}><span className={"material-symbols-outlined text-primary p-2 bg-surface-container rounded"}>{"shopping_bag"}</span><div><h4 className={"font-headline-md text-headline-md"}>{"Consumer Products"}</h4><p className={"font-body-md text-body-md text-on-surface-variant"}>{"High-volume, aesthetic-driven hardware with complex assembly logic."}</p></div></div><div className={"flex gap-4 items-start"}><span className={"material-symbols-outlined text-primary p-2 bg-surface-container rounded"}>{"medical_services"}</span><div><h4 className={"font-headline-md text-headline-md"}>{"Medical Devices"}</h4><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Compliant, high-reliability engineering for life-critical applications (ISO 13485)."}</p></div></div><div className={"flex gap-4 items-start"}><span className={"material-symbols-outlined text-primary p-2 bg-surface-container rounded"}>{"factory"}</span><div><h4 className={"font-headline-md text-headline-md"}>{"Industrial Systems"}</h4><p className={"font-body-md text-body-md text-on-surface-variant"}>{"Ruggedized equipment designed for 24/7 uptime in harsh environments."}</p></div></div></div></div><div className={"col-span-12 md:col-span-7 h-[600px] bg-white p-4"}><div className={"w-full h-full rounded-xl overflow-hidden relative border border-outline-variant/10 shadow-2xl"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDAlo5efbzDcYrlpBvhrZ1McEAgY37aPSHTu6pMUoVvwj2-pxHBa82R0VZEFUcRyVmNffrei0EpeGt6OTEy7SOI09ZzmlEBgzBHsJRwhAA0IM3Bq1g43ltrm9wezBfRLfxaD9AqF_oBl8FIxyZN2Y5RG_t7kM3qVGHu5k4rekKGKreN7O7pdd7di-aF3x9sCendLLvDegEQTHD-AaLFf-x8aER8HXG8mAiTGWhjoizrHzt35J-SFHlfRWBYzBnfKE3hquZOX6jI8Ik"} alt={"A split-view professional photograph showing three distinct product domains: a sleek minimalist white consumer wearable, a complex stainless steel surgical instrument, and a heavy-duty industrial drone chassis. The lighting is crisp and editorial, highlighting the material textures and precision gaps. The overall style is high-end industrial minimalism with a cool, professional color palette."} className={"w-full h-full object-cover"} /><div className={"absolute inset-0 bg-primary/5"}></div></div></div></div></section>
    </>
  );
}
