import { StitchImage } from "@/components/ui/StitchImage";

export function HeroSection() {
  return (
    <>
      <section className={"relative h-[870px] overflow-hidden flex items-center bg-primary-container"}><div className={"absolute inset-0 z-0"}><StitchImage src={"https://lh3.googleusercontent.com/aida-public/AB6AXuDY2qw5uTkmlqis24_huntfvRrTBRH-tO-5pO599u0FjY0TyvoQMzDZdRCAvXucMC1qQ7VN2OnlnY4ZujsEz2CqoNY3LF0Pi4Suqu05eydyBV-EecrliS__n9db3pY1Hh6mvSZYiyuG6K07HESR6-5y-t2J_cTAwEd6FkelO2Z1jLiIpKw-cR-Px8KMUq4CgwvKpv0eGHPGgPPwC5QlkYsqZGyJ1lZABMoDib2pL6bprQNfPegM5ufVnhuZP8sbo0dBYiHHzyFddJA"} alt={"A futuristic high-speed transit pod shaped like a sleek silver needle accelerating through a glass vacuum tube. Technical data overlays, digital line work, and blueprints are superimposed over the scene. The lighting is cold, blue-toned, and high-tech, emphasizing industrial precision. Cinematic composition with a sense of immense speed and kinetic energy."} className={"w-full h-full object-cover opacity-50 grayscale contrast-125"} /><div className={"absolute inset-0 bg-gradient-to-r from-primary-container via-primary-container/40 to-transparent"}></div></div><div className={"relative z-10 px-margin-desktop max-w-container-max mx-auto w-full"}><div className={"max-w-3xl"}><div className={"flex items-center space-x-3 mb-6"}><span className={"w-12 h-[1px] bg-outline"}></span><span className={"font-label-sm text-label-sm text-on-primary-container tracking-widest uppercase"}>{"Project Case Study 041"}</span></div><h1 className={"font-display-lg text-display-lg text-white mb-8 leading-[1.05]"}>{"Hyperloop Beta:"}<br />{"Sub-Microsecond Validation"}</h1><p className={"font-body-lg text-body-lg text-on-primary-container/80 mb-10 max-w-xl"}>{"\n                        Engineered precision for the digital frontier. Validating high-speed transients where standard DAQ systems fail.\n                    "}</p><div className={"flex flex-wrap gap-4"}><div className={"flex items-center bg-white/5 border border-white/10 px-4 py-2 rounded-full backdrop-blur-md"}><span className={"font-label-sm text-label-sm text-white"}>{"FPGA Architecture"}</span></div><div className={"flex items-center bg-white/5 border border-white/10 px-4 py-2 rounded-full backdrop-blur-md"}><span className={"font-label-sm text-label-sm text-white"}>{"Bare-Metal C++"}</span></div><div className={"flex items-center bg-white/5 border border-white/10 px-4 py-2 rounded-full backdrop-blur-md"}><span className={"font-label-sm text-label-sm text-white"}>{"LoRaWAN Integration"}</span></div></div></div></div></section>
    </>
  );
}
