import { entry, type ExplicitContentMap } from "./types";

const adapter = "src/lib/cms/migration/adapters/explicit-content/case-studies.ts";
const action = (label: string, href: string) => ({ label, href });

export const caseStudyExplicitContent: ExplicitContentMap = {
  "hyperloop.validation": entry(adapter, "Hyperloop Beta Section JSX literals", { items: [{ value: "0.02Âµs", label: "Validation Latency" }, { value: "Sub-Âµs", label: "Sync Precision" }, { value: "1000km/h", label: "Max Velocity" }, { value: "12ch", label: "Simultaneous Channels" }] }),
  "hyperloop.constraints": entry(adapter, "Hyperloop Beta ProblemStatementSection JSX literals", { heading: "The Hardware Ceiling", introduction: "Standard DAQ systems were fundamentally too slow to capture high-frequency transients occurring during the transonic phase of the Hyperloop pod's journey. At 1000km/h, even millisecond-level jitter obscures critical structural integrity data, making flight safety verification impossible.", cards: [{ title: "Extreme Vibration", body: "Maintaining mechanical connection and signal integrity at peak acoustic resonance." }, { title: "Distributed Sync", body: "Zero-latency time-stamping across a 2km vacuum tube with no physical clock lines." }] }),
  "hyperloop.sensor-mesh": entry(adapter, "Hyperloop Beta AbstractArchitectureVisualizationSection JSX literals", { eyebrow: "The Innovation", heading: "Distributed Sensor Mesh with FPGA Core Validation", introduction: "We developed a custom distributed wireless sensor network utilizing Xilinx Artix-7 FPGA cores. By shifting signal processing from software to hardware logic, we achieved deterministic time-stamping at the point of ingestion.", nodes: [{ id: "timestamp", label: "FPGA-Based Time-Stamping", description: "Real-time logic execution for sub-microsecond event logging." }, { id: "firmware", label: "Bare-Metal Firmware", description: "C++ signal processing pipelines optimized for zero context switching." }, { id: "cloud", label: "Cloud Post-Run Ingestion", description: "Massive parallel ingestion for post-run forensic flight analysis." }, { id: "hub", label: "Node-Link Central Hub v2.1", annotation: "SYSTEM ARCHITECTURE" }], annotations: [{ label: "VALIDATED HARDWARE", value: "Xilinx Artix-7 100T Series; Ultra-Low Jitter Clocking" }] }),
  "hyperloop.outcomes": entry(adapter, "Hyperloop Beta Block2Section JSX literals", { heading: "Mission-Critical Outcomes", items: [{ value: "01", label: "Verifiable Flight Data", description: "Complete audit trails for every sub-microsecond transient captured during flight." }, { value: "02", label: "Safety Certification", description: "Empirical evidence required by regulatory bodies for high-speed transit safety protocols." }, { value: "03", label: "Risk Mitigation", description: "Early detection of structural fatigue through ultra-high frequency acoustic analysis." }] }),
  "hyperloop.review": entry(adapter, "Hyperloop Beta Block4Section JSX literals", { title: "Ready for Technical Review?", body: "Access the full anonymized telemetry data and structural validation reports from the Hyperloop Beta phase.", actions: [action("View Validation Reports", "/embedded-measurement-system")] }),
  "metropolis.solution": entry(adapter, "Metropolis EV Transit HardwareCardSection JSX literals", { heading: "The Engineering Solution", introduction: "A vertically integrated stack combining next-gen hardware with real-time cloud telemetry.", cards: [{ title: "Hardware Precision", body: "Liquid-cooled Silicon Carbide (SiC) power modules delivering 98.5% peak efficiency with ultra-compact footprints.", badges: ["SiC MOSFETs", "IP67 Enclosure"] }, { title: "Compliant Firmware", body: "Robust OCPP 2.0.1 communication stack running on NXP i.MX processors, enabling seamless V2G and ISO 15118 integration.", badges: ["OCPP CERTIFIED", "SECURE BOOT"] }, { title: "Fleet Telemetry", body: "Real-time monitoring of 500+ nodes, featuring predictive maintenance alerts and automated load shifting based on grid pricing.", metrics: [{ value: "30%", label: "Energy Savings" }, { value: "99.9%", label: "Uptime" }, { value: "500+", label: "Nodes Live" }], actions: [{ label: "EXPLORE PORTAL", action: "developer-controlled" }] }] }),
  "metropolis.system": entry(adapter, "Metropolis EV Transit SubstationSection JSX literals", { heading: "System Architecture", introduction: "A high-fidelity visualization of the power flow from the municipal substation through our Load Balancing Center to the bus terminal.", nodes: [{ id: "substation", label: "Substation", annotation: "11kV AC Input" }, { id: "hub", label: "Smart Hub", annotation: "CORE BALANCER" }, { id: "fleet", label: "Bus Fleet", annotation: "L3 DC Charging" }], edges: [{ from: "substation", to: "hub", label: "High Voltage" }, { from: "hub", to: "fleet", label: "Control Plane" }] }),
  "metropolis.tech-stack": entry(adapter, "Metropolis EV Transit Section JSX literals", { heading: "Technical Stack", items: [{ label: "NXP i.MX RT" }, { label: "Yocto Linux" }, { label: "SiC Technology" }, { label: "MQTT / TLS 1.3" }], benefits: ["Seamless transition to zero-emission transit.", "Optimized schedules via smart telemetry."], related: [{ title: "EV Infrastructure Phase II", body: "Residential V2G Solutions", href: "/ev-infrastructure" }, { title: "Smart Cities Core", body: "Grid Management Systems", href: "/smart-infrastructure" }] }),
  "metropolis.transit": entry(adapter, "Metropolis EV Transit Block2Section JSX literals", { title: "Ready to Engineer the Future of Transit?", body: "Connect with our team of infrastructure experts to discuss your fleet electrification roadmap.", actions: [action("Speak to an Infrastructure Expert", "/metropolis-ev-transit")] }),
  "nanolithography.challenge": entry(adapter, "Nanolithography ChallengeLeftSection JSX literals", { heading: "The Micro-Scale Challenge", introduction: "Environmental fluctuationsâ€”even those imperceptible to humansâ€”are the primary enemy of semiconductor yield. A single degree of temperature shift or a micron of vibration can ruin an entire wafer lot.", cards: [{ title: "Thermal Instability", body: "Uncontrolled thermal expansion warping lithography masks at 7nm nodes." }, { title: "Vibration Interference", body: "External mechanical hum affecting the sub-millimeter positioning of stepper motors." }, { title: "Active Compensation", body: "Real-time PID control loops processing 10,000 samples per second to counteract environmental drift." }], metrics: [{ value: "0.001K", label: "Thermal Stability Target" }, { value: "99.9%", label: "Uptime SLA Required" }] }),
  "nanolithography.solution": entry(adapter, "Nanolithography TechColumn1Section JSX literals", { heading: "The Solution Architecture", introduction: "A multi-zone environmental monitoring and active compensation system designed for the digital frontier.", nodes: [{ id: "hardware", label: "Hardware Layer", description: "Custom PCBs featuring 24-bit Sigma-Delta ADCs and ultra-low noise amplifiers paired with medical-grade platinum thermal probes." }, { id: "firmware", label: "Firmware Intelligence", description: "Predictive disturbance rejection algorithms implemented in C++, utilizing Kalman filters to anticipate external thermal shocks." }, { id: "cloud", label: "Cloud Orchestration", description: "Real-time environmental analytics dashboard with millisecond latency, providing a global view of cleanroom health." }, { id: "sensors", label: "Multi-Zone Array", annotation: "Sensors" }, { id: "controller", label: "Active PID Loop", annotation: "Controller" }, { id: "actuator", label: "Thermal Stabilizer", annotation: "Actuator" }], edges: [{ from: "sensors", to: "controller" }, { from: "controller", to: "actuator" }], legend: ["STM32 MCU", "24-bit Sigma-Delta", "EtherCAT"], annotations: [{ label: "Operational Logic", value: "Closed-Loop Stabilization Path" }] }),
  "nanolithography.results": entry(adapter, "Nanolithography Section JSX literals", { heading: "Engineering Results", items: [{ value: "12ms", label: "Response Time", description: "Critical system correction speed to thermal disturbance detection." }, { value: "+15%", label: "Wafer Yield Increase", description: "Direct correlation between environmental stability and product quality." }, { value: "-30%", label: "Energy Reduction", description: "Predictive cooling cycles reducing redundant HVAC waste." }], media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuDzCqBCzqpTHU2s__5snDY43d_FMwortYWz09D1GqCvaI5OX2bclTwbWzvI9W8p29HtaHpShWHeIFvK_BLSKWkK8iKYXaGKiFFal8iTOZLph9LEyzFLXVLIANtJT-IR-LRUvC9Lneg6ItJ5EwKExltCN00xh-r_6vjFDQAVh0jeEtimWg6PMzhOT__HtjIzrHTR-E_twQHFfWD1-cy7Z-S-3nO3OqxbLSQexBTvlPdFaALHMffcbtk6yVoJXA8jSEa5cIynCTJ0cEo" }, mediaAlt: "Engineering dashboard displaying real-time sensor data in a cleanroom facility." }),
  "nanolithography.stabilization": entry(adapter, "Nanolithography Block2Section JSX literals", { title: "Ready to Stabilize Your Operation?", body: "Bring industrial precision to your manufacturing floor with Mind Matrix custom control solutions.", actions: [action("Consult on Cleanroom Control", "/building-automation")] }),
};
