import { entry, type ExplicitContentMap } from "./types";

const adapter = "src/lib/cms/migration/adapters/explicit-content/industrial.ts";
const action = (label: string, href: string) => ({ label, href });

export const industrialExplicitContent: ExplicitContentMap = {
  "cognitive-core.performance": entry(adapter, "Cognitive core Section JSX literals", { items: [{ value: "< 100μs", label: "System Jitter", progress: 85 }, { value: "SIL3", label: "Safety Rating", progress: 100 }, { value: "+42%", label: "Production Gain", progress: 42 }] }),
  "cognitive-core.risks": entry(adapter, "TheProblemSection JSX literals", { heading: "Critical Latency Risks", introduction: "Standard operating systems, designed for general-purpose computing, introduce non-deterministic execution paths. In high-speed human-robot collaboration, even a millisecond of unexpected jitter can result in safety violations and catastrophic hardware collisions.", cards: [{ title: "Safety Criticality", body: "Achieving SIL3 safety certification for robotic interplay." }, { title: "Sub-μs Jitter", body: "Eliminating software-induced variability in motor control." }], quote: "Reliability is not a feature; it's the foundation." }),
  "cognitive-core.hardware-rtos": entry(adapter, "HardwareSection JSX literals", { eyebrow: "03 / THE SOLUTION", heading: "Hardware-Accelerated RTOS", body: "Custom deterministic processing stack.", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuAzBKlHbGcEJcV23pUaICDVqnLbtcrG96wbCUy24ONCFclbdjBqwvDL7NoMhBs8EK8LPqkH3NUD-7XTwQCFJ_nGChkKktxFw4sDJbpKaV41gaH1DSEnUDnZxpsupnCceBfsN1mgJmoHZs142roiBNiroEZAeiEKpvvzpeMyYbX82AXXPbC372qUcw-W4Smh3srPYtKduwNiTgiBiwF-_bb073HUz5oimInrX5e5Y7rbVyjehAZKdHS3FOGfGIowbWqZL9yv0xjzhf4" }, mediaAlt: "RISC-V industrial controller circuit board.", bullets: [{ title: "Hardware", body: "Custom RISC-V industrial controllers with hardware-level scheduling logic." }, { title: "Firmware", body: "Microkernel architecture featuring strict spatial isolation and MPU enforcement." }, { title: "Connectivity", body: "Digital twin synchronization via ultra-low latency MQTT brokers for fleet management." }], actions: [action("View Schematics", "/industrial-automation")] }),
  "cognitive-core.stack": entry(adapter, "VisualRepresentationOfArchitectureSection JSX literals", { heading: "Engineering Stack", introduction: "Architecture overview", nodes: [{ id: "application", label: "User Application" }, { id: "safety", label: "Safety Logic" }, { id: "microkernel", label: "Microkernel Isolation Layer" }, { id: "hal", label: "Hardware Abstraction (HAL)" }], annotations: [{ label: "PROCESSOR ARCHITECTURE", value: "RISC-V" }, { label: "REAL-TIME KERNEL", value: "FreeRTOS+" }, { label: "DATA PROTOCOL", value: "MQTT v5" }] }),
  "cognitive-core.optimization": entry(adapter, "Cognitive core Block2Section JSX literals", { title: "Ready to optimize your deterministic workload?", actions: [action("Request a Technical Deep-Dive", "/industrial-automation"), action("Download whitepaper", "/industrial-automation")] }),
  "building-automation.challenges": entry(adapter, "HvacSection JSX literals", {
    heading: "Structural Challenges", introduction: "Modern infrastructure faces critical friction points that bleed revenue and impact asset longevity.", cards: [
      { title: "HVAC Optimization", body: "Traditional systems operate on rigid schedules, failing to adapt to real-time occupancy and external climate shifts.", icon: "thermostat", badges: ["Reactive Load Balancing", "PID Loop Tuning"] },
      { title: "Occupant Comfort", body: "Static environments reduce productivity. Dynamic spaces require precise CO2, humidity, and lux level management.", icon: "groups", badges: ["Air Quality Indexing", "Human-Centric Lighting"] },
      { title: "Energy Waste", body: "Shadow consumption in vacant zones accounts for up to 40% of building overhead. Precision control is mandatory.", icon: "energy_savings_leaf", badges: ["Zero-Load Monitoring", "Grid Interaction"] },
    ],
  }),
  "building-automation.unified-architecture": entry(adapter, "ColumnLeftSection JSX literals", {
    heading: "The Unified Architecture", introduction: "Our hardware stack acts as a protocol-agnostic bridge between legacy field devices and modern cloud analytics.",
    nodes: [
      { id: "controllers", label: "KNX/BACnet Controllers", description: "Hardened edge gateways supporting bidirectional data flows for mission-critical facility management.", media: "https://lh3.googleusercontent.com/aida-public/AB6AXuDwpsc2pj2Lkt81b-rDUuzt9-4yJtjouSscmeYQTluuH60PgNzxNRGkGIedP-0GXjNdv1KHmphxo2Vap_AKaKVooyX3FjLEXLA6DzAEaPSC3Z6YHPhRH7n0dudD_ZHz50G9xaiMMy2ohVcVgBU-Hg6jX4lLCqXtpI3H07cfpyirXUFCuF0Dl0nJM57l6gtlj3eS_fnqgs92CqTYcsDJ9sSVcMRDtJLVS43ZzlEMuJElHYg2B9VYKQ9iD-v418JMbVbzqeRjI2b_y9o" },
      { id: "lighting", label: "Smart Lighting Drivers", description: "DALI-2 certified dimming engines with integrated power metering and predictive failure diagnostics.", media: "https://lh3.googleusercontent.com/aida-public/AB6AXuCLbNU6fe5EGod1821_OBUjNqf5xLLv8o5lF50HZIwRpu9-RRQNIk-YVri3z9KLPW9u1qwyaqgjNhDOPqf3-YqEZLwuPIDoCnI_zTCj8iGLW-HbK2-1HI6a0rX0LE6dnzs8N-AmVuc0xbnRoR2VuBfXrXj2aJY5y_n8VjWqWK4_NUeoKzhR0LrBp55uVi9liD-g8xW7amHP6yhXwMRBsyvbHXTJvyvuilQJ-TOIX97EYNaFN0SQ---a09yiFmjAU1dWEHkFdD6JsEU" },
      { id: "air-quality", label: "Air Quality Networks", description: "Distributed sensor meshes monitoring CO2, PM2.5, and TVOC levels to drive demand-controlled ventilation.", bullets: ["Ultra-Low-Power Sensing", "Protocol Conversion Mesh"] },
    ],
    annotations: [{ value: "99.9%", label: "Uptime Reliability" }, { value: "-28%", label: "Energy Reduction" }],
  }),
  "building-automation.protocols": entry(adapter, "Building automation Section JSX literals", { heading: "Connectivity Standard", items: ["BACnet", "Zigbee", "Thread", "MQTT", "KNX"].map((label) => ({ label })) }),
  "building-automation.cognitive-core": entry(adapter, "Building automation Block2Section JSX literals", {
    eyebrow: "CASE STUDY", heading: "Cognitive Core OS", body: "How we deployed a decentralized building operating system for a 72-story global headquarters, achieving autonomous HVAC adjustment based on occupancy heat maps.",
    media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4Lg_4ukR_oggtROwxnLShuBXY7HzRd2VP1et3DdGi6L7c8Qqm2j-sSGaok2E-yi54ql5KFh83TP7gdqgwKKpovQAh8YRIAxrMNOFLGGgwCGQlEzFscrxByo_OT2AzevtWEVwF6Pr3lVeHMIf6UjhUtHLtXH1qJZOO3Ex9pSc2a-4c93rAzrTC6Ef3apx7vRWKQoz4kTb10TIZEK32fFDejaxkCzRh-9f4ixTZ7PJ86bTRU6wuCzcfOAZdM890wvEiucYSVgR63_g" }, mediaAlt: "Dashboard interface showing real-time 3D heat maps of a building floor plan.",
    bullets: [{ title: "Impact", body: "Reduced peak load energy consumption by 42% in the first quarter." }, { title: "Engineering", body: "Ultra-low-power sensing mesh with 5-year battery life nodes." }], actions: [action("Read Documentation", "/cognitive-core-os")],
  }),
  "building-automation.future": entry(adapter, "Building automation Block3Section JSX literals", { title: "Ready to Engineer the Future of Urban Infrastructure?", body: "Join leading architectural firms and property developers in building a more efficient, responsive world.", actions: [action("Build Smarter Now", "/cognitive-core-os"), action("Talk to an Engineer", "/cognitive-core-os")] }),
  "wsn.overview": entry(adapter, "Wireless sensor network Section JSX literals", {
    title: "Technical Overview", body: "Engineering reliability into every packet. Our WSN solution provides an immutable foundation for critical data acquisition.",
    items: [{ title: "Heterogeneous Mesh Architecture", body: "Unlike standard star topologies, our self-healing mesh enables nodes to dynamically reroute data through neighboring devices if a path is obstructed. This creates a resilient living network that adapts to industrial structural changes in real-time." }, { value: "99.99%", label: "Uptime Reliability", quote: "The benchmark for mission-critical environmental tracking." }, { title: "5-Year Lifespan", body: "Optimized power management protocols for battery-operated remote nodes." }, { title: "AES-128 Encryption", body: "Military-grade hardware security modules at the chip level." }, { title: "Sub-GHz Range", body: "Superior penetration through thick concrete and steel reinforcement." }],
  }),
  "wsn.topology": entry(adapter, "EndNodesSection JSX literals", {
    heading: "Gateway-to-Node Topology", introduction: "Our architecture leverages a multi-tier hierarchy to ensure zero data loss and maximum scalability across large geographic footprints.",
    nodes: [{ id: "node-1", label: "Node Tier 01", description: "BLE / LoRa Client", group: "Distributed Sensors" }, { id: "node-2", label: "Node Tier 02", description: "BLE / LoRa Client", group: "Distributed Sensors" }, { id: "node-3", label: "Node Tier 03", description: "BLE / LoRa Client", group: "Distributed Sensors" }, { id: "gateway", label: "SMART GATEWAY", description: "Edge Processing", protocols: ["MQTT", "HTTPS", "COAP"] }, { id: "analytics", label: "DATA ANALYTICS", group: "Enterprise Layer" }, { id: "control", label: "CENTRAL CONTROL", group: "Enterprise Layer" }],
    edges: [{ from: "node-1", to: "gateway" }, { from: "node-2", to: "gateway" }, { from: "node-3", to: "gateway" }, { from: "gateway", to: "analytics" }, { from: "gateway", to: "control" }],
  }),
  "wsn.standards": entry(adapter, "Wireless sensor network Block2Section JSX literals", {
    heading: "Built with Leading-Edge Industrial Standards", items: [{ label: "LoRaWAN™ 1.1" }, { label: "Nordic nRF52" }, { label: "BLE 5.3 Mesh" }, { label: "ARM Cortex-M4" }, { label: "Ultra-Low Power", description: "Deep sleep modes consume less than 2μA, allowing decades of operation on a single primary cell." }, { label: "Self-Healing", description: "Automatic network reorganization ensures continuity during hardware failures or signal interference." }, { label: "Zero-Touch", description: "Auto-provisioning nodes for rapid field deployment without manual configuration overhead." }, { label: "Over-the-Air", description: "Secure multicasting for firmware updates (FOTA) across thousands of nodes simultaneously." }],
  }),
  "wsn.applications": entry(adapter, "Wireless sensor network Block3Section JSX literals", {
    heading: "Strategic Applications", introduction: "From precision agriculture to urban infrastructure, our WSN technology powers the data-driven future.", actions: [action("View All Case Studies", "/environmental-monitoring")],
    cards: [{ eyebrow: "Public Infrastructure", title: "Smart Cities & Lighting", body: "Intelligent sensor networks for traffic management, parking optimization, and energy-efficient street lighting.", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuDKRWQk96tnwTI7Vqbt0dgx28rIhBSPukwwL4lQzsyHniSFueMtesOLDIE_3NvwxrsfjVjq7d1Jofwim5QYpwpb-wFuTF5Ww83oDIM1ZArl5kD9JNrOgiis6B1aBemO_R5njBtiN0DR7gCnVuiU5MvGULlpx_EPh1f8LxFKwbbuBfXplLk8aHkoowp0h8mlXyjeukbPa8bSb2dBaNnh9YbMe5SLtPaLK4O_zIV2YLBwkX2AYwDAhPCrKsn38Uo_1yWQ-lPMemElJSQ" } }, { eyebrow: "Scientific Research", title: "Environmental Monitoring", body: "Precision tracking of air quality, soil moisture, and water levels across vast, remote ecological zones.", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuDaTSG4Y6lkUAaEgQIij0uXWYFDU1h-4O1d2210ej65DfWy3Py0jcGe84z_P5312LEMFmk2py2lF1cjpHJTGgwXMZ87btbAb6eDtHfuo0d5Iby5cfmY_Z9m03ycJqC3Qi5Xg7ehcXgX6cEco7zjKoSY-agfSEC2ERROynO8z6NDkYpFK0F9ZP_IifvfUWQsiukGw3jTcev1VGn8SlkVKIH_8vddKqhz-DAXi8M4NNBypzOFTxrwTATcu4Lw8-TPrPlkpJwRse8R-P4" } }],
  }),
  "wsn.strategy": entry(adapter, "SubtleBackgroundDecorationSection content; decoration excluded", {
    title: "Ready to Engineer Your Connectivity Strategy?", body: "Our engineers are ready to assist with your mesh network architecture design, hardware selection, and deployment roadmap.", actions: [action("Schedule Technical Review", "/request-consultation"), action("Contact Sales", "/contact-us")],
    media: ["https://lh3.googleusercontent.com/aida-public/AB6AXuBlQDy9u3c4RZYIxy3ETCxpLjEPZHKvDh-OFDc9lXmpBrw--NlvIgzTk1bDhRIFbxxOR7ih1g1oeXTh0iVg9iJPSoRsuPhTR5akXoKpT0NgT8Eecclz_7goZABRwEmpTUEHznKYSsfe_yCz2aga6Ty4zAOk1kemeR_PMaHW6E2LVuEYqJ41aNUV17CIwGTGTg3XxcDUQWG_aBxCZHWTzAeuCeWhMvgA7dm76yQX8GwHq-cC8JKMWPzseM6cJZAWPtrGH0fFg8eotYU", "https://lh3.googleusercontent.com/aida-public/AB6AXuBvjjzo8d8lTxlyqxJvp5hHYNzKNCxFsOcEdsksdej0V7vGRb03cRoZz4b7ErhDhxu0peXNFem_symKCA_gMQSuGBCne7c4EVod_btTo2ST3XjSJRtkwRjp2pkK-bliii3cMY6_7M7eH9RSk0H88w3l59FOEFpwWODIqGMCrkDnE_9mxKyy7f59os41xGd658IsCPWKKdcsLlapFwDcZPJw3G0RX2N6c0OtFCUMFdipLXYAtrLtC5A7yV3TABdG7-kOZBxEbFQO1ag", "https://lh3.googleusercontent.com/aida-public/AB6AXuB2l4EKmLnm6FmUUnOiT2B9d3KMnOKHXJ12g1ZoCjM-P7fvWL3BBEZrPJDtkQaCl-6uEDXqr3FE7XQvYi0_5kqN-W8BABmF2leqcsL1mi8LCy43NjN_zKOWpba_VC2Uza9CGWnDGGvhYahrabEzV1e1m4g6r2IVvLsYXKWi5fRpMfODLpOJIc4-DvpoTTJwgQ-77XtZ8PXHXKMlpRnB57yO_tbwChU3-GUIeitsJjunZNbodiobwRTRZCa7NlBxigC-vaWayi1IIrA"].map((source) => ({ source, alt: "Partner" })),
  }),
  "connectivity.capabilities": entry(adapter, "LargeFeatureCardSection JSX literals", {
    heading: "Core Capabilities", introduction: "Optimizing the delicate balance between range, data throughput, and power conservation.",
    cards: [
      { title: "LPWAN Mastery", body: "Proprietary long-range wide-area network engineering achieving up to 15km line-of-sight range with 10+ year battery lifecycle.", metrics: [{ value: "15km+", label: "MAX RANGE (LoS)" }, { value: "2.4μA", label: "DEEP SLEEP CURRENT" }] },
      { title: "Self-Healing Mesh", body: "Advanced BLE and Zigbee mesh implementations that reroute data dynamically when nodes fail.", icon: "hub" },
      { title: "Spectral Analysis", body: "Real-time environment noise monitoring to ensure carrier-grade reliability in dense urban sectors." },
      { title: "Zero-Touch Provisioning", body: "Automated secure onboarding for thousands of sensors via NFC and QR-linked hardware certificates." },
      { title: "Protocol Translation", body: "Edge gateways that unify diverse wireless standards into a single, cohesive MQTT/AMQP data stream." },
    ],
  }),
  "connectivity.rf-design": entry(adapter, "Connectivity Section JSX literals", {
    heading: "Antenna Design & RF Precision",
    body: "Our labs feature state-of-the-art anechoic chambers where we simulate complex RF environments. We don't just use off-the-shelf modules; we design custom PCB trace antennas and evaluate SAR and TRP/TIS metrics to ensure certification-ready hardware from day one.",
    media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuD6CxLSCglVzBkLl2qTm_eeFkIF2_oj3eGJFju2jD17YQAOu3-ez1nf4D0cSSYdDk1ydDKlGPBTeSzvkWgR_CaYoIQID1ceRh_K_QcwOq64gRIHA1yzXB0kidAqGE0uPcXiBHpwWLYwFLIfe7cnBTYmqY9y8Ajg2HN6kh1Wr94jajB_-RXunLaA1eakoJmfI2nm9qg6y-YSOJxyZjE1BI9GEz8o84SkchimNqg7ewurs84b3zn4t-qinf_nAdZ5TuNGgoeVtzLerxM" },
    mediaAlt: "Technical visualization of the RF radiation pattern of a custom antenna.",
    background: {
      source: "https://lh3.googleusercontent.com/aida-public/AB6AXuDm_gk3Ft_CJxwS7yp2oU6zGj7PpYhILPeBb9LYGe8mXzYXhitAuqWQE1jhmbE6EDgqOUJbaRhOnJ87LbtgZCW-4_5uAO_AM2ZGAscqIYZj5WBiBy-SXJ0PvTurkrJDUYov9p1H36_ukNE49ONVLgSeDNkLThWErCAcqfjoTRqxfFWnq3ck16tRdEmF0m68pZSZchECMJBVLnNFe2LsHHzclXJMSTPvGxdzbWAjrCJmlTy3Hcw84mVEedm73m4wLGbYwqC-OgsyrbA",
    },
    cards: [
      { title: "FCC/CE/IC Pre-Certification", body: "Mitigating compliance risk through early-stage emissions testing.", icon: "verified" },
      { title: "Impedance Matching", body: "Maximizing power transfer to antennas to extend range without increasing battery drain.", icon: "settings_input_antenna" },
    ],
  }),
  "connectivity.deployments": entry(adapter, "App1Section JSX literals", {
    heading: "Industrial Deployment", introduction: "Proven solutions for mission-critical connectivity across the digital frontier.",
    cards: [
      { eyebrow: "Smart Grid", title: "Utility Monitoring", body: "LoRaWAN-based grid health monitoring across thousands of square miles with zero dependency on cellular networks.", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-4dVTPtJxL_OQmDMll9e6aMKrc5GVxrLewHR_QVIe9k3Ua49pWqZ2IQiGqhx0jatpK3sj5zuYYmIsP0EBDNdZrOdfC1d_6qrN0VqoFAVpLbL8x8au_NwUs-iF5DefVLADE-reQQFJLfnmDGkux-VpTK42olhk1DFw2fzGWo5FN25Z_keNiQ3w45mDECkBDD4v6ZByOpjdwNEhBLt2H9tSGWemolZlUWWfgmb6VHgtPv3XSBQjZ33vkC5hI2U5xvF4HxRqMq4espw" }, mediaAlt: "Large solar farm in a desert landscape monitored by sensor nodes." },
      { eyebrow: "Industry 4.0", title: "Automated Factory Floor", body: "Ultra-low latency Wi-Fi 6 and 5G private network integration for high-speed synchronized robotics.", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuCx2A6jGFq1-VYARTsBC2vmx3HTO9chjWFRq2j1rTfyUEcsc8XO66glAcsrSyun3EKzvCgECB0lyk3NXSn9P7Hn57lwD6_XSMiCfL7yjWlKJqfj05jHaHL_Sqy0mk22Wuxh105vGrqKCoMzDDhjTBojsOduqes-cEC5lTczmgEey3L6M3UL9SMtwBXxGqre8Bodj5bjfE79YS8k2Qlt7EdAYUUdH19lehgXtidaRm1elkTbYdvjefr-NtZK6ztkmrQ25dwF9LPMg-E" }, mediaAlt: "Highly automated smart factory with wireless connectivity between machines." },
    ],
  }),
  "connectivity.performance": entry(adapter, "Connectivity Block2Section JSX literals", {
    items: [{ value: "99.9%", label: "Uptime Reliability", description: "Through redundant mesh topology and carrier-grade hardware selection." }, { value: "-40%", label: "Energy Reduction", description: "Optimized sleep-cycle protocols that extend maintenance intervals for field devices." }, { value: "AES-256", label: "End-to-End Security", description: "Military-grade hardware encryption at the silicon level for every transmitted packet." }],
  }),
  "connectivity.strategy": entry(adapter, "Connectivity Block3Section JSX literals", {
    title: "Bridge the Connectivity Gap.", body: "Consult with our RF engineering team to architect a robust wireless infrastructure tailored for your industrial environment.", actions: [action("Schedule an Engineering Review", "/connectivity")],
  }),
  "industrial-controller.architecture": entry(adapter, "ProcessingCoreSection JSX literals", {
    heading: "High-Precision Architecture", introduction: "Designed with a decoupled core strategy to ensure total I/O isolation and zero-fail processing safety.",
    cards: [
      { title: "Decoupled Processing Core", body: "Dual-core RISC-V architecture separating real-time tasks from HMI processing, ensuring deterministic execution of critical control loops.", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuAUOAOcCFEyc-B8rpSaicuphGlI7NS_TiPacYfRC51v0PFHzPnUhiwVyM75RroyTQLaab2qhfc4nA7poFdVThg3HsCn0i8-rzDloIZIGLelrMv4WQ-P2k4Hy0PAd3klD3fhck6GtzaJayFferE1agrqT6Rzft21hnvkeBzViU5xcAEzypNVTZQhHRA4FnvnjznVEAd7bENkGFYpSSXCwdxUsDqDFt87LlN_yo06e9FCouObpK4URU_eS5FbhBQNAgQOMeHzPOG0rxI" }, mediaAlt: "High-performance industrial microprocessor mounted on a PCB." },
      { title: "Galvanic I/O Isolation", body: "Protects critical logic from surges and electrical noise. Tested for 4kV transient immunity in heavy industrial environments." },
      { title: "Cycle Time", body: "Sustained performance under full I/O load.", value: "0.5ms" },
      { title: "Functional Safety SIL3", body: "Integrated safety logic certified for human-robot collaboration zones.", value: "3" },
    ],
  }),
  "industrial-controller.connectivity": entry(adapter, "Industrial controller Section JSX literals", {
    heading: "Universal Connectivity", introduction: "Seamlessly integrate with existing factory infrastructure through native support for industry-standard fieldbus protocols.",
    items: [{ label: "ETHERCAT" }, { label: "PROFINET" }, { label: "OPC UA" }, { label: "Robotics", description: "6-axis synchronous motion control with sub-millisecond precision." }, { label: "Assembly", description: "High-speed sorting and vision-guided placement synchronization." }, { label: "Packaging", description: "Integrated servo-drive control for multi-lane high-volume systems." }, { label: "Process", description: "Precise PID loop management for temperature and flow control." }],
  }),
  "industrial-controller.upgrade": entry(adapter, "SubtleTechBackgroundEffectSection JSX literals", {
    eyebrow: "Ready to Upgrade?", title: "Engineering the future of autonomous systems.",
    actions: [{ label: "Request a Demo", action: "request-demo" }, { label: "Talk to an Engineer", action: "contact-engineer" }],
    media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuAPp_dNdKTy91_TMF05JIxwmsrJ8jeZjWGjx63HjoYiXUazl-ycSxRpM4Vqynmk9k8nHNgHpYOPU9LsvdVI-oYFJx6EfUTvvJFOOuTVh45Qi5hGD-SoHHDOm8bnalQyQpv2592d3VK_zLNrTSgRN9Yf76DfRgtrMG4RGE3n9o0Eya2imhXUJoF1f3OZ_ohpiDHoN9jArgx--Tfb9JLXm_zErsWUGZQV-OjoAVZ3yf1bx60hCc-sESqkyg6s1TeQf0GH2mZUriZOVVI" },
    mediaAlt: "Modern automated assembly line with articulated robot arms.",
  }),
  "iiot.node-to-insight": entry(adapter, "Step1Section JSX literals", {
    eyebrow: "Architecture", heading: "From Node to Insight",
    steps: [{ title: "Ingestion", body: "Protocols like Modbus, OPC UA, and BACnet are translated into uniform telemetry streams." }, { title: "Edge Gate", body: "Industrial-grade gateways perform local filtering, security encryption, and protocol conversion." }, { title: "Transmission", body: "Secure MQTT or LoRaWAN tunnels deliver packets to the Mind Matrix cloud infrastructure." }, { title: "Visualization", body: "Real-time dashboards and digital twins provide actionable insights for decision makers." }],
  }),
  "iiot.capabilities": entry(adapter, "SensorIntegrationSection JSX literals", {
    heading: "Core IIoT Capabilities", introduction: "Our modular architecture adapts to existing infrastructures, providing a unified data layer for complex industrial environments.",
    cards: [
      { title: "Universal Sensor Integration", body: "Hardware-agnostic connectivity for legacy and modern instrumentation. We normalize data from thousands of endpoints into a single, high-fidelity stream.", icon: "sensors", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuAJTGhzKMkTwnuq7MTgI4usRHqR_-fgnBGjd6iW3mjvVIbTOcZO69MALILsBvLNB14QoidTX2Mt-UlFikus-cAqhVBA5dqhmLd9VGzA752EiDS_hlakjilDb-A3RyMsbBNOXa92BTUW-tD9jFwYSLhzIqEWFLe1HAs_gBDXIzMnN-pW5PXKIzlEcHIOA41lgeOewbSGrR7jOxu8iwH27LL6qj6rCFPHqKQVMvq-UXDTk-XAAIUI7iFlNBvIPfZ_mY0QRRX3Z5PVs2A" } },
      { title: "Edge Intelligence", body: "Real-time processing at the source. Minimize latency and bandwidth by executing ML models directly on industrial gateways.", items: ["Sub-ms Latency Control", "Local Data Persistence", "Edge Orchestration"] },
      { title: "Predictive Analysis", body: "Zero-downtime operations through AI-driven failure prediction and health monitoring for rotating equipment and thermal assets." },
      { title: "Next-Gen HMI & SCADA", body: "Modernized human-machine interfaces that prioritize cognitive load reduction and situational awareness for control room operators.", link: action("Explore Interface Designs", "/manufacturing") },
    ],
  }),
  "iiot.ecosystem": entry(adapter, "Industrial IoT solutions Section JSX literals", { heading: "Our Technology Ecosystem", introduction: "We integrate with industry-standard protocols and cloud providers to ensure your IIoT stack is future-proof and scalable.", items: [{ label: "AWS IoT", icon: "cloud" }, { label: "Azure IoT", icon: "hub" }, { label: "LoRaWAN", icon: "router" }, { label: "MQTT 5.0", icon: "swap_calls" }, { label: "Rugged Gateways", description: "IP67-rated hardware designed for extreme temperatures and high-vibration environments." }, { label: "Cloud Dashboards", description: "Enterprise-scale visualization with multi-tenant support and granular RBAC security." }] }),
  "iiot.advantages": entry(adapter, "Industrial IoT solutions Block2Section JSX literals", { heading: "The Industrial Advantage", introduction: "Beyond simple connectivity, Mind Matrix delivers tangible operational excellence and measurable ROI through deep domain expertise.", items: [{ value: "24% Increase", label: "Equipment Effectiveness", description: "Average increase in overall equipment effectiveness (OEE) within the first 12 months." }, { value: "Zero-Downtime", label: "Predictive Operations", description: "Achieved through proactive sensor monitoring and predictive maintenance algorithms." }, { value: "Secure-by-Design", label: "Edge Security", description: "End-to-end TLS 1.3 encryption and hardware-level root of trust for all connected devices." }] }),
  "iiot.verticals": entry(adapter, "Industrial IoT solutions Block3Section JSX literals", { heading: "Vertical Specializations", introduction: "Precision solutions tailored for high-stakes industrial sectors.", cards: [{ title: "Manufacturing", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuBWtbt7-HgiL9KAuqUBFLLNzjVfJgYcyAwpAUaZVKrqYW138DR9t3gIAh0IT6KLW94WvdKFVoohR03P3gYoXQHS2KEhpllwRujF4vlLaiO2bEFQpjOIy5mb1LLKjS8-SoDoGt3GGB2vR0mk8mcihqQDuyDooOmb6qkd5f0GfNvhkc-A9ybn1E_36p_Th0FxpEKNP8i7QtPvHlu_maXxc_2xKHbSTFYourOkvS_tAEYZMyC7EtvXLbQU89SOiJcTWQiXs_qrD4jtmFI" }, mediaAlt: "Precision manufacturing facility with CNC machines and automated carts." }, { title: "Energy & Utilities", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuDFnRfgGaCyY9hMeQXu7qPGI_sEgsMx6kyQ_4txl325kbbAYUgaZ4rhUbKFWm09ASiAzE0xJoOMtzaozf0sKwPJUXiQyDg0DRX4G1WGSz7LV1Ty7uIV-9Q1T-XsNeooGunXQHuK0Y_BZaG5_7XEtBNRrGe2JLXKJ_PzyesYHvGloxeallAEM8qVgo3RnaFJKU2ilrPJEzDc5LIfb7DvghAZW6JeWrZ77FIlJ-HMtZSWvFCOdVHLYr1Q5uay7zBJBv6AMv0vxe7nyzQ" }, mediaAlt: "Offshore wind farm at dusk." }, { title: "Chemicals", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuB3LbJLCw1sWLkwhd507KWpAFB-1v0Jk-O89QutG7dnWwnGl0wdoxceXTZKEUEFIZwGHNJ5-6axymT71yO3IpmsQVu6rCcbLMTJnkpCr6esDAWhTxA126gp94SRc5JPQzo_LVObFv6U_qrMXHqV3M_Sl1iGMRiU473A5aQXkLdZywvCLnnQpbMqIAUKC8Dx70R0ruK_M8QXyZ0pakViUFW19Qhtx22AvlrKo9J6trJyyhYTyrU8xAG773WHQ6CEKdl9gsbyguuREFQ" }, mediaAlt: "Chemical processing plant at night." }, { title: "Logistics", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuCnbT9PQJcdE_RI7PJ6L0kYedzZz0d37bycW_dDY8MdUpMk8pXquCVUjShIcfYwcKHuR2c_2bXoIQRqDoLDTZ5v_5R686JrVD6W4-dpoIaU4v_eIxs5KuzoVhDlQDtJ7UXaCVjwDV009NE_S7kR7zgr4ctX8T-rqqViNwzG1nYcZyymLOSWenzRLfKCUnTF7zu80OysLJjq6vpFYUNFGXJiy2KVideTgv_cuf7d4FjhPzzA720GxYVZRI__WF5riAthDbIJI1kVTK8" }, mediaAlt: "Automated logistics warehouse with high-speed sorting systems." }], actions: [action("Explore All Sectors", "/manufacturing")] }),
  "iiot.technical-faq": entry(adapter, "Industrial IoT solutions Block4Section JSX literals", { heading: "Technical FAQ", items: [{ question: "How do you handle legacy machinery integration?", answer: "We utilize multi-protocol industrial gateways that support legacy serial connections (RS-232/485) and standard industrial protocols like Modbus and PROFIBUS, wrapping them in modern encrypted packets for cloud transmission." }, { question: "What security standards does Mind Matrix follow?", answer: "Our architecture is built on ISA/IEC 62443 standards. We implement network segmentation, hardware-based encryption (TPM), and continuous vulnerability monitoring across the entire edge-to-cloud pipeline." }, { question: "Does the solution work offline?", answer: "Yes. Our edge computing layer includes local data persistence and autonomous decision-making capabilities. If cloud connectivity is lost, the edge node continues to operate and syncs data once the connection is restored." }] }),
  "iiot.modernization": entry(adapter, "Industrial IoT solutions Block5Section JSX literals", { title: "Ready to Modernize Your Operations?", body: "Schedule a technical deep-dive with our engineering team to map your path to Industrial 4.0.", actions: [action("Book a Consultation", "/manufacturing"), action("Download Technical Spec", "/manufacturing")] }),
  "solutions.solution-catalog": entry(adapter, "SolutionCardIiotGatewaySection JSX literals", {
    heading: "Solution Catalog", cards: [
      { badge: "IOT-01G", title: "Industrial IoT Gateway", body: "A ruggedized, edge-computing hub designed for extreme industrial environments. It provides real-time data processing, protocol translation, and secure cloud tunneling for legacy machinery.", items: ["Edge Logic Processing", "IP67 Ruggedized Chassis", "Multi-protocol Support", "Oil & Gas Monitoring", "Smart Factory Control"], link: action("VIEW DATASHEET", "/iot") },
      { title: "Battery Management Systems", body: "High-voltage BMS for utility-scale energy storage. Featuring sub-millisecond cell balancing and advanced thermal monitoring algorithms.", items: ["State of Health accuracy: ±0.5%", "Active Cell Balancing", "CAN Bus Interface"] },
      { eyebrow: "Power Electronics", title: "EV Charger Systems", body: "Integrated power conversion modules for Level 3 DC fast chargers. Compact design with 98.5% efficiency ratings.", badges: ["SiC Technology", "Liquid Cooled", "350kW Ready"], media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuB_2Tw7wua5RJ-wfQy6A60lv3qTcjUOPmdrKcznK615vy8xFd7DGY2SyUicaxXXD84qYGY0TJfFQKWTKXfgiVG-qEsaZPm_fj7VfujNLy5uO-gtJXYWWjYrpdPvMbvBwBWyLovTxCqX2w3fPnSRhZbACdKm9_qBF7Fl2zoWPyPZ3fy06hX-SMKK5vlraWFTUeCKTtSaJkEqyWHeIJ3wMCh1wuooGdUXIBLF_-MrGcFgykKftk7fte3uyVSNLpPJLCNRd7pm_0jf3bQ" } },
      { eyebrow: "Digital Twin", title: "Global Asset Tracking", body: "Satellite-linked telemetry for remote industrial assets. Monitor heavy machinery anywhere on the globe with 5-meter precision and 10-year battery life.", coordinates: "34.0522° N, 118.2437° W", actions: [action("Request Demo", "/iot"), action("Details", "/iot")] },
    ],
  }),
  "solutions.technical-inquiry": entry(adapter, "BackgroundTechLinesAnimationPlaceholderSection content; form mechanics excluded", {
    title: "Scale your vision with Matrix-Core Systems.", body: "Our modular architecture allows for rapid prototyping and deployment without sacrificing the industrial rigor required for mass production.",
    actions: [action("Send Technical Brief", "/iot")],
    callouts: [{ title: "Certified Hardware", body: "UL / CE / FCC COMPLIANT", icon: "verified" }, { title: "Encrypted Edge", body: "AES-256 BIT SECURITY", icon: "security" }, { title: "Technical Inquiry", options: ["Industrial IoT", "Battery Management", "EV Power Systems"] }],
  }),
  "smart-infrastructure.challenges": entry(adapter, "Smart infrastructure Challenge1Section JSX literals", { heading: "Critical Challenges", cards: [{ title: "Structural Health Monitoring", body: "Legacy infrastructure suffers from hidden degradation. Our high-precision vibration sensors and strain gauges detect micro-fractures in real-time, preventing catastrophic failure through predictive edge modeling.", badges: ["0.01mm Precision", "Edge Inference"] }, { title: "Public Safety", body: "Integrating encrypted mesh networks for emergency response systems and low-latency surveillance protocols in dense urban corridors.", label: "99.999% Uptime SLA" }, { title: "Traffic Flow Optimization", body: "Reducing gridlock through autonomous traffic controllers that adapt signal patterns in real-time based on high-reliability mesh sensor data." }] }),
  "smart-infrastructure.solutions": entry(adapter, "Smart infrastructure Solution1Section JSX literals", { eyebrow: "Precision Solutions", heading: "Industrial-Grade Ecosystem", cards: [{ title: "Vibration Sensors", body: "Sub-hertz frequency detection with on-device spectral analysis for bridges and high-rise structural integrity.", badges: ["IP68 Rated Housing", "10-Year Battery Life"], media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuDCjPcwWFhjvzgp5jfJDYYGSiSfuzlTpZTpb48YGE-O288wdqSGgRFVF_aBYzofX9Jk3dqDUewKaKSu45Frdw_xcp9bUbWW7prkMhOrt_1an8rKErSVWNZFMn5-GuxWOE2HAbsb-eu1w9Yoo1VLUNz8T8Vh36AtkWknmZTpwhGem3115bRs4Q61zmLu3t71Ik1ih_HZeFj6f9s9kzYXEA88r-8xjSLmJ0U3kX-lREbBXYrvxKXVXI1rnErTFOzQuNwULFbFv0iNFP4" }, mediaAlt: "Ruggedized industrial vibration sensor in a machined metal housing." }, { title: "Autonomous Controllers", body: "Multi-protocol gateways featuring Edge AI for localized decision making without cloud dependency.", badges: ["LTE Cat-M / 5G Ready", "Hardware Root-of-Trust"], media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-hOUMIdEZ8OsqT7wm9GA32K1PcVSgnvY7_7FKu3n7iPP0TCPzcRJ9_nnkbLRNgYcXsC_8gx6dq7N-HQMNWs9A01IMoMM2159zTDZ2h6qVlGpmmZeTTooNBHwioAYtXsOabb2jdBTwzX3ZGz2NII1puoVgYCbF0wqn9WWghCpx1zLZebDUcRTuHUrjrG0qXy55dojWK2XXq60-2l3LXuf9mpGJc30GYr_kjWG1hSZgo6Py1W9ZOxcwqJr7saxTo-oJ1B-WJX1OIXU" }, mediaAlt: "Autonomous traffic-controller unit with status lights and high-speed connections." }, { title: "Mesh Lighting", body: "Dynamic luminaires that act as Wi-SUN mesh repeaters, providing city-wide network coverage.", badges: ["Wi-SUN Certified Mesh", "Energy Demand Response"], media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuBBfzbCB26ejimVCmHW9rICavkSnTeM8AAZ-Dp3SFjUpQYKrnLpSTeTM4HnFx-0igCYGWvdJ1t1gypFjIfxFyAZ2OtnEeNso84B1SPKYWV84i0KhcTgV2fkCUozL4g6a5njjHRhP5hCDlR4Br-UvQqLAU8sSIfxcvZVCYL1Fk9sR4keHjgPglmSq2maltSDFKzHwh1bVjAWYXWWZxrtUt2olG2teTcq5O7IOelbmW3PybYSepXsfyjcOmqzlK6ocpe22JU_IwGeXtY" }, mediaAlt: "Mesh-connected street lighting along a waterfront promenade." }] }),
  "smart-infrastructure.expertise": entry(adapter, "Smart infrastructure Section JSX literals", { heading: "Engineering Expertise", introduction: "We deliver ruggedized hardware and high-security firmware built for the most demanding physical environments.", cards: [{ title: "Ruggedized Design", body: "-40Â°C to +85Â°C operating range with EMI shielding." }, { title: "High-Security Firmware", body: "AES-256 encrypted updates and secure boot protocols." }, { title: "Wi-SUN", body: "Long Range Mesh" }, { title: "LTE-M", body: "Global Cellular" }, { title: "Edge AI", body: "Neural Processing" }, { title: "Mesh", body: "Self-Healing" }, { title: "Architecture Visualization", body: "High-reliability mesh architecture for 100k+ connected nodes.", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuC6ltggC6V-dfXfNZwXo4mbPnflf1hP7jNUCZhMwKsQZdBr8g-xM-0qOlCMpXFzZKqwVheMdvtSY1bgijsRFo8OOkE4V-2Zzg4egH1D24vsRAFh5BxMCdQullJKPM823E5IyWke9OR71BEvZ6EnrWbRKC2UFxUyix6z3Md6LhQZkjkqmhGdO9WFCqWUwz1tBUP9YG624MIj16SGKcrJYhKI8qlyZxaTbdQf3gwx1nUOaEKpG-GeYf3OyKgdm3SicPYkNNDS4wcjyzM" }, mediaAlt: "Blueprint-style visualization of a connected smart-city grid." }] }),
  "smart-infrastructure.ev-grid": entry(adapter, "Smart infrastructure Block2Section JSX literals", { eyebrow: "Case Study", heading: "Smart EV Charging Grid", body: "Implementing a city-wide load-balancing network for electric vehicle charging, reducing grid peak-load by 35% through localized intelligence.", media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuCmSbVNlyj8qyO5T3Mcjdtg_ceBkU8fphwSZOSB1tKykl1v6J8_kW4qMWQOa7iHMHWYyhjdQ8wm6CHLVyvky6hSENDaMEVgWaFQRfSlFmircoe3v5rjA2zVc0yVisdnzXt5-PN8glyI6u2DtubWzrMBFKebl5D0mL69Abs78_7EzrSBx9Ybl6PSwjrKVL6pRZbHsVh8CaD1Zb8_5kGcx5HFZyopniHu01xL_K-0PdVbvxwxaLdzZOVrkgw_5tw-nhkaSWs7p0Oow1g" }, mediaAlt: "Modern EV charging station at night with illuminated charging posts.", callouts: [{ value: "35%", label: "Peak Reduction" }, { value: "2.4k", label: "Active Nodes" }], actions: [{ label: "VIEW FULL TECHNICAL REPORT", action: "developer-controlled" }] }),
  "smart-infrastructure.modernization": entry(adapter, "Smart infrastructure Block3Section JSX literals", { title: "Ready to Modernize?", body: "Connect with our systems engineers to discuss your city's digital transformation roadmap.", actions: [{ label: "Connect Your City", action: "developer-controlled" }, action("Download Brochure", "/technical-downloads-and-sdks")] }),
  "oil-gas.challenges": entry(adapter, "Oil and gas ExplosiveEnvironmentsSection JSX literals", { heading: "Critical Challenges", introduction: "Addressing the friction points of modern energy extraction with surgical precision and hardened hardware.", cards: [{ title: "Explosive Environments", body: "Operations in Zone 0 and Zone 1 environments require more than just ruggedization. We design for **ATEX/IECEx** intrinsic safety from the component level up.", badges: ["CERTIFICATION: Class I, Division 1", "COMPLIANCE: EN 60079 Series"] }, { title: "Asset Degradation", body: "Continuous monitoring for hydrogen embrittlement and chloride-induced corrosion in high-salinity marine air.", label: "SENSITIVITY Â±0.01mm" }, { title: "Remote Connectivity", body: "Bridging the gap in \"dark zones\" where terrestrial networks fail. Our multi-path backhaul ensures data integrity from deep sea to desert floor.", items: ["Satellite Backhaul Integration", "LoRaWAN Long-Range Mesh", "Private LTE/5G Deployments"], media: { source: "/industries/RemoteConnectivityNetwork.webp" }, mediaAlt: "Remote oil field connected through a digital mesh and satellite network." }] }),
  "oil-gas.solutions": entry(adapter, "Oil and gas SmallAccentSection JSX literals", { heading: "Integrated Solutions", cards: [{ title: "Intrinsically Safe Sensors", body: "Non-sparking hardware engineered with energy-limiting circuits for safe operation in the presence of flammable gases." }, { title: "Remote Telemetry Units (RTUs)", body: "Edge computing nodes that aggregate, filter, and transmit data via high-efficiency Modbus and MQTT protocols." }, { title: "Corrosion Monitoring", body: "Ultrasonic and electrochemical sensors that detect structural fatigue before catastrophic failure occurs." }, { eyebrow: "Core Expertise", title: "10-Year Battery Life", body: "We optimize firmware at the kernel level to ensure that once a sensor is deployed, it stays operational for a decade without human intervention.", metrics: [{ value: "1.2ÂµA", label: "SLEEP" }, { value: "45mA", label: "ACTIVE" }, { value: "250ms", label: "CYCLE" }] }] }),
  "oil-gas.stack-marquee": entry(adapter, "Oil and gas Section JSX literals", { heading: "The Stack", items: ["Modbus TCP/RTU", "LoRaWAN Mesh", "Satellite Backhaul", "Ultra-Low Power", "MQTT Sparkplug B"].map((label) => ({ label })) }),
  "oil-gas.quantum-ready": entry(adapter, "Oil and gas Block2Section JSX literals", { eyebrow: "Case Study 01", title: "Quantum-Ready Data Architecture", body: "For a major offshore operator, we developed a decentralized data architecture capable of handling multi-terabyte streams from subsea sensors, encrypted with post-quantum algorithms to safeguard national energy interests.", bullets: [{ value: "40%", label: "Efficiency Gain" }, { value: "Zero", label: "Downtime Incidents" }], callouts: [{ label: "QUANTUM ENCRYPTION LAYER V2.4" }], links: [action("READ FULL REPORT", "/quantum-ready-data-architecture")] }),
  "oil-gas.hardening": entry(adapter, "Oil and gas AtmosphericBgElementSection content literals; decoration excluded", { title: "Ready to harden your infrastructure?", body: "Connect with our industry-leading engineers to discuss your project specifics and safety requirements.", actions: [action("SECURE YOUR OPERATIONS", "/quantum-ready-data-architecture"), action("REQUEST TECHNICAL SPECS", "/quantum-ready-data-architecture")] }),
  "pipeline.vulnerabilities": entry(adapter, "Pipeline monitoring Section JSX literals", { eyebrow: "The Critical Challenge", heading: "Unseen Vulnerabilities", cards: [{ title: "Hundreds of miles of remote infrastructure", body: "Monitoring vast, uninhabited terrain requires more than just periodic checks. Our systems provide 24/7 visibility over transcontinental assets with zero blind spots.", metrics: [{ value: "0.5m", label: "Leak Accuracy" }, { value: "1k+", label: "Miles Covered" }, { value: "10ms", label: "Response Time" }] }, { title: "Sensor synchronization", body: "Legacy systems suffer from temporal drift. We solve synchronization at the hardware level, ensuring that every data point across thousands of nodes aligns to a universal clock." }] }),
  "pipeline.solutions": entry(adapter, "Pipeline monitoring Solution1Section JSX literals", { eyebrow: "Technical Authority", heading: "Integrated Monitoring Solutions", introduction: "Machined precision in hardware meets sophisticated algorithmic analysis for absolute infrastructure certainty.", cards: [{ badge: "MODULE 01", title: "Distributed acoustic sensing hubs", body: "Utilizing fiber-optic cables as thousands of discrete sensors to detect vibration signatures of potential leaks.", items: ["40km sensing range per hub", "Real-time spectral analysis"] }, { badge: "MODULE 02", title: "Pressure-wave analysis modules", body: "Advanced algorithms that isolate the unique transient pressure waves generated by pipeline wall breaches.", items: ["Sub-millisecond event detection", "False alarm mitigation AI"] }, { badge: "MODULE 03", title: "Solar-powered wireless nodes", body: "Self-sustaining edge devices designed for harsh environments, providing connectivity in the most remote areas.", items: ["10-year battery life cycle", "IP68 industrial enclosure"] }] }),
  "pipeline.technical-superiority": entry(adapter, "Pipeline monitoring Block2Section JSX literals", { title: "Engineered for Technical Superiority", bullets: [{ title: "GPS Synchronization", body: "Nanosecond-level timing accuracy across global sensor networks for perfect data correlation." }, { title: "Sub-millisecond Logging", body: "High-speed data acquisition at the edge ensures no transient events are missed." }, { title: "NB-IoT Connectivity", body: "Narrowband internet-of-things protocol for deep penetration and ultra-low power consumption." }], callouts: [{ eyebrow: "Hardware Interface", title: "Matrix V2 Node" }] }),
  "pipeline.asset-tracking": entry(adapter, "Pipeline monitoring Block3Section JSX literals", { eyebrow: "Case Study", heading: "Global Asset Tracking", body: "We implemented an end-to-end monitoring solution for a 2,500km natural gas corridor, reducing leak detection latency from hours to seconds and preventing millions in potential environmental damage.", media: { source: null, status: "not present in source section" }, bullets: [{ title: "Wireless sensor networks", body: "Mesh architectures designed for redundancy in zero-signal zones." }, { title: "High-precision measurement", body: "Grade-A industrial sensors with calibrated sub-micron sensitivity." }], actions: [action("View Full Technical Case Study", "/wireless-sensor-network")] }),
  "pipeline.security": entry(adapter, "Pipeline monitoring Block4Section JSX literals", { title: "Ready to secure your pipeline?", body: "Our engineering team is ready to design a bespoke monitoring matrix for your specific infrastructure requirements.", actions: [action("Monitor Your Infrastructure", "/wireless-sensor-network")] }),
  "quantum-ready.risks": entry(adapter, "Quantum-ready data architecture Section JSX literals", { heading: "The Vulnerability Matrix", introduction: "Legacy protocols in offshore energy facilities represent a critical failure point. In an era where quantum computing threats are approaching the horizon, traditional encryption is no longer sufficient for 24/7 critical connectivity.", cards: [{ title: "The Problem", body: "Vulnerable legacy protocols in critical energy infrastructure prone to interception and exploitation." }, { title: "The Challenge", body: "Maintaining 100% uptime while implementing post-quantum threat protection across remote edge environments." }, { title: "SIMULATION: CRYPTOGRAPHIC DECAY MODEL" }] }),
  "quantum-ready.architecture": entry(adapter, "Quantum-ready data architecture HardwareSection JSX literals", { heading: "The Architecture of Certainty", introduction: "A multi-layered defense strategy integrating Hardware, Firmware, and Cloud.", nodes: [{ id: "hardware", label: "Ruggedized ARM-based Gateway", description: "Integrated TPM 2.0 and dedicated Hardware Security Modules (HSM) provide a physical root of trust in extreme industrial environments.", badges: ["ARM Cortex-A Processing Unit", "MIL-STD-810H Compliance", "Redundant Power Supply"], media: { source: "https://lh3.googleusercontent.com/aida-public/AB6AXuBGFu9ErAAoYTKHXb3YsTQGxQod1qm7eAbYUzyBRZO-MLrn-AthTXYXee8pplc1-Mt3rY0df4my7CCB_A2v4RQ2UmFGz5NFdTJfl5Obwt4CFi_MOSntNzJH3h3w31UeohAnoUde6rqab_BSgkIn2gRiwEjrIzyHeTy1JmMKgASozSsKRXuDmfYmu9n6g_QN230EZC9NpME8dXnVlB4KL4ZGKr0FsCD29xne8sYrJkj_S_mShPLIcTWyGexUUB-3rVw0O-3zppW-w8g" }, mediaAlt: "Rugged industrial ARM-based gateway with cooling fins and industrial connectors." }, { id: "firmware", label: "Firmware & Encryption", description: "Secure boot chains and a TLS 1.3 encrypted firmware stack ensure that only verified, signed updates can be executed on the edge device." }, { id: "cloud", label: "End-to-End Cloud Sync", description: "Seamless integration with AWS IoT Core provides global visibility while maintaining a zero-trust posture across all data transits." }], annotations: [{ label: "Cloud Platform", value: "AWS IoT Core" }, { label: "Encryption", value: "TLS 1.3 + PQC" }, { label: "Processor", value: "ARM Cortex-A" }, { label: "OS", value: "Yocto Linux" }] }),
  "quantum-ready.success": entry(adapter, "Quantum-ready data architecture Block2Section JSX literals", { heading: "Mission Success Metrics", introduction: "Our deployment delivered absolute technical authority over data assets in one of the world's most hostile digital environments.", items: [{ value: "100%", label: "Data Integrity" }, { value: "0", label: "Breaches Detected" }, { value: "24/7", label: "Connectivity" }] }),
  "quantum-ready.outcomes": entry(adapter, "Quantum-ready data architecture Block3Section JSX literals", { heading: "Customer Outcomes", introduction: "Moving beyond implementation into long-term strategic value and future-proofed operations.", cards: [{ title: "Future-Proofed Security", body: "Architecture designed for tomorrow's quantum threats, eliminating the need for expensive hardware retrofitting in the next decade." }, { title: "Regulatory Compliance", body: "Exceeds current NIST and IEC 62443 standards for industrial control systems, simplifying audits and insurance requirements." }] }),
  "quantum-ready.security": entry(adapter, "Quantum-ready data architecture Block4Section JSX literals", { title: "Secure Your Digital Perimeter", body: "Our engineering team is ready to audit your existing infrastructure and design a roadmap for quantum resilience.", actions: [action("Audit Your Infrastructure Security", "/iot"), action("Download Technical Spec", "/iot")] }),
};
